DEF cAttribmap01_3F_GAMEVERSION        EQUS "\"./build/attribmaps/013F_kuwagata.map\""
DEF cAttribmap01_45_GAMEVERSION        EQUS "\"./build/attribmaps/0142.map\""
DEF cAttribmap01_46_GAMEVERSION        EQUS "\"./build/attribmaps/0146_kuwagata.map\""
DEF cAttribmap01_47_GAMEVERSION        EQUS "\"./build/attribmaps/0147_kuwagata.map\""
DEF cAttribmap01_48_GAMEVERSION        EQUS "\"./build/attribmaps/0148_kuwagata.map\""
DEF cAttribmap01_49_GAMEVERSION        EQUS "\"./build/attribmaps/0149_kuwagata.map\""
DEF cAttribmap01_4A_GAMEVERSION        EQUS "\"./build/attribmaps/014A_kuwagata.map\""
DEF cAttribmap01_4B_GAMEVERSION        EQUS "\"./build/attribmaps/014B_kuwagata.map\""
DEF cAttribmap01_4C_GAMEVERSION        EQUS "\"./build/attribmaps/014C_kuwagata.map\""
DEF cAttribmap01_4D_GAMEVERSION        EQUS "\"./build/attribmaps/014D_kuwagata.map\""
DEF cAttribmap01_4E_GAMEVERSION        EQUS "\"./build/attribmaps/014E_kuwagata.map\""

INCLUDE "./game/src/version/attribmap_table.asm"
