DEF cTilemap01_27_GAMEVERSION        EQUS "\"./build/tilemaps/0127_kuwagata.map\""
DEF cTilemap01_4C_GAMEVERSION        EQUS "\"./build/tilemaps/014C_kuwagata.map\""
DEF cTilemap01_4D_GAMEVERSION        EQUS "\"./build/tilemaps/014D_kuwagata.map\""
DEF cTilemap01_4E_GAMEVERSION        EQUS "\"./build/tilemaps/014E_kuwagata.map\""
DEF cTilemap01_4F_GAMEVERSION        EQUS "\"./build/tilemaps/014F_kuwagata.map\""
DEF cTilemap01_56_GAMEVERSION        EQUS "\"./build/tilemaps/0156_kuwagata.map\""
DEF cTilemap01_57_GAMEVERSION        EQUS "\"./build/tilemaps/0157_kuwagata.map\""
DEF cTilemap01_58_GAMEVERSION        EQUS "\"./build/tilemaps/0158_kuwagata.map\""
DEF cTilemap01_59_GAMEVERSION        EQUS "\"./build/tilemaps/0159_kuwagata.map\""
DEF cTilemap01_5A_GAMEVERSION        EQUS "\"./build/tilemaps/015A_kuwagata.map\""
DEF cTilemap01_5B_GAMEVERSION        EQUS "\"./build/tilemaps/015B_kuwagata.map\""
DEF cTilemap01_5C_GAMEVERSION        EQUS "\"./build/tilemaps/015C_kuwagata.map\""
DEF cTilemap01_5D_GAMEVERSION        EQUS "\"./build/tilemaps/015D_kuwagata.map\""
DEF cTilemap01_5E_GAMEVERSION        EQUS "\"./build/tilemaps/015E_kuwagata.map\""

INCLUDE "./game/src/version/tilemap_table.asm"
