; File initially autogenerated by ./scripts/dump_tilesets_misc.py

SECTION "Tileset CreditsFont", ROMX[$4000], BANK[$18]
TilesetCreditsFont::
  INCBIN "./build/tilesets/CreditsFont.2bpp"
SECTION "Tileset CreditsFont End", ROMX[$72DF], BANK[$18]

