; Autogenerated by ./scripts/dump_metasprites.py

INCLUDE "./game/src/version/metasprites00.asm"
INCLUDE "./game/src/version/metasprites01.asm"
INCLUDE "./game/src/version/metasprites02.asm"
INCLUDE "./game/src/version/metasprites03.asm"
INCLUDE "./game/src/version/metasprites04.asm"
INCLUDE "./game/src/version/metasprites05.asm"
INCLUDE "./game/src/version/metasprites06.asm"
INCLUDE "./game/src/version/metasprites07.asm"
