cTilemap01_27_GAMEVERSION        EQUS "\"./build/tilemaps/0127_kabuto.map\""
cTilemap01_4C_GAMEVERSION        EQUS "\"./build/tilemaps/014C_kabuto.map\""
cTilemap01_4D_GAMEVERSION        EQUS "\"./build/tilemaps/014D_kabuto.map\""
cTilemap01_4E_GAMEVERSION        EQUS "\"./build/tilemaps/014E_kabuto.map\""
cTilemap01_4F_GAMEVERSION        EQUS "\"./build/tilemaps/014F_kabuto.map\""
cTilemap01_56_GAMEVERSION        EQUS "\"./build/tilemaps/0156_kabuto.map\""
cTilemap01_57_GAMEVERSION        EQUS "\"./build/tilemaps/0157_kabuto.map\""
cTilemap01_58_GAMEVERSION        EQUS "\"./build/tilemaps/0158_kabuto.map\""
cTilemap01_59_GAMEVERSION        EQUS "\"./build/tilemaps/0159_kabuto.map\""
cTilemap01_5A_GAMEVERSION        EQUS "\"./build/tilemaps/015A_kabuto.map\""
cTilemap01_5B_GAMEVERSION        EQUS "\"./build/tilemaps/015B_kabuto.map\""
cTilemap01_5C_GAMEVERSION        EQUS "\"./build/tilemaps/015C_kabuto.map\""
cTilemap01_5D_GAMEVERSION        EQUS "\"./build/tilemaps/015D_kabuto.map\""
cTilemap01_5E_GAMEVERSION        EQUS "\"./build/tilemaps/015E_kabuto.map\""

INCLUDE "./game/src/version/tilemap_table.asm"
