H_RegJoyp           EQU $ff00
H_RegSB             EQU $ff01
H_RegSC             EQU $ff02
H_RegDIV            EQU $ff04
H_RegTIMA           EQU $ff05
H_RegTMA            EQU $ff06
H_RegTAC            EQU $ff07
H_RegIF             EQU $ff0f
H_RegNR10           EQU $ff10
H_RegNR11           EQU $ff11
H_RegNR12           EQU $ff12
H_RegNR13           EQU $ff13
H_RegNR14           EQU $ff14
H_RegNR21           EQU $ff16
H_RegNR22           EQU $ff17
H_RegNR23           EQU $ff18
H_RegNR24           EQU $ff19
H_RegNR30           EQU $ff1a
H_RegNR31           EQU $ff1b
H_RegNR32           EQU $ff1c
H_RegNR33           EQU $ff1d
H_RegNR34           EQU $ff1e
H_RegNR41           EQU $ff20
H_RegNR42           EQU $ff21
H_RegNR43           EQU $ff22
H_RegNR44           EQU $ff23
H_RegNR50           EQU $ff24
H_RegNR51           EQU $ff25
H_RegNR52           EQU $ff26
H_RegLCDC           EQU $ff40
H_LCDStat           EQU $ff41
H_RegSCY            EQU $ff42
H_RegSCX            EQU $ff43
H_RegLY             EQU $ff44
H_RegLYC            EQU $ff45
H_RegDMA            EQU $ff46
H_RegBGP            EQU $ff47
H_RegOBP0           EQU $ff48
H_RegOBP1           EQU $ff49
H_RegWY             EQU $ff4a
H_RegWX             EQU $ff4b
H_RegKEY1           EQU $ff4d
H_RegVBK            EQU $ff4f
H_RegHDMA1          EQU $ff51
H_RegHDMA2          EQU $ff52
H_RegHDMA3          EQU $ff53
H_RegHDMA4          EQU $ff54
H_RegHDMA5          EQU $ff55
H_RegRP             EQU $ff56
H_RegBGPI           EQU $ff68
H_RegBGPD           EQU $ff69
H_RegOBPI           EQU $ff6a
H_RegOBPD           EQU $ff6b
H_RegSVBK           EQU $ff70
H_RegIE             EQU $ffff

H_PushOAM           EQU $ff80

; Joypad
H_JPInputHeldDown   EQU $ff8c
H_JPInputChanged    EQU $ff8d

H_VBlankCompleted   EQU $ff92

H_SoundEffect       EQU $ffa1

M_JPInputA          EQU $1
M_JPInputB          EQU $2
M_JPInputSelect     EQU $4
M_JPInputStart      EQU $8
M_JPInputRight      EQU $10
M_JPInputLeft       EQU $20
M_JPInputUp         EQU $40
M_JPInputDown       EQU $80

X_MBC5SRAMEnable    EQU $0000
X_MBC5ROMBankLow    EQU $2000
X_MBC5ROMBankHigh   EQU $3000
X_MBC5SRAMBank      EQU $4000

M_MedarotSlotLength   EQU $10

M_MedarotEquipState   EQU $0
M_MedarotType         EQU $1
M_MedarotMedal        EQU $2
M_MedarotHead         EQU $3
M_MedarotLeftArm      EQU $4
M_MedarotRightArm     EQU $5
M_MedarotLegs         EQU $6
M_MedarotPalette      EQU $7

M_MedalSlotLength     EQU $40

M_MedalStatus         EQU $0
M_MedalType           EQU $1
M_MedalExpLower       EQU $2
M_MedalExpUpper       EQU $3
M_MedalImage          EQU $4
M_MedalMedaforceA     EQU $5
M_MedalMedaforceB     EQU $6
M_MedalMedaforceC     EQU $7
M_MedalAttribute      EQU $8
M_MedalLevel          EQU $9
M_MedalPersonality    EQU $A
M_MedalCompatibility  EQU $B
M_MedalSkillAIndex    EQU $19
M_MedalSkillAUses     EQU $1A
M_MedalSkillAExp      EQU $1B
M_MedalSkillAPadding  EQU $1C
M_MedalSkillBIndex    EQU $1D
M_MedalSkillBUses     EQU $1E
M_MedalSkillBExp      EQU $1F
M_MedalSkillBPadding  EQU $20
M_MedalSkillCIndex    EQU $21
M_MedalSkillCUses     EQU $22
M_MedalSkillCExp      EQU $23
M_MedalMedaliaAStatus EQU $24
M_MedalMedaliaASkill  EQU $25
M_MedalMedaliaAUses   EQU $26
M_MedalMedaliaAExp    EQU $27
M_MedalMedaliaBStatus EQU $28
M_MedalMedaliaBSkill  EQU $29
M_MedalMedaliaBUses   EQU $2A
M_MedalMedaliaBExp    EQU $2B
M_MedalMedaliaCStatus EQU $2C
M_MedalMedaliaCSkill  EQU $2D
M_MedalMedaliaCUses   EQU $2E
M_MedalMedaliaCExp    EQU $2F
M_MedalNickname       EQU $30

M_CreditConfigLength    EQU $0C
M_CreditConfigAniIndex  EQU $00
M_CreditConfigDirection EQU $01
M_CreditConfigTimer     EQU $02
M_CreditConfigActIndex  EQU $03
M_CreditConfigPageNum   EQU $04
M_CreditConfigTextIndex EQU $05

M_CreditTextConfigYPos        EQU $00
M_CreditTextConfigXPos        EQU $01
M_CreditTextConfigPalette     EQU $03
M_CreditTextConfigText        EQU $04
