; Autogenerated by ./scripts/dump_metasprites.py

SECTION "Metasprite Table 07", ROMX[$640C], BANK[$32]
MetaspriteTable07::
  dw Metasprite0700
  dw Metasprite0701
  dw Metasprite0702
  dw Metasprite0703
  dw Metasprite0704
  dw Metasprite0705
  dw Metasprite0706
  dw Metasprite0707
  dw Metasprite0708
  dw Metasprite0709
  dw Metasprite070A
  dw Metasprite070B
  dw Metasprite070C
  dw Metasprite070D
  dw Metasprite070E
  dw Metasprite070F
  dw Metasprite0710
  dw Metasprite0711
  dw Metasprite0712
  dw Metasprite0713
  dw Metasprite0714
  dw Metasprite0715
  dw Metasprite0716
  dw Metasprite0717
  dw Metasprite0718
  dw Metasprite0719
  dw Metasprite071A
  dw Metasprite071B
  dw Metasprite071C
  dw Metasprite071D
  dw Metasprite071E
  dw Metasprite071F
  dw Metasprite0720
  dw Metasprite0721
  dw Metasprite0722
  dw Metasprite0723
  dw Metasprite0724
  dw Metasprite0725
  dw Metasprite0726
  dw Metasprite0727
  dw Metasprite0728
  dw Metasprite0729
  dw Metasprite072A
  dw Metasprite072B
  dw Metasprite072C
  dw Metasprite072D
  dw Metasprite072E
  dw Metasprite072F
  dw Metasprite0730
  dw Metasprite0731
  dw Metasprite0731
  dw Metasprite0733
  dw Metasprite0734
  dw Metasprite0735
  dw Metasprite0736
  dw Metasprite0737
  dw Metasprite0738
  dw Metasprite0739
  dw Metasprite073A
  dw Metasprite073B
  dw Metasprite073C
  dw Metasprite073D
  dw Metasprite073E
  dw Metasprite073F
  dw Metasprite0740
  dw Metasprite0741
  dw Metasprite0742
  dw Metasprite0743
  dw Metasprite0744
  dw Metasprite0745
  dw Metasprite0746
  dw Metasprite0747
  dw Metasprite0748
  dw Metasprite0749
  dw Metasprite074A
  dw Metasprite074B
  dw Metasprite074B
  dw Metasprite074D
  dw Metasprite074E
  dw Metasprite074F
  dw Metasprite0750
  dw Metasprite0751
  dw Metasprite0751
  dw Metasprite0753
  dw Metasprite0754
  dw Metasprite0755
  dw Metasprite0756
  dw Metasprite0757
  dw Metasprite0758
  dw Metasprite0759
  dw Metasprite075A
  dw Metasprite075B
  dw Metasprite075C
  dw Metasprite075D
  dw Metasprite075E
  dw Metasprite075F
  dw Metasprite0760
  dw Metasprite0761
  dw Metasprite0762
  dw Metasprite0763
  dw Metasprite0764
  dw Metasprite0765
  dw Metasprite0766
  dw Metasprite0767
  dw Metasprite0768
  dw Metasprite0769
  dw Metasprite076A
  dw Metasprite076B
  dw Metasprite076B
  dw Metasprite076D
  dw Metasprite076E
  dw Metasprite076F
  dw Metasprite0770
  dw Metasprite0771
  dw Metasprite0772
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0773
  dw Metasprite0781
  dw Metasprite0782
  dw Metasprite0783
  dw Metasprite0784
  dw Metasprite0785
  dw Metasprite0786
  dw Metasprite0787
  dw Metasprite0788
  dw Metasprite0789
  dw Metasprite078A
  dw Metasprite078B
  dw Metasprite078C
  dw Metasprite078D
  dw Metasprite078E
  dw Metasprite078F
  dw Metasprite0790
  dw Metasprite0791
  dw Metasprite0792
  dw Metasprite0793
  dw Metasprite0794
  dw Metasprite0795
  dw Metasprite0796
  dw Metasprite0797
  dw Metasprite0798
  dw Metasprite0799
  dw Metasprite079A
  dw Metasprite079B
  dw Metasprite079C
  dw Metasprite079D
  dw Metasprite079E
  dw Metasprite079F
  dw Metasprite07A0
  dw Metasprite07A1
  dw Metasprite07A2
  dw Metasprite07A3
  dw Metasprite07A4
  dw Metasprite07A5
  dw Metasprite07A6
  dw Metasprite07A7
  dw Metasprite07A8
  dw Metasprite07A9
  dw Metasprite07AA
  dw Metasprite07AB
  dw Metasprite07AC
  dw Metasprite07AD
  dw Metasprite07AE
  dw Metasprite07AF
  dw Metasprite07B0
  dw Metasprite07B1
  dw Metasprite07B2
  dw Metasprite07B3
  dw Metasprite07B4
  dw Metasprite07B5
  dw Metasprite07B6
  dw Metasprite07B7
  dw Metasprite07B8
  dw Metasprite07B9
  dw Metasprite07BA
  dw MetaspriteTable07End
  dw MetaspriteTable07End
  dw MetaspriteTable07End
  dw MetaspriteTable07End
  dw MetaspriteTable07End
Metasprite0700::
  db $09
  db $00,$EC,$00,$02,$18
  db $00,$F4,$01,$02,$18
  db $00,$FC,$02,$02,$18
  db $08,$EC,$03,$02,$18
  db $08,$F4,$04,$02,$18
  db $08,$FC,$05,$02,$18
  db $10,$EC,$06,$02,$18
  db $10,$F4,$07,$02,$18
  db $10,$FC,$08,$02,$18
Metasprite0701::
  db $09
  db $00,$FC,$02,$02,$38
  db $00,$04,$01,$02,$38
  db $00,$0C,$00,$02,$38
  db $08,$FC,$05,$02,$38
  db $08,$04,$04,$02,$38
  db $08,$0C,$03,$02,$38
  db $10,$FC,$08,$02,$38
  db $10,$04,$07,$02,$38
  db $10,$0C,$06,$02,$38
Metasprite0702::
  db $0F
  db $F0,$EC,$09,$02,$18
  db $F0,$F4,$0A,$02,$18
  db $F0,$FC,$0B,$02,$18
  db $F8,$EC,$0C,$02,$18
  db $F8,$F4,$0D,$02,$18
  db $F8,$FC,$0E,$02,$18
  db $00,$EC,$0F,$02,$18
  db $00,$F4,$10,$02,$18
  db $00,$FC,$11,$02,$18
  db $08,$EC,$12,$02,$18
  db $08,$F4,$13,$02,$18
  db $08,$FC,$14,$02,$18
  db $10,$EC,$15,$02,$18
  db $10,$F4,$16,$02,$18
  db $10,$FC,$17,$02,$18
Metasprite0703::
  db $0F
  db $F0,$FC,$0B,$02,$38
  db $F0,$04,$0A,$02,$38
  db $F0,$0C,$09,$02,$38
  db $F8,$FC,$0E,$02,$38
  db $F8,$04,$0D,$02,$38
  db $F8,$0C,$0C,$02,$38
  db $00,$FC,$11,$02,$38
  db $00,$04,$10,$02,$38
  db $00,$0C,$0F,$02,$38
  db $08,$FC,$14,$02,$38
  db $08,$04,$13,$02,$38
  db $08,$0C,$12,$02,$38
  db $10,$FC,$17,$02,$38
  db $10,$04,$16,$02,$38
  db $10,$0C,$15,$02,$38
Metasprite0704::
  db $0F
  db $F0,$EC,$18,$02,$18
  db $F0,$F4,$19,$02,$18
  db $F0,$FC,$1A,$02,$18
  db $F8,$EC,$1B,$02,$18
  db $F8,$F4,$1C,$02,$18
  db $F8,$FC,$1D,$02,$18
  db $00,$EC,$1E,$02,$18
  db $00,$F4,$1F,$02,$18
  db $00,$FC,$20,$02,$18
  db $08,$EC,$21,$02,$18
  db $08,$F4,$22,$02,$18
  db $08,$FC,$23,$02,$18
  db $10,$EC,$24,$02,$18
  db $10,$F4,$25,$02,$18
  db $10,$FC,$26,$02,$18
Metasprite0705::
  db $0F
  db $F0,$FC,$1A,$02,$38
  db $F0,$04,$19,$02,$38
  db $F0,$0C,$18,$02,$38
  db $F8,$FC,$1D,$02,$38
  db $F8,$04,$1C,$02,$38
  db $F8,$0C,$1B,$02,$38
  db $00,$FC,$20,$02,$38
  db $00,$04,$1F,$02,$38
  db $00,$0C,$1E,$02,$38
  db $08,$FC,$23,$02,$38
  db $08,$04,$22,$02,$38
  db $08,$0C,$21,$02,$38
  db $10,$FC,$26,$02,$38
  db $10,$04,$25,$02,$38
  db $10,$0C,$24,$02,$38
Metasprite0706::
  db $10
  db $F0,$F0,$27,$02,$18
  db $F0,$F8,$28,$02,$18
  db $F0,$00,$29,$02,$18
  db $F0,$08,$2A,$02,$18
  db $F8,$F0,$2B,$02,$18
  db $F8,$F8,$2C,$02,$18
  db $F8,$00,$2D,$02,$18
  db $F8,$08,$2E,$02,$18
  db $00,$F0,$2F,$02,$18
  db $00,$F8,$30,$02,$18
  db $00,$00,$31,$02,$18
  db $00,$08,$32,$02,$18
  db $08,$F0,$33,$02,$18
  db $08,$F8,$34,$02,$18
  db $08,$00,$35,$02,$18
  db $08,$08,$36,$02,$18
Metasprite0707::
  db $09
  db $F4,$F4,$37,$02,$18
  db $F4,$FC,$38,$02,$18
  db $F4,$04,$39,$02,$18
  db $FC,$F4,$3A,$02,$18
  db $FC,$FC,$3B,$02,$18
  db $FC,$04,$3C,$02,$18
  db $04,$F4,$3D,$02,$18
  db $04,$FC,$3E,$02,$18
  db $04,$04,$3F,$02,$18
Metasprite0708::
  db $04
  db $F8,$F4,$00,$01,$1D
  db $F8,$FC,$01,$01,$1D
  db $00,$F4,$02,$01,$1D
  db $00,$FC,$03,$01,$1D
Metasprite0709::
  db $04
  db $F8,$FC,$01,$01,$3D
  db $F8,$04,$00,$01,$3D
  db $00,$FC,$03,$01,$3D
  db $00,$04,$02,$01,$3D
Metasprite070A::
  db $04
  db $F8,$F4,$04,$01,$1D
  db $F8,$FC,$05,$01,$1D
  db $00,$F4,$06,$01,$1D
  db $00,$FC,$07,$01,$1D
Metasprite070B::
  db $04
  db $F8,$FC,$05,$01,$3D
  db $F8,$04,$04,$01,$3D
  db $00,$FC,$07,$01,$3D
  db $00,$04,$06,$01,$3D
Metasprite070C::
  db $04
  db $F8,$F4,$08,$01,$1C
  db $F8,$FC,$09,$01,$1C
  db $00,$F4,$0A,$01,$1C
  db $00,$FC,$0B,$01,$1C
Metasprite070D::
  db $04
  db $F8,$FC,$09,$01,$3C
  db $F8,$04,$08,$01,$3C
  db $00,$FC,$0B,$01,$3C
  db $00,$04,$0A,$01,$3C
Metasprite070E::
  db $04
  db $F8,$F4,$0C,$01,$1C
  db $F8,$FC,$0D,$01,$1C
  db $00,$F4,$0E,$01,$1C
  db $00,$FC,$0F,$01,$1C
Metasprite070F::
  db $04
  db $F8,$FC,$0D,$01,$3C
  db $F8,$04,$0C,$01,$3C
  db $00,$FC,$0F,$01,$3C
  db $00,$04,$0E,$01,$3C
Metasprite0710::
  db $04
  db $F8,$F4,$10,$01,$1F
  db $F8,$FC,$11,$01,$1F
  db $00,$F4,$12,$01,$1F
  db $00,$FC,$13,$01,$1F
Metasprite0711::
  db $04
  db $F8,$FC,$11,$01,$3F
  db $F8,$04,$10,$01,$3F
  db $00,$FC,$13,$01,$3F
  db $00,$04,$12,$01,$3F
Metasprite0712::
  db $04
  db $F8,$F4,$14,$01,$1F
  db $F8,$FC,$15,$01,$1F
  db $00,$F4,$16,$01,$1F
  db $00,$FC,$17,$01,$1F
Metasprite0713::
  db $04
  db $F8,$FC,$15,$01,$3F
  db $F8,$04,$14,$01,$3F
  db $00,$FC,$17,$01,$3F
  db $00,$04,$16,$01,$3F
Metasprite0714::
  db $02
  db $FC,$F4,$1C,$01,$1B
  db $FC,$FC,$1D,$01,$1B
Metasprite0715::
  db $02
  db $FC,$FC,$1D,$01,$3B
  db $FC,$04,$1C,$01,$3B
Metasprite0716::
  db $04
  db $FC,$E4,$18,$01,$18
  db $FC,$EC,$19,$01,$18
  db $FC,$F4,$1C,$01,$1B
  db $FC,$FC,$1D,$01,$1B
Metasprite0717::
  db $04
  db $FC,$FC,$1D,$01,$3B
  db $FC,$04,$1C,$01,$3B
  db $FC,$0C,$19,$01,$38
  db $FC,$14,$18,$01,$38
Metasprite0718::
  db $04
  db $FC,$E4,$1A,$01,$18
  db $FC,$EC,$1B,$01,$18
  db $FC,$F4,$1E,$01,$1B
  db $FC,$FC,$1F,$01,$1B
Metasprite0719::
  db $04
  db $FC,$FC,$1F,$01,$3B
  db $FC,$04,$1E,$01,$3B
  db $FC,$0C,$1B,$01,$38
  db $FC,$14,$1A,$01,$38
Metasprite071A::
  db $08
  db $F8,$EC,$20,$01,$19
  db $F8,$F4,$21,$01,$19
  db $F8,$FC,$22,$01,$19
  db $00,$EC,$23,$01,$19
  db $00,$F4,$24,$01,$19
  db $00,$FC,$25,$01,$19
  db $FC,$DC,$18,$01,$18
  db $FC,$E4,$19,$01,$18
Metasprite071B::
  db $08
  db $F8,$FC,$22,$01,$39
  db $F8,$04,$21,$01,$39
  db $F8,$0C,$20,$01,$39
  db $00,$FC,$25,$01,$39
  db $00,$04,$24,$01,$39
  db $00,$0C,$23,$01,$39
  db $FC,$14,$19,$01,$38
  db $FC,$1C,$18,$01,$38
Metasprite071C::
  db $08
  db $F8,$EC,$26,$01,$19
  db $F8,$F4,$27,$01,$19
  db $F8,$FC,$28,$01,$19
  db $00,$EC,$29,$01,$19
  db $00,$F4,$2A,$01,$19
  db $00,$FC,$2B,$01,$19
  db $FC,$DC,$1A,$01,$18
  db $FC,$E4,$1B,$01,$18
Metasprite071D::
  db $08
  db $F8,$FC,$28,$01,$39
  db $F8,$04,$27,$01,$39
  db $F8,$0C,$26,$01,$39
  db $00,$FC,$2B,$01,$39
  db $00,$04,$2A,$01,$39
  db $00,$0C,$29,$01,$39
  db $FC,$14,$1B,$01,$38
  db $FC,$1C,$1A,$01,$38
Metasprite071E::
  db $08
  db $F8,$EC,$2C,$01,$19
  db $F8,$F4,$2D,$01,$19
  db $F8,$FC,$2E,$01,$19
  db $00,$EC,$2F,$01,$19
  db $00,$F4,$30,$01,$19
  db $00,$FC,$31,$01,$19
  db $FC,$DC,$18,$01,$18
  db $FC,$E4,$19,$01,$18
Metasprite071F::
  db $08
  db $F8,$FC,$2E,$01,$39
  db $F8,$04,$2D,$01,$39
  db $F8,$0C,$2C,$01,$39
  db $00,$FC,$31,$01,$39
  db $00,$04,$30,$01,$39
  db $00,$0C,$2F,$01,$39
  db $FC,$14,$19,$01,$38
  db $FC,$1C,$18,$01,$38
Metasprite0720::
  db $02
  db $F0,$FC,$01,$01,$1A
  db $F8,$FC,$00,$01,$1A
Metasprite0721::
  db $02
  db $F0,$FE,$02,$01,$3A
  db $F8,$FE,$00,$01,$7A
Metasprite0722::
  db $02
  db $F0,$FC,$01,$01,$1A
  db $F8,$FC,$00,$01,$5A
Metasprite0723::
  db $02
  db $F0,$FE,$02,$01,$3A
  db $F8,$FE,$00,$01,$3A
Metasprite0724::
  db $09
  db $F4,$F4,$03,$02,$1A
  db $F4,$FC,$04,$02,$1A
  db $F4,$04,$05,$02,$1A
  db $FC,$F4,$06,$02,$1A
  db $FC,$FC,$07,$02,$1A
  db $FC,$04,$08,$02,$1A
  db $04,$F4,$09,$02,$1A
  db $04,$FC,$0A,$02,$1A
  db $04,$04,$0B,$02,$1A
Metasprite0725::
  db $09
  db $F4,$F4,$0C,$02,$1A
  db $F4,$FC,$0D,$02,$1A
  db $F4,$04,$0E,$02,$1A
  db $FC,$F4,$0F,$02,$1A
  db $FC,$FC,$10,$02,$1A
  db $FC,$04,$11,$02,$1A
  db $04,$F4,$12,$02,$1A
  db $04,$FC,$13,$02,$1A
  db $04,$04,$14,$02,$1A
Metasprite0726::
  db $04
  db $F8,$F8,$00,$02,$18
  db $F8,$00,$01,$02,$18
  db $00,$F8,$02,$02,$18
  db $00,$00,$03,$02,$18
Metasprite0727::
  db $04
  db $F8,$F8,$04,$02,$18
  db $F8,$00,$05,$02,$18
  db $00,$F8,$06,$02,$18
  db $00,$00,$07,$02,$18
Metasprite0728::
  db $09
  db $F4,$F4,$08,$02,$18
  db $F4,$FC,$09,$02,$18
  db $F4,$04,$0A,$02,$18
  db $FC,$F4,$0B,$02,$18
  db $FC,$FC,$0C,$02,$18
  db $FC,$04,$0D,$02,$18
  db $04,$F4,$0E,$02,$18
  db $04,$FC,$0F,$02,$18
  db $04,$04,$10,$02,$18
Metasprite0729::
  db $09
  db $F4,$F4,$11,$02,$18
  db $F4,$FC,$12,$02,$18
  db $F4,$04,$13,$02,$18
  db $FC,$F4,$14,$02,$18
  db $FC,$FC,$15,$02,$18
  db $FC,$04,$16,$02,$18
  db $04,$F4,$17,$02,$18
  db $04,$FC,$18,$02,$18
  db $04,$04,$19,$02,$18
Metasprite072A::
  db $09
  db $F4,$F4,$1A,$02,$18
  db $F4,$FC,$1B,$02,$18
  db $F4,$04,$1C,$02,$18
  db $FC,$F4,$1D,$02,$18
  db $FC,$FC,$1E,$02,$18
  db $FC,$04,$1F,$02,$18
  db $04,$F4,$20,$02,$18
  db $04,$FC,$21,$02,$18
  db $04,$04,$22,$02,$18
Metasprite072B::
  db $09
  db $F4,$F4,$23,$02,$18
  db $F4,$FC,$24,$02,$18
  db $F4,$04,$25,$02,$18
  db $FC,$F4,$26,$02,$18
  db $FC,$FC,$27,$02,$18
  db $FC,$04,$28,$02,$18
  db $04,$F4,$29,$02,$18
  db $04,$FC,$2A,$02,$18
  db $04,$04,$2B,$02,$18
Metasprite072C::
  db $09
  db $F4,$F4,$2C,$02,$18
  db $F4,$FC,$2D,$02,$18
  db $F4,$04,$2E,$02,$18
  db $FC,$F4,$2F,$02,$18
  db $FC,$FC,$30,$02,$18
  db $FC,$04,$31,$02,$18
  db $04,$F4,$32,$02,$18
  db $04,$FC,$33,$02,$18
  db $04,$04,$34,$02,$18
Metasprite072D::
  db $09
  db $F4,$F4,$35,$02,$18
  db $F4,$FC,$36,$02,$18
  db $F4,$04,$37,$02,$18
  db $FC,$F4,$38,$02,$18
  db $FC,$FC,$39,$02,$18
  db $FC,$04,$3A,$02,$18
  db $04,$F4,$3B,$02,$18
  db $04,$FC,$3C,$02,$18
  db $04,$04,$3D,$02,$18
Metasprite072E::
  db $09
  db $F4,$F4,$2E,$02,$38
  db $F4,$FC,$2D,$02,$38
  db $F4,$04,$2C,$02,$38
  db $FC,$F4,$31,$02,$38
  db $FC,$FC,$30,$02,$38
  db $FC,$04,$2F,$02,$38
  db $04,$F4,$34,$02,$38
  db $04,$FC,$33,$02,$38
  db $04,$04,$32,$02,$38
Metasprite072F::
  db $09
  db $F4,$F4,$25,$02,$38
  db $F4,$FC,$24,$02,$38
  db $F4,$04,$23,$02,$38
  db $FC,$F4,$28,$02,$38
  db $FC,$FC,$27,$02,$38
  db $FC,$04,$26,$02,$38
  db $04,$F4,$2B,$02,$38
  db $04,$FC,$2A,$02,$38
  db $04,$04,$29,$02,$38
Metasprite0730::
  db $09
  db $F4,$F4,$1C,$02,$38
  db $F4,$FC,$1B,$02,$38
  db $F4,$04,$1A,$02,$38
  db $FC,$F4,$1F,$02,$38
  db $FC,$FC,$1E,$02,$38
  db $FC,$04,$1D,$02,$38
  db $04,$F4,$22,$02,$38
  db $04,$FC,$21,$02,$38
  db $04,$04,$20,$02,$38
Metasprite0731::
  db $08
  db $F0,$00,$00,$01,$1E
  db $F0,$08,$01,$01,$1E
  db $F8,$00,$02,$01,$1E
  db $F8,$08,$03,$01,$1E
  db $00,$00,$04,$01,$1E
  db $00,$08,$05,$01,$1E
  db $08,$00,$06,$01,$1E
  db $08,$08,$07,$01,$1E
Metasprite0733::
  db $08
  db $F0,$00,$08,$01,$1E
  db $F0,$08,$09,$01,$1E
  db $F8,$00,$0A,$01,$1E
  db $F8,$08,$0B,$01,$1E
  db $00,$00,$0C,$01,$1E
  db $00,$08,$0D,$01,$1E
  db $08,$00,$0E,$01,$1E
  db $08,$08,$0F,$01,$1E
Metasprite0734::
  db $08
  db $F0,$00,$10,$01,$1E
  db $F0,$08,$11,$01,$1E
  db $F8,$00,$12,$01,$1E
  db $F8,$08,$13,$01,$1E
  db $00,$00,$14,$01,$1E
  db $00,$08,$15,$01,$1E
  db $08,$00,$16,$01,$1E
  db $08,$08,$17,$01,$1E
Metasprite0735::
  db $08
  db $F0,$00,$18,$01,$1E
  db $F0,$08,$19,$01,$1E
  db $F8,$00,$1A,$01,$1E
  db $F8,$08,$1B,$01,$1E
  db $00,$00,$1C,$01,$1E
  db $00,$08,$1D,$01,$1E
  db $08,$00,$1E,$01,$1E
  db $08,$08,$1F,$01,$1E
Metasprite0736::
  db $04
  db $00,$00,$20,$01,$1A
  db $00,$08,$21,$01,$1A
  db $08,$00,$22,$01,$1A
  db $08,$08,$23,$01,$1A
Metasprite0737::
  db $0F
  db $E8,$FC,$00,$01,$1F
  db $E8,$04,$01,$01,$1F
  db $E8,$0C,$02,$01,$1F
  db $F0,$FC,$03,$01,$1F
  db $F0,$04,$04,$01,$1F
  db $F0,$0C,$05,$01,$1F
  db $F8,$FC,$06,$01,$1F
  db $F8,$04,$07,$01,$1F
  db $F8,$0C,$08,$01,$1F
  db $00,$FC,$09,$01,$1F
  db $00,$04,$0A,$01,$1F
  db $00,$0C,$0B,$01,$1F
  db $08,$FC,$0C,$01,$1F
  db $08,$04,$0D,$01,$1F
  db $08,$0C,$0E,$01,$1F
Metasprite0738::
  db $0F
  db $E8,$FC,$0F,$01,$1F
  db $E8,$04,$10,$01,$1F
  db $E8,$0C,$11,$01,$1F
  db $F0,$FC,$12,$01,$1F
  db $F0,$04,$13,$01,$1F
  db $F0,$0C,$14,$01,$1F
  db $F8,$FC,$15,$01,$1F
  db $F8,$04,$16,$01,$1F
  db $F8,$0C,$17,$01,$1F
  db $00,$FC,$18,$01,$1F
  db $00,$04,$19,$01,$1F
  db $00,$0C,$1A,$01,$1F
  db $08,$FC,$1B,$01,$1F
  db $08,$04,$1C,$01,$1F
  db $08,$0C,$1D,$01,$1F
Metasprite0739::
  db $0F
  db $E8,$FC,$1E,$01,$1F
  db $E8,$04,$1F,$01,$1F
  db $E8,$0C,$20,$01,$1F
  db $F0,$FC,$21,$01,$1F
  db $F0,$04,$22,$01,$1F
  db $F0,$0C,$23,$01,$1F
  db $F8,$FC,$24,$01,$1F
  db $F8,$04,$25,$01,$1F
  db $F8,$0C,$26,$01,$1F
  db $00,$FC,$27,$01,$1F
  db $00,$04,$28,$01,$1F
  db $00,$0C,$29,$01,$1F
  db $08,$FC,$2A,$01,$1F
  db $08,$04,$2B,$01,$1F
  db $08,$0C,$2C,$01,$1F
Metasprite073A::
  db $0F
  db $E8,$FC,$2D,$01,$1F
  db $E8,$04,$2E,$01,$1F
  db $E8,$0C,$2F,$01,$1F
  db $F0,$FC,$30,$01,$1F
  db $F0,$04,$31,$01,$1F
  db $F0,$0C,$32,$01,$1F
  db $F8,$FC,$33,$01,$1F
  db $F8,$04,$34,$01,$1F
  db $F8,$0C,$35,$01,$1F
  db $00,$FC,$36,$01,$1F
  db $00,$04,$37,$01,$1F
  db $00,$0C,$38,$01,$1F
  db $08,$FC,$39,$01,$1F
  db $08,$04,$3A,$01,$1F
  db $08,$0C,$3B,$01,$1F
Metasprite073B::
  db $04
  db $00,$00,$3C,$01,$1A
  db $00,$08,$3D,$01,$1A
  db $08,$00,$3E,$01,$1A
  db $08,$08,$3F,$01,$1A
Metasprite073C::
  db $09
  db $FC,$FC,$00,$02,$18
  db $FC,$04,$01,$02,$18
  db $FC,$0C,$02,$02,$18
  db $04,$FC,$03,$02,$18
  db $04,$04,$04,$02,$18
  db $04,$0C,$05,$02,$18
  db $0C,$FC,$06,$02,$18
  db $0C,$04,$07,$02,$18
  db $0C,$0C,$08,$02,$18
Metasprite073D::
  db $09
  db $FC,$FC,$09,$02,$18
  db $FC,$04,$0A,$02,$18
  db $FC,$0C,$0B,$02,$18
  db $04,$FC,$0C,$02,$18
  db $04,$04,$0D,$02,$18
  db $04,$0C,$0E,$02,$18
  db $0C,$FC,$0F,$02,$18
  db $0C,$04,$10,$02,$18
  db $0C,$0C,$11,$02,$18
Metasprite073E::
  db $09
  db $FC,$FC,$12,$02,$18
  db $FC,$04,$13,$02,$18
  db $FC,$0C,$14,$02,$18
  db $04,$FC,$15,$02,$18
  db $04,$04,$16,$02,$18
  db $04,$0C,$17,$02,$18
  db $0C,$FC,$18,$02,$18
  db $0C,$04,$19,$02,$18
  db $0C,$0C,$1A,$02,$18
Metasprite073F::
  db $09
  db $FC,$FC,$1B,$02,$18
  db $FC,$04,$1C,$02,$18
  db $FC,$0C,$1D,$02,$18
  db $04,$FC,$1E,$02,$18
  db $04,$04,$1F,$02,$18
  db $04,$0C,$20,$02,$18
  db $0C,$FC,$21,$02,$18
  db $0C,$04,$22,$02,$18
  db $0C,$0C,$23,$02,$18
Metasprite0740::
  db $09
  db $F8,$00,$24,$01,$1F
  db $F8,$08,$25,$01,$1F
  db $F8,$10,$26,$01,$1F
  db $00,$00,$27,$01,$1F
  db $00,$08,$28,$01,$1F
  db $00,$10,$29,$01,$1F
  db $08,$00,$2A,$01,$1F
  db $08,$08,$2B,$01,$1F
  db $08,$10,$2C,$01,$1F
Metasprite0741::
  db $09
  db $F8,$F8,$26,$01,$3F
  db $F8,$00,$25,$01,$3F
  db $F8,$08,$24,$01,$3F
  db $00,$F8,$29,$01,$3F
  db $00,$00,$28,$01,$3F
  db $00,$08,$27,$01,$3F
  db $08,$F8,$2C,$01,$3F
  db $08,$00,$2B,$01,$3F
  db $08,$08,$2A,$01,$3F
Metasprite0742::
  db $0C
  db $F0,$F4,$00,$01,$1D
  db $F0,$FC,$01,$01,$1D
  db $F0,$04,$02,$01,$1D
  db $F8,$F4,$03,$01,$1D
  db $F8,$FC,$04,$01,$1D
  db $F8,$04,$05,$01,$1D
  db $00,$F4,$06,$01,$1D
  db $00,$FC,$07,$01,$1D
  db $00,$04,$08,$01,$1D
  db $08,$F4,$09,$01,$1D
  db $08,$FC,$0A,$01,$1D
  db $08,$04,$0B,$01,$1D
Metasprite0743::
  db $01
  db $FC,$FC,$0C,$01,$1A
Metasprite0744::
  db $01
  db $FC,$FC,$0D,$01,$1A
Metasprite0745::
  db $01
  db $FC,$FC,$0E,$01,$1A
Metasprite0746::
  db $01
  db $FC,$FC,$0F,$01,$1A
Metasprite0747::
  db $01
  db $FC,$FC,$10,$01,$1D
Metasprite0748::
  db $01
  db $FC,$FC,$11,$01,$1D
Metasprite0749::
  db $04
  db $F8,$F8,$12,$01,$1D
  db $F8,$00,$13,$01,$1D
  db $00,$F8,$14,$01,$1D
  db $00,$00,$15,$01,$1D
Metasprite074A::
  db $09
  db $F4,$F4,$16,$01,$1D
  db $F4,$FC,$17,$01,$1D
  db $F4,$04,$18,$01,$1D
  db $FC,$F4,$19,$01,$1D
  db $FC,$FC,$1A,$01,$1D
  db $FC,$04,$1B,$01,$1D
  db $04,$F4,$1C,$01,$1D
  db $04,$FC,$1D,$01,$1D
  db $04,$04,$1E,$01,$1D
Metasprite074B::
  db $0C
  db $F0,$F4,$00,$01,$1A
  db $F0,$FC,$01,$01,$1A
  db $F0,$04,$02,$01,$1A
  db $F8,$F4,$03,$01,$1A
  db $F8,$FC,$04,$01,$1A
  db $F8,$04,$05,$01,$1A
  db $00,$F4,$06,$01,$1A
  db $00,$FC,$07,$01,$18
  db $00,$04,$08,$01,$1A
  db $08,$F4,$09,$01,$1A
  db $08,$FC,$0A,$01,$1A
  db $08,$04,$0B,$01,$1A
Metasprite074D::
  db $01
  db $FC,$FC,$10,$01,$1A
Metasprite074E::
  db $01
  db $FC,$FC,$11,$01,$1A
Metasprite074F::
  db $04
  db $F8,$F8,$12,$01,$1A
  db $F8,$00,$13,$01,$1A
  db $00,$F8,$14,$01,$1A
  db $00,$00,$15,$01,$1A
Metasprite0750::
  db $09
  db $F4,$F4,$16,$01,$1A
  db $F4,$FC,$17,$01,$1A
  db $F4,$04,$18,$01,$1A
  db $FC,$F4,$19,$01,$1A
  db $FC,$FC,$1A,$01,$1A
  db $FC,$04,$1B,$01,$1A
  db $04,$F4,$1C,$01,$1A
  db $04,$FC,$1D,$01,$1A
  db $04,$04,$1E,$01,$1A
Metasprite0751::
  db $04
  db $F0,$F8,$00,$01,$1A
  db $F0,$00,$01,$01,$1A
  db $F8,$F8,$02,$01,$1A
  db $F8,$00,$03,$01,$1A
Metasprite0753::
  db $08
  db $F0,$F8,$00,$01,$1A
  db $F0,$00,$01,$01,$1A
  db $F8,$F8,$02,$01,$1A
  db $F8,$00,$03,$01,$1A
  db $00,$F8,$04,$01,$1A
  db $00,$00,$05,$01,$1A
  db $08,$F8,$06,$01,$1A
  db $08,$00,$07,$01,$1A
Metasprite0754::
  db $02
  db $F8,$FC,$08,$01,$1F
  db $00,$FC,$08,$01,$5F
Metasprite0755::
  db $04
  db $F0,$FC,$08,$01,$1F
  db $F8,$FC,$0C,$01,$1E
  db $00,$FC,$0D,$01,$1E
  db $08,$FC,$08,$01,$5F
Metasprite0756::
  db $04
  db $F0,$FC,$08,$01,$1F
  db $F8,$FC,$0C,$01,$3E
  db $00,$FC,$0D,$01,$3E
  db $08,$FC,$08,$01,$5F
Metasprite0757::
  db $06
  db $E8,$FC,$08,$01,$1F
  db $F0,$FC,$0B,$01,$1E
  db $F8,$FC,$0C,$01,$1E
  db $00,$FC,$0D,$01,$1E
  db $08,$FC,$0E,$01,$1E
  db $10,$FC,$08,$01,$5F
Metasprite0758::
  db $06
  db $E8,$FC,$08,$01,$1F
  db $F0,$FC,$0B,$01,$3E
  db $F8,$FC,$0C,$01,$3E
  db $00,$FC,$0D,$01,$3E
  db $08,$FC,$0E,$01,$3E
  db $10,$FC,$08,$01,$5F
Metasprite0759::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$0A,$01,$1E
  db $F0,$FC,$0B,$01,$1E
  db $F8,$FC,$0C,$01,$1E
  db $00,$FC,$0D,$01,$1E
  db $08,$FC,$0E,$01,$1E
  db $10,$FC,$0F,$01,$1E
  db $18,$FC,$08,$01,$5F
Metasprite075A::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$0A,$01,$3E
  db $F0,$FC,$0B,$01,$3E
  db $F8,$FC,$0C,$01,$3E
  db $00,$FC,$0D,$01,$3E
  db $08,$FC,$0E,$01,$3E
  db $10,$FC,$0F,$01,$3E
  db $18,$FC,$08,$01,$5F
Metasprite075B::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$0B,$01,$1E
  db $F0,$FC,$0C,$01,$1E
  db $F8,$FC,$0D,$01,$1E
  db $00,$FC,$0E,$01,$1E
  db $08,$FC,$0F,$01,$1E
  db $10,$FC,$10,$01,$1E
  db $18,$FC,$09,$01,$5F
Metasprite075C::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$0B,$01,$3E
  db $F0,$FC,$0C,$01,$3E
  db $F8,$FC,$0D,$01,$3E
  db $00,$FC,$0E,$01,$3E
  db $08,$FC,$0F,$01,$3E
  db $10,$FC,$10,$01,$3E
  db $18,$FC,$09,$01,$5F
Metasprite075D::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$0C,$01,$1E
  db $F0,$FC,$0D,$01,$1E
  db $F8,$FC,$0E,$01,$1E
  db $00,$FC,$0F,$01,$1E
  db $08,$FC,$10,$01,$1E
  db $10,$FC,$11,$01,$1E
  db $18,$FC,$08,$01,$5F
Metasprite075E::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$0C,$01,$3E
  db $F0,$FC,$0D,$01,$3E
  db $F8,$FC,$0E,$01,$3E
  db $00,$FC,$0F,$01,$3E
  db $08,$FC,$10,$01,$3E
  db $10,$FC,$11,$01,$3E
  db $18,$FC,$08,$01,$5F
Metasprite075F::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$0D,$01,$1E
  db $F0,$FC,$0E,$01,$1E
  db $F8,$FC,$0F,$01,$1E
  db $00,$FC,$10,$01,$1E
  db $08,$FC,$11,$01,$1E
  db $10,$FC,$12,$01,$1E
  db $18,$FC,$09,$01,$5F
Metasprite0760::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$0D,$01,$3E
  db $F0,$FC,$0E,$01,$3E
  db $F8,$FC,$0F,$01,$3E
  db $00,$FC,$10,$01,$3E
  db $08,$FC,$11,$01,$3E
  db $10,$FC,$12,$01,$3E
  db $18,$FC,$09,$01,$5F
Metasprite0761::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$0E,$01,$1E
  db $F0,$FC,$0F,$01,$1E
  db $F8,$FC,$10,$01,$1E
  db $00,$FC,$11,$01,$1E
  db $08,$FC,$12,$01,$1E
  db $10,$FC,$0A,$01,$1E
  db $18,$FC,$08,$01,$5F
Metasprite0762::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$0E,$01,$3E
  db $F0,$FC,$0F,$01,$3E
  db $F8,$FC,$10,$01,$3E
  db $00,$FC,$11,$01,$3E
  db $08,$FC,$12,$01,$3E
  db $10,$FC,$0A,$01,$3E
  db $18,$FC,$08,$01,$5F
Metasprite0763::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$0F,$01,$1E
  db $F0,$FC,$10,$01,$1E
  db $F8,$FC,$11,$01,$1E
  db $00,$FC,$12,$01,$1E
  db $08,$FC,$0A,$01,$1E
  db $10,$FC,$0B,$01,$1E
  db $18,$FC,$09,$01,$5F
Metasprite0764::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$0F,$01,$3E
  db $F0,$FC,$10,$01,$3E
  db $F8,$FC,$11,$01,$3E
  db $00,$FC,$12,$01,$3E
  db $08,$FC,$0A,$01,$3E
  db $10,$FC,$0B,$01,$3E
  db $18,$FC,$09,$01,$5F
Metasprite0765::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$10,$01,$1E
  db $F0,$FC,$11,$01,$1E
  db $F8,$FC,$12,$01,$1E
  db $00,$FC,$0A,$01,$1E
  db $08,$FC,$0B,$01,$1E
  db $10,$FC,$0C,$01,$1E
  db $18,$FC,$08,$01,$5F
Metasprite0766::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$10,$01,$3E
  db $F0,$FC,$11,$01,$3E
  db $F8,$FC,$12,$01,$3E
  db $00,$FC,$0A,$01,$3E
  db $08,$FC,$0B,$01,$3E
  db $10,$FC,$0C,$01,$3E
  db $18,$FC,$08,$01,$5F
Metasprite0767::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$11,$01,$1E
  db $F0,$FC,$12,$01,$1E
  db $F8,$FC,$0A,$01,$1E
  db $00,$FC,$0B,$01,$1E
  db $08,$FC,$0C,$01,$1E
  db $10,$FC,$0D,$01,$1E
  db $18,$FC,$09,$01,$5F
Metasprite0768::
  db $08
  db $E0,$FC,$09,$01,$1F
  db $E8,$FC,$11,$01,$3E
  db $F0,$FC,$12,$01,$3E
  db $F8,$FC,$0A,$01,$3E
  db $00,$FC,$0B,$01,$3E
  db $08,$FC,$0C,$01,$3E
  db $10,$FC,$0D,$01,$3E
  db $18,$FC,$09,$01,$5F
Metasprite0769::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$12,$01,$1E
  db $F0,$FC,$0A,$01,$1E
  db $F8,$FC,$0B,$01,$1E
  db $00,$FC,$0C,$01,$1E
  db $08,$FC,$0D,$01,$1E
  db $10,$FC,$0E,$01,$1E
  db $18,$FC,$08,$01,$5F
Metasprite076A::
  db $08
  db $E0,$FC,$08,$01,$1F
  db $E8,$FC,$12,$01,$3E
  db $F0,$FC,$0A,$01,$3E
  db $F8,$FC,$0B,$01,$3E
  db $00,$FC,$0C,$01,$3E
  db $08,$FC,$0D,$01,$3E
  db $10,$FC,$0E,$01,$3E
  db $18,$FC,$08,$01,$5F
Metasprite076B::
  db $09
  db $F4,$F4,$00,$01,$1F
  db $F4,$FC,$01,$01,$1F
  db $F4,$04,$02,$01,$1F
  db $FC,$F4,$03,$01,$1F
  db $FC,$FC,$04,$01,$1F
  db $FC,$04,$05,$01,$1F
  db $04,$F4,$06,$01,$1F
  db $04,$FC,$07,$01,$1F
  db $04,$04,$08,$01,$1F
Metasprite076D::
  db $09
  db $F4,$F4,$09,$01,$1F
  db $F4,$FC,$0A,$01,$1F
  db $F4,$04,$0B,$01,$1F
  db $FC,$F4,$0C,$01,$1F
  db $FC,$FC,$0D,$01,$1F
  db $FC,$04,$0E,$01,$1F
  db $04,$F4,$0F,$01,$1F
  db $04,$FC,$10,$01,$1F
  db $04,$04,$11,$01,$1F
Metasprite076E::
  db $09
  db $F4,$F4,$0B,$01,$3F
  db $F4,$FC,$0A,$01,$3F
  db $F4,$04,$09,$01,$3F
  db $FC,$F4,$0E,$01,$3F
  db $FC,$FC,$0D,$01,$3F
  db $FC,$04,$0C,$01,$3F
  db $04,$F4,$11,$01,$3F
  db $04,$FC,$10,$01,$3F
  db $04,$04,$0F,$01,$3F
Metasprite076F::
  db $04
  db $F8,$F8,$12,$01,$1C
  db $F8,$00,$13,$01,$1C
  db $00,$F8,$14,$01,$1C
  db $00,$00,$15,$01,$1C
Metasprite0770::
  db $04
  db $F8,$F8,$13,$01,$3C
  db $F8,$00,$12,$01,$3C
  db $00,$F8,$15,$01,$3C
  db $00,$00,$14,$01,$3C
Metasprite0771::
  db $04
  db $F8,$F8,$16,$01,$1C
  db $F8,$00,$17,$01,$1C
  db $00,$F8,$18,$01,$1C
  db $00,$00,$19,$01,$1C
Metasprite0772::
  db $04
  db $F8,$F8,$17,$01,$3C
  db $F8,$00,$16,$01,$3C
  db $00,$F8,$19,$01,$3C
  db $00,$00,$18,$01,$3C
Metasprite0773::
  db $04
  db $00,$00,$00,$01,$18
  db $00,$08,$01,$01,$18
  db $08,$00,$02,$01,$18
  db $08,$08,$03,$01,$18
Metasprite0781::
  db $04
  db $00,$00,$01,$01,$38
  db $00,$08,$00,$01,$38
  db $08,$00,$03,$01,$38
  db $08,$08,$02,$01,$38
Metasprite0782::
  db $04
  db $00,$00,$04,$01,$18
  db $00,$08,$05,$01,$18
  db $08,$00,$06,$01,$18
  db $08,$08,$07,$01,$18
Metasprite0783::
  db $04
  db $00,$00,$05,$01,$38
  db $00,$08,$04,$01,$38
  db $08,$00,$07,$01,$38
  db $08,$08,$06,$01,$38
Metasprite0784::
  db $04
  db $00,$00,$08,$01,$18
  db $00,$08,$09,$01,$18
  db $08,$00,$0A,$01,$18
  db $08,$08,$0B,$01,$18
Metasprite0785::
  db $04
  db $00,$00,$09,$01,$38
  db $00,$08,$08,$01,$38
  db $08,$00,$0B,$01,$38
  db $08,$08,$0A,$01,$38
Metasprite0786::
  db $04
  db $00,$00,$0C,$01,$18
  db $00,$08,$0D,$01,$18
  db $08,$00,$0E,$01,$18
  db $08,$08,$0F,$01,$18
Metasprite0787::
  db $04
  db $00,$00,$0D,$01,$38
  db $00,$08,$0C,$01,$38
  db $08,$00,$0F,$01,$38
  db $08,$08,$0E,$01,$38
Metasprite0788::
  db $04
  db $00,$00,$10,$01,$18
  db $00,$08,$11,$01,$18
  db $08,$00,$12,$01,$18
  db $08,$08,$13,$01,$18
Metasprite0789::
  db $04
  db $00,$00,$11,$01,$38
  db $00,$08,$10,$01,$38
  db $08,$00,$13,$01,$38
  db $08,$08,$12,$01,$38
Metasprite078A::
  db $04
  db $00,$00,$14,$01,$18
  db $00,$08,$15,$01,$18
  db $08,$00,$16,$01,$18
  db $08,$08,$17,$01,$18
Metasprite078B::
  db $04
  db $00,$00,$15,$01,$38
  db $00,$08,$14,$01,$38
  db $08,$00,$17,$01,$38
  db $08,$08,$16,$01,$38
Metasprite078C::
  db $04
  db $00,$00,$18,$01,$18
  db $00,$08,$19,$01,$18
  db $08,$00,$1A,$01,$18
  db $08,$08,$1B,$01,$18
Metasprite078D::
  db $04
  db $00,$00,$19,$01,$38
  db $00,$08,$18,$01,$38
  db $08,$00,$1B,$01,$38
  db $08,$08,$1A,$01,$38
Metasprite078E::
  db $04
  db $00,$00,$1C,$01,$18
  db $00,$08,$1D,$01,$18
  db $08,$00,$1E,$01,$18
  db $08,$08,$1F,$01,$18
Metasprite078F::
  db $04
  db $00,$00,$1D,$01,$38
  db $00,$08,$1C,$01,$38
  db $08,$00,$1F,$01,$38
  db $08,$08,$1E,$01,$38
Metasprite0790::
  db $04
  db $00,$00,$20,$01,$18
  db $00,$08,$21,$01,$18
  db $08,$00,$22,$01,$18
  db $08,$08,$23,$01,$18
Metasprite0791::
  db $04
  db $00,$00,$21,$01,$38
  db $00,$08,$20,$01,$38
  db $08,$00,$23,$01,$38
  db $08,$08,$22,$01,$38
Metasprite0792::
  db $04
  db $00,$00,$24,$01,$18
  db $00,$08,$25,$01,$18
  db $08,$00,$26,$01,$18
  db $08,$08,$27,$01,$18
Metasprite0793::
  db $04
  db $00,$00,$25,$01,$38
  db $00,$08,$24,$01,$38
  db $08,$00,$27,$01,$38
  db $08,$08,$26,$01,$38
Metasprite0794::
  db $04
  db $00,$00,$28,$01,$18
  db $00,$08,$29,$01,$18
  db $08,$00,$2A,$01,$18
  db $08,$08,$2B,$01,$18
Metasprite0795::
  db $04
  db $00,$00,$29,$01,$38
  db $00,$08,$28,$01,$38
  db $08,$00,$2B,$01,$38
  db $08,$08,$2A,$01,$38
Metasprite0796::
  db $04
  db $00,$00,$2C,$01,$18
  db $00,$08,$2D,$01,$18
  db $08,$00,$2E,$01,$18
  db $08,$08,$2F,$01,$18
Metasprite0797::
  db $04
  db $00,$00,$2D,$01,$38
  db $00,$08,$2C,$01,$38
  db $08,$00,$2F,$01,$38
  db $08,$08,$2E,$01,$38
Metasprite0798::
  db $04
  db $00,$00,$30,$01,$18
  db $00,$08,$31,$01,$18
  db $08,$00,$32,$01,$18
  db $08,$08,$33,$01,$18
Metasprite0799::
  db $04
  db $00,$00,$31,$01,$38
  db $00,$08,$30,$01,$38
  db $08,$00,$33,$01,$38
  db $08,$08,$32,$01,$38
Metasprite079A::
  db $04
  db $00,$00,$34,$01,$18
  db $00,$08,$35,$01,$18
  db $08,$00,$36,$01,$18
  db $08,$08,$37,$01,$18
Metasprite079B::
  db $04
  db $00,$00,$35,$01,$38
  db $00,$08,$34,$01,$38
  db $08,$00,$37,$01,$38
  db $08,$08,$36,$01,$38
Metasprite079C::
  db $04
  db $00,$00,$38,$01,$18
  db $00,$08,$39,$01,$18
  db $08,$00,$3A,$01,$18
  db $08,$08,$3B,$01,$18
Metasprite079D::
  db $04
  db $00,$00,$39,$01,$38
  db $00,$08,$38,$01,$38
  db $08,$00,$3B,$01,$38
  db $08,$08,$3A,$01,$38
Metasprite079E::
  db $04
  db $00,$00,$3C,$01,$18
  db $00,$08,$3D,$01,$18
  db $08,$00,$3E,$01,$18
  db $08,$08,$3F,$01,$18
Metasprite079F::
  db $04
  db $00,$00,$3D,$01,$38
  db $00,$08,$3C,$01,$38
  db $08,$00,$3F,$01,$38
  db $08,$08,$3E,$01,$38
Metasprite07A0::
  db $01
  db $FC,$FC,$00,$01,$1A
Metasprite07A1::
  db $01
  db $FC,$FC,$00,$01,$3A
Metasprite07A2::
  db $01
  db $FC,$FC,$00,$01,$7A
Metasprite07A3::
  db $01
  db $FC,$FC,$00,$01,$5A
Metasprite07A4::
  db $04
  db $F8,$F8,$01,$01,$1A
  db $F8,$00,$02,$01,$1A
  db $00,$F8,$03,$01,$1A
  db $00,$00,$04,$01,$1A
Metasprite07A5::
  db $04
  db $F8,$F8,$02,$01,$3A
  db $F8,$00,$01,$01,$3A
  db $00,$F8,$04,$01,$3A
  db $00,$00,$03,$01,$3A
Metasprite07A6::
  db $04
  db $F8,$F8,$04,$01,$7A
  db $F8,$00,$03,$01,$7A
  db $00,$F8,$02,$01,$7A
  db $00,$00,$01,$01,$7A
Metasprite07A7::
  db $04
  db $F8,$F8,$03,$01,$5A
  db $F8,$00,$04,$01,$5A
  db $00,$F8,$01,$01,$5A
  db $00,$00,$02,$01,$5A
Metasprite07A8::
  db $04
  db $F8,$F8,$05,$01,$1A
  db $F8,$00,$06,$01,$1A
  db $00,$F8,$07,$01,$1A
  db $00,$00,$08,$01,$1A
Metasprite07A9::
  db $04
  db $F8,$F8,$06,$01,$3A
  db $F8,$00,$05,$01,$3A
  db $00,$F8,$08,$01,$3A
  db $00,$00,$07,$01,$3A
Metasprite07AA::
  db $04
  db $F8,$F8,$08,$01,$7A
  db $F8,$00,$07,$01,$7A
  db $00,$F8,$06,$01,$7A
  db $00,$00,$05,$01,$7A
Metasprite07AB::
  db $04
  db $F8,$F8,$07,$01,$5A
  db $F8,$00,$08,$01,$5A
  db $00,$F8,$05,$01,$5A
  db $00,$00,$06,$01,$5A
Metasprite07AC::
  db $09
  db $F4,$F4,$09,$01,$1A
  db $F4,$FC,$0A,$01,$1A
  db $F4,$04,$0B,$01,$1A
  db $FC,$F4,$0C,$01,$1A
  db $FC,$FC,$0D,$01,$1A
  db $FC,$04,$0E,$01,$1A
  db $04,$F4,$0F,$01,$1A
  db $04,$FC,$10,$01,$1A
  db $04,$04,$11,$01,$1A
Metasprite07AD::
  db $09
  db $F4,$F4,$0B,$01,$3A
  db $F4,$FC,$0A,$01,$3A
  db $F4,$04,$09,$01,$3A
  db $FC,$F4,$0E,$01,$3A
  db $FC,$FC,$0D,$01,$3A
  db $FC,$04,$0C,$01,$3A
  db $04,$F4,$11,$01,$3A
  db $04,$FC,$10,$01,$3A
  db $04,$04,$0F,$01,$3A
Metasprite07AE::
  db $09
  db $F4,$F4,$11,$01,$7A
  db $F4,$FC,$10,$01,$7A
  db $F4,$04,$0F,$01,$7A
  db $FC,$F4,$0E,$01,$7A
  db $FC,$FC,$0D,$01,$7A
  db $FC,$04,$0C,$01,$7A
  db $04,$F4,$0B,$01,$7A
  db $04,$FC,$0A,$01,$7A
  db $04,$04,$09,$01,$7A
Metasprite07AF::
  db $09
  db $F4,$F4,$0F,$01,$5A
  db $F4,$FC,$10,$01,$5A
  db $F4,$04,$11,$01,$5A
  db $FC,$F4,$0C,$01,$5A
  db $FC,$FC,$0D,$01,$5A
  db $FC,$04,$0E,$01,$5A
  db $04,$F4,$09,$01,$5A
  db $04,$FC,$0A,$01,$5A
  db $04,$04,$0B,$01,$5A
Metasprite07B0::
  db $09
  db $F4,$F4,$12,$01,$1A
  db $F4,$FC,$13,$01,$1A
  db $F4,$04,$14,$01,$1A
  db $FC,$F4,$15,$01,$1A
  db $FC,$FC,$16,$01,$1A
  db $FC,$04,$17,$01,$1A
  db $04,$F4,$18,$01,$1A
  db $04,$FC,$19,$01,$1A
  db $04,$04,$1A,$01,$1A
Metasprite07B1::
  db $09
  db $F4,$F4,$14,$01,$3A
  db $F4,$FC,$13,$01,$3A
  db $F4,$04,$12,$01,$3A
  db $FC,$F4,$17,$01,$3A
  db $FC,$FC,$16,$01,$3A
  db $FC,$04,$15,$01,$3A
  db $04,$F4,$1A,$01,$3A
  db $04,$FC,$19,$01,$3A
  db $04,$04,$18,$01,$3A
Metasprite07B2::
  db $09
  db $F4,$F4,$1A,$01,$7A
  db $F4,$FC,$19,$01,$7A
  db $F4,$04,$18,$01,$7A
  db $FC,$F4,$17,$01,$7A
  db $FC,$FC,$16,$01,$7A
  db $FC,$04,$15,$01,$7A
  db $04,$F4,$14,$01,$7A
  db $04,$FC,$13,$01,$7A
  db $04,$04,$12,$01,$7A
Metasprite07B3::
  db $09
  db $F4,$F4,$18,$01,$5A
  db $F4,$FC,$19,$01,$5A
  db $F4,$04,$1A,$01,$5A
  db $FC,$F4,$15,$01,$5A
  db $FC,$FC,$16,$01,$5A
  db $FC,$04,$17,$01,$5A
  db $04,$F4,$12,$01,$5A
  db $04,$FC,$13,$01,$5A
  db $04,$04,$14,$01,$5A
Metasprite07B4::
  db $10
  db $F0,$F0,$1B,$01,$1A
  db $F0,$F8,$1C,$01,$1A
  db $F0,$00,$1D,$01,$1A
  db $F0,$08,$1E,$01,$1A
  db $F8,$F0,$1F,$01,$1A
  db $F8,$F8,$20,$01,$1A
  db $F8,$00,$21,$01,$1A
  db $F8,$08,$22,$01,$1A
  db $00,$F0,$23,$01,$1A
  db $00,$F8,$24,$01,$1A
  db $00,$00,$25,$01,$1A
  db $00,$08,$26,$01,$1A
  db $08,$F0,$27,$01,$1A
  db $08,$F8,$28,$01,$1A
  db $08,$00,$29,$01,$1A
  db $08,$08,$2A,$01,$1A
Metasprite07B5::
  db $10
  db $F0,$F0,$1E,$01,$3A
  db $F0,$F8,$1D,$01,$3A
  db $F0,$00,$1C,$01,$3A
  db $F0,$08,$1B,$01,$3A
  db $F8,$F0,$22,$01,$3A
  db $F8,$F8,$21,$01,$3A
  db $F8,$00,$20,$01,$3A
  db $F8,$08,$1F,$01,$3A
  db $00,$F0,$26,$01,$3A
  db $00,$F8,$25,$01,$3A
  db $00,$00,$24,$01,$3A
  db $00,$08,$23,$01,$3A
  db $08,$F0,$2A,$01,$3A
  db $08,$F8,$29,$01,$3A
  db $08,$00,$28,$01,$3A
  db $08,$08,$27,$01,$3A
Metasprite07B6::
  db $10
  db $F0,$F0,$2A,$01,$7A
  db $F0,$F8,$29,$01,$7A
  db $F0,$00,$28,$01,$7A
  db $F0,$08,$27,$01,$7A
  db $F8,$F0,$26,$01,$7A
  db $F8,$F8,$25,$01,$7A
  db $F8,$00,$24,$01,$7A
  db $F8,$08,$23,$01,$7A
  db $00,$F0,$22,$01,$7A
  db $00,$F8,$21,$01,$7A
  db $00,$00,$20,$01,$7A
  db $00,$08,$1F,$01,$7A
  db $08,$F0,$1E,$01,$7A
  db $08,$F8,$1D,$01,$7A
  db $08,$00,$1C,$01,$7A
  db $08,$08,$1B,$01,$7A
Metasprite07B7::
  db $10
  db $F0,$F0,$27,$01,$5A
  db $F0,$F8,$28,$01,$5A
  db $F0,$00,$29,$01,$5A
  db $F0,$08,$2A,$01,$5A
  db $F8,$F0,$23,$01,$5A
  db $F8,$F8,$24,$01,$5A
  db $F8,$00,$25,$01,$5A
  db $F8,$08,$26,$01,$5A
  db $00,$F0,$1F,$01,$5A
  db $00,$F8,$20,$01,$5A
  db $00,$00,$21,$01,$5A
  db $00,$08,$22,$01,$5A
  db $08,$F0,$1B,$01,$5A
  db $08,$F8,$1C,$01,$5A
  db $08,$00,$1D,$01,$5A
  db $08,$08,$1E,$01,$5A
Metasprite07B8::
  db $04
  db $F8,$F8,$2B,$01,$18
  db $F8,$00,$2C,$01,$18
  db $00,$F8,$2D,$01,$18
  db $00,$00,$2E,$01,$18
Metasprite07B9::
  db $04
  db $F8,$F8,$2F,$01,$18
  db $F8,$00,$30,$01,$18
  db $00,$F8,$31,$01,$18
  db $00,$00,$32,$01,$18
Metasprite07BA::
  db $09
  db $F4,$F4,$33,$01,$18
  db $F4,$FC,$34,$01,$18
  db $F4,$04,$35,$01,$18
  db $FC,$F4,$36,$01,$18
  db $FC,$FC,$37,$01,$18
  db $FC,$04,$38,$01,$18
  db $04,$F4,$39,$01,$18
  db $04,$FC,$3A,$01,$18
  db $04,$04,$3B,$01,$18
MetaspriteTable07End::
