; Autogenerated by ./scripts/dump_metasprites.py

SECTION "Metasprite Table 02", ROMX[$68E8], BANK[$2F]
MetaspriteTable02::
  dw Metasprite0200
  dw Metasprite0201
  dw Metasprite0202
  dw Metasprite0203
  dw Metasprite0204
  dw Metasprite0205
  dw Metasprite0206
  dw Metasprite0207
  dw Metasprite0208
  dw Metasprite0209
  dw Metasprite020A
  dw Metasprite020B
  dw Metasprite020C
  dw Metasprite020D
  dw Metasprite020E
  dw Metasprite020F
  dw Metasprite0210
  dw Metasprite0211
  dw Metasprite0212
  dw Metasprite0213
  dw Metasprite0214
  dw Metasprite0215
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0216
  dw Metasprite0221
  dw Metasprite0222
  dw Metasprite0223
  dw Metasprite0223
  dw Metasprite0223
  dw Metasprite0223
  dw Metasprite0223
  dw Metasprite0223
  dw Metasprite0229
  dw Metasprite022A
  dw Metasprite022A
  dw Metasprite022A
  dw Metasprite022A
  dw Metasprite022A
  dw Metasprite022A
  dw Metasprite022A
  dw Metasprite0231
  dw Metasprite0232
  dw Metasprite0233
  dw Metasprite0234
  dw Metasprite0235
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0236
  dw Metasprite0281
  dw Metasprite0282
  dw Metasprite0283
  dw Metasprite0284
  dw Metasprite0285
  dw Metasprite0286
  dw Metasprite0287
  dw Metasprite0288
  dw Metasprite0289
  dw Metasprite028A
  dw Metasprite028B
  dw Metasprite028C
  dw Metasprite028D
  dw Metasprite028E
  dw Metasprite028F
  dw Metasprite0290
  dw Metasprite0291
  dw Metasprite0292
  dw Metasprite0293
  dw Metasprite0294
  dw Metasprite0295
  dw Metasprite0296
  dw Metasprite0297
  dw Metasprite0298
  dw Metasprite0299
  dw Metasprite029A
  dw Metasprite029B
  dw Metasprite029C
  dw Metasprite029D
  dw Metasprite029E
  dw Metasprite029F
  dw Metasprite02A0
  dw Metasprite02A1
  dw Metasprite02A2
  dw Metasprite02A3
  dw Metasprite02A4
  dw Metasprite02A5
  dw Metasprite02A6
  dw Metasprite02A7
  dw Metasprite02A8
  dw Metasprite02A9
  dw Metasprite02AA
  dw Metasprite02AB
  dw Metasprite02AC
  dw Metasprite02AD
  dw Metasprite02AE
  dw Metasprite02AF
  dw Metasprite02B0
  dw Metasprite02B1
  dw Metasprite02B2
  dw Metasprite02B3
  dw Metasprite02B4
  dw Metasprite02B5
  dw Metasprite02B6
  dw Metasprite02B7
  dw Metasprite02B8
  dw Metasprite02B9
  dw Metasprite02BA
  dw Metasprite02BB
  dw Metasprite02BC
  dw Metasprite02BD
  dw Metasprite02BE
  dw Metasprite02BF
  dw Metasprite02C0
  dw Metasprite02C1
  dw Metasprite02C2
  dw Metasprite02C3
  dw Metasprite02C4
  dw Metasprite02C5
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
  dw MetaspriteTable02End
Metasprite0200::
  db $04
  db $F2,$F8,$00,$01,$10
  db $F2,$00,$01,$01,$10
  db $FA,$F8,$02,$01,$10
  db $FA,$00,$03,$01,$10
Metasprite0201::
  db $04
  db $F2,$F8,$04,$01,$10
  db $F2,$00,$05,$01,$10
  db $FA,$F8,$06,$01,$10
  db $FA,$00,$07,$01,$10
Metasprite0202::
  db $04
  db $F2,$F8,$09,$01,$30
  db $F2,$00,$08,$01,$30
  db $FA,$F8,$0B,$01,$30
  db $FA,$00,$0A,$01,$30
Metasprite0203::
  db $04
  db $F2,$F8,$08,$01,$10
  db $F2,$00,$09,$01,$10
  db $FA,$F8,$0A,$01,$10
  db $FA,$00,$0B,$01,$10
Metasprite0204::
  db $04
  db $F2,$F8,$0C,$01,$10
  db $F2,$00,$0D,$01,$10
  db $FA,$F8,$0E,$01,$10
  db $FA,$00,$0F,$01,$10
Metasprite0205::
  db $04
  db $F2,$F8,$0D,$01,$30
  db $F2,$00,$0C,$01,$30
  db $FA,$F8,$0F,$01,$30
  db $FA,$00,$0E,$01,$30
Metasprite0206::
  db $04
  db $F2,$F8,$10,$01,$10
  db $F2,$00,$11,$01,$10
  db $FA,$F8,$12,$01,$10
  db $FA,$00,$13,$01,$10
Metasprite0207::
  db $04
  db $F2,$F8,$11,$01,$30
  db $F2,$00,$10,$01,$30
  db $FA,$F8,$13,$01,$30
  db $FA,$00,$12,$01,$30
Metasprite0208::
  db $04
  db $F2,$F8,$15,$01,$30
  db $F2,$00,$14,$01,$30
  db $FA,$F8,$17,$01,$30
  db $FA,$00,$16,$01,$30
Metasprite0209::
  db $04
  db $F2,$F8,$14,$01,$10
  db $F2,$00,$15,$01,$10
  db $FA,$F8,$16,$01,$10
  db $FA,$00,$17,$01,$10
Metasprite020A::
  db $04
  db $F2,$F8,$18,$01,$10
  db $F2,$00,$19,$01,$10
  db $FA,$F8,$1A,$01,$10
  db $FA,$00,$1B,$01,$10
Metasprite020B::
  db $04
  db $F2,$F8,$1C,$01,$10
  db $F2,$00,$1D,$01,$10
  db $FA,$F8,$1E,$01,$10
  db $FA,$00,$1F,$01,$10
Metasprite020C::
  db $04
  db $F2,$F8,$20,$01,$10
  db $F2,$00,$21,$01,$10
  db $FA,$F8,$22,$01,$10
  db $FA,$00,$23,$01,$10
Metasprite020D::
  db $04
  db $F2,$F8,$24,$01,$10
  db $F2,$00,$25,$01,$10
  db $FA,$F8,$26,$01,$10
  db $FA,$00,$27,$01,$10
Metasprite020E::
  db $04
  db $F2,$F8,$28,$01,$10
  db $F2,$00,$29,$01,$10
  db $FA,$F8,$2A,$01,$10
  db $FA,$00,$2B,$01,$10
Metasprite020F::
  db $04
  db $F2,$F8,$2C,$01,$10
  db $F2,$00,$2D,$01,$10
  db $FA,$F8,$2E,$01,$10
  db $FA,$00,$2F,$01,$10
Metasprite0210::
  db $04
  db $F2,$F8,$31,$01,$31
  db $F2,$00,$30,$01,$31
  db $FA,$F8,$33,$01,$31
  db $FA,$00,$32,$01,$31
Metasprite0211::
  db $04
  db $F2,$F8,$30,$01,$11
  db $F2,$00,$31,$01,$11
  db $FA,$F8,$32,$01,$11
  db $FA,$00,$33,$01,$11
Metasprite0212::
  db $04
  db $F2,$F8,$35,$01,$31
  db $F2,$00,$34,$01,$31
  db $FA,$F8,$37,$01,$31
  db $FA,$00,$36,$01,$31
Metasprite0213::
  db $04
  db $F2,$F8,$34,$01,$11
  db $F2,$00,$35,$01,$11
  db $FA,$F8,$36,$01,$11
  db $FA,$00,$37,$01,$11
Metasprite0214::
  db $04
  db $F2,$F8,$38,$01,$11
  db $F2,$00,$39,$01,$11
  db $FA,$F8,$3A,$01,$11
  db $FA,$00,$3B,$01,$11
Metasprite0215::
  db $04
  db $F2,$F8,$3C,$01,$11
  db $F2,$00,$3D,$01,$11
  db $FA,$F8,$3E,$01,$11
  db $FA,$00,$3F,$01,$11
Metasprite0216::
  db $04
  db $F2,$F8,$40,$01,$12
  db $F2,$00,$41,$01,$12
  db $FA,$F8,$42,$01,$12
  db $FA,$00,$43,$01,$12
Metasprite0221::
  db $04
  db $F2,$F8,$44,$01,$12
  db $F2,$00,$45,$01,$12
  db $FA,$F8,$46,$01,$12
  db $FA,$00,$47,$01,$12
Metasprite0222::
  db $04
  db $F2,$F8,$48,$01,$12
  db $F2,$00,$49,$01,$12
  db $FA,$F8,$4A,$01,$12
  db $FA,$00,$4B,$01,$12
Metasprite0223::
  db $04
  db $F2,$F8,$4C,$01,$13
  db $F2,$00,$4D,$01,$13
  db $FA,$F8,$4E,$01,$13
  db $FA,$00,$4F,$01,$13
Metasprite0229::
  db $04
  db $F2,$F8,$50,$01,$13
  db $F2,$00,$51,$01,$13
  db $FA,$F8,$52,$01,$13
  db $FA,$00,$53,$01,$13
Metasprite022A::
  db $04
  db $F2,$F8,$54,$01,$10
  db $F2,$00,$55,$01,$10
  db $FA,$F8,$56,$01,$10
  db $FA,$00,$57,$01,$10
Metasprite0231::
  db $04
  db $F2,$F8,$58,$01,$10
  db $F2,$00,$59,$01,$10
  db $FA,$F8,$5A,$01,$10
  db $FA,$00,$5B,$01,$10
Metasprite0232::
  db $04
  db $F2,$F8,$5C,$01,$10
  db $F2,$00,$5D,$01,$10
  db $FA,$F8,$5E,$01,$10
  db $FA,$00,$5F,$01,$10
Metasprite0233::
  db $04
  db $F2,$F8,$60,$01,$10
  db $F2,$00,$61,$01,$10
  db $FA,$F8,$62,$01,$10
  db $FA,$00,$63,$01,$10
Metasprite0234::
  db $04
  db $F2,$F8,$64,$01,$10
  db $F2,$00,$65,$01,$10
  db $FA,$F8,$66,$01,$10
  db $FA,$00,$67,$01,$10
Metasprite0235::
  db $04
  db $F2,$F8,$68,$01,$10
  db $F2,$00,$69,$01,$10
  db $FA,$F8,$6A,$01,$10
  db $FA,$00,$6B,$01,$10
Metasprite0236::
  db $0E
  db $00,$00,$40,$01,$14
  db $00,$08,$41,$01,$14
  db $00,$10,$42,$01,$14
  db $00,$18,$43,$01,$14
  db $00,$20,$44,$01,$14
  db $00,$28,$45,$01,$14
  db $00,$30,$46,$01,$14
  db $08,$00,$47,$01,$14
  db $08,$08,$48,$01,$14
  db $08,$10,$49,$01,$14
  db $08,$18,$4A,$01,$14
  db $08,$20,$4B,$01,$14
  db $08,$28,$4C,$01,$14
  db $08,$30,$4D,$01,$14
Metasprite0281::
  db $0E
  db $00,$00,$4E,$01,$14
  db $00,$08,$4F,$01,$14
  db $00,$10,$50,$01,$14
  db $00,$18,$51,$01,$14
  db $00,$20,$52,$01,$14
  db $00,$28,$53,$01,$14
  db $00,$30,$54,$01,$14
  db $08,$00,$55,$01,$14
  db $08,$08,$56,$01,$14
  db $08,$10,$57,$01,$14
  db $08,$18,$58,$01,$14
  db $08,$20,$59,$01,$14
  db $08,$28,$5A,$01,$14
  db $08,$30,$5B,$01,$14
Metasprite0282::
  db $04
  db $00,$00,$64,$01,$12
  db $00,$08,$65,$01,$12
  db $08,$00,$66,$01,$12
  db $08,$08,$67,$01,$12
Metasprite0283::
  db $04
  db $00,$00,$60,$01,$13
  db $00,$08,$61,$01,$13
  db $08,$00,$62,$01,$13
  db $08,$08,$63,$01,$13
Metasprite0284::
  db $04
  db $01,$00,$64,$01,$12
  db $01,$08,$65,$01,$12
  db $09,$00,$66,$01,$12
  db $09,$08,$67,$01,$12
Metasprite0285::
  db $04
  db $01,$00,$60,$01,$13
  db $01,$08,$61,$01,$13
  db $09,$00,$62,$01,$13
  db $09,$08,$63,$01,$13
Metasprite0286::
  db $02
  db $00,$00,$FA,$01,$3F
  db $00,$30,$FA,$01,$1F
Metasprite0287::
  db $02
  db $E8,$00,$FA,$01,$3F
  db $E8,$30,$FA,$01,$1F
Metasprite0288::
  db $04
  db $00,$00,$00,$01,$1D
  db $00,$08,$01,$01,$1D
  db $08,$00,$02,$01,$1D
  db $08,$08,$03,$01,$1D
Metasprite0289::
  db $04
  db $00,$00,$04,$01,$19
  db $00,$08,$05,$01,$19
  db $08,$00,$06,$01,$19
  db $08,$08,$07,$01,$19
Metasprite028A::
  db $04
  db $00,$00,$08,$01,$19
  db $00,$08,$09,$01,$19
  db $08,$00,$0A,$01,$19
  db $08,$08,$0B,$01,$19
Metasprite028B::
  db $04
  db $00,$00,$0C,$01,$19
  db $00,$08,$0D,$01,$19
  db $08,$00,$0E,$01,$19
  db $08,$08,$0F,$01,$19
Metasprite028C::
  db $04
  db $00,$00,$10,$01,$19
  db $00,$08,$11,$01,$19
  db $08,$00,$12,$01,$19
  db $08,$08,$13,$01,$19
Metasprite028D::
  db $04
  db $00,$00,$14,$01,$19
  db $00,$08,$15,$01,$19
  db $08,$00,$16,$01,$19
  db $08,$08,$17,$01,$19
Metasprite028E::
  db $04
  db $00,$00,$18,$01,$19
  db $00,$08,$19,$01,$19
  db $08,$00,$1A,$01,$19
  db $08,$08,$1B,$01,$19
Metasprite028F::
  db $04
  db $00,$00,$1C,$01,$19
  db $00,$08,$1D,$01,$19
  db $08,$00,$1E,$01,$19
  db $08,$08,$1F,$01,$19
Metasprite0290::
  db $04
  db $00,$00,$20,$01,$19
  db $00,$08,$21,$01,$19
  db $08,$00,$22,$01,$19
  db $08,$08,$23,$01,$19
Metasprite0291::
  db $04
  db $00,$00,$24,$01,$19
  db $00,$08,$25,$01,$19
  db $08,$00,$26,$01,$19
  db $08,$08,$27,$01,$19
Metasprite0292::
  db $04
  db $00,$00,$28,$01,$19
  db $00,$08,$29,$01,$19
  db $08,$00,$2A,$01,$19
  db $08,$08,$2B,$01,$19
Metasprite0293::
  db $04
  db $00,$00,$2C,$01,$19
  db $00,$08,$2D,$01,$19
  db $08,$00,$2E,$01,$19
  db $08,$08,$2F,$01,$19
Metasprite0294::
  db $04
  db $00,$00,$30,$01,$19
  db $00,$08,$31,$01,$19
  db $08,$00,$32,$01,$19
  db $08,$08,$33,$01,$19
Metasprite0295::
  db $04
  db $00,$00,$34,$01,$19
  db $00,$08,$35,$01,$19
  db $08,$00,$36,$01,$19
  db $08,$08,$37,$01,$19
Metasprite0296::
  db $04
  db $00,$00,$38,$01,$19
  db $00,$08,$39,$01,$19
  db $08,$00,$3A,$01,$19
  db $08,$08,$3B,$01,$19
Metasprite0297::
  db $04
  db $00,$00,$3C,$01,$19
  db $00,$08,$3D,$01,$19
  db $08,$00,$3E,$01,$19
  db $08,$08,$3F,$01,$19
Metasprite0298::
  db $04
  db $00,$00,$2D,$01,$22
  db $00,$08,$2C,$01,$22
  db $08,$00,$2F,$01,$22
  db $08,$08,$2E,$01,$22
Metasprite0299::
  db $04
  db $00,$02,$2D,$01,$22
  db $00,$0A,$2C,$01,$22
  db $08,$02,$2F,$01,$22
  db $08,$0A,$2E,$01,$22
Metasprite029A::
  db $04
  db $00,$04,$2D,$01,$22
  db $00,$0C,$2C,$01,$22
  db $08,$04,$2F,$01,$22
  db $08,$0C,$2E,$01,$22
Metasprite029B::
  db $04
  db $00,$00,$2C,$01,$02
  db $00,$08,$2D,$01,$02
  db $08,$00,$2E,$01,$02
  db $08,$08,$2F,$01,$02
Metasprite029C::
  db $04
  db $00,$02,$2C,$01,$02
  db $00,$0A,$2D,$01,$02
  db $08,$02,$2E,$01,$02
  db $08,$0A,$2F,$01,$02
Metasprite029D::
  db $04
  db $00,$04,$2C,$01,$02
  db $00,$0C,$2D,$01,$02
  db $08,$04,$2E,$01,$02
  db $08,$0C,$2F,$01,$02
Metasprite029E::
  db $04
  db $00,$06,$2C,$01,$02
  db $00,$0E,$2D,$01,$02
  db $08,$06,$2E,$01,$02
  db $08,$0E,$2F,$01,$02
Metasprite029F::
  db $04
  db $00,$08,$2C,$01,$02
  db $00,$10,$2D,$01,$02
  db $08,$08,$2E,$01,$02
  db $08,$10,$2F,$01,$02
Metasprite02A0::
  db $04
  db $00,$00,$30,$01,$11
  db $00,$08,$31,$01,$11
  db $08,$00,$32,$01,$11
  db $08,$08,$33,$01,$11
Metasprite02A1::
  db $04
  db $FD,$FD,$30,$01,$11
  db $FD,$05,$31,$01,$11
  db $05,$FD,$32,$01,$11
  db $05,$05,$33,$01,$11
Metasprite02A2::
  db $04
  db $00,$00,$40,$01,$15
  db $00,$08,$40,$01,$15
  db $08,$00,$40,$01,$15
  db $08,$08,$40,$01,$15
Metasprite02A3::
  db $0E
  db $00,$00,$40,$01,$14
  db $00,$08,$41,$01,$14
  db $00,$10,$42,$01,$14
  db $00,$18,$43,$01,$14
  db $00,$20,$44,$01,$14
  db $00,$28,$45,$01,$14
  db $00,$30,$46,$01,$14
  db $08,$00,$47,$01,$14
  db $08,$08,$48,$01,$14
  db $08,$10,$49,$01,$14
  db $08,$18,$4A,$01,$14
  db $08,$20,$4B,$01,$14
  db $08,$28,$4C,$01,$14
  db $08,$30,$4D,$01,$14
Metasprite02A4::
  db $0E
  db $00,$00,$4E,$01,$14
  db $00,$08,$4F,$01,$14
  db $00,$10,$50,$01,$14
  db $00,$18,$51,$01,$14
  db $00,$20,$52,$01,$14
  db $00,$28,$53,$01,$14
  db $00,$30,$54,$01,$14
  db $08,$00,$55,$01,$14
  db $08,$08,$56,$01,$14
  db $08,$10,$57,$01,$14
  db $08,$18,$58,$01,$14
  db $08,$20,$59,$01,$14
  db $08,$28,$5A,$01,$14
  db $08,$30,$5B,$01,$14
Metasprite02A5::
  db $02
  db $00,$00,$FA,$01,$3F
  db $00,$40,$FA,$01,$1F
Metasprite02A6::
  db $02
  db $00,$00,$FC,$01,$3F
  db $00,$40,$FC,$01,$1F
Metasprite02A7::
  db $23
  db $00,$08,$00,$01,$01
  db $00,$10,$01,$01,$01
  db $00,$18,$02,$01,$01
  db $00,$20,$03,$01,$00
  db $00,$30,$04,$01,$05
  db $00,$38,$05,$01,$05
  db $08,$08,$06,$01,$01
  db $08,$10,$07,$01,$00
  db $08,$18,$08,$01,$00
  db $08,$20,$09,$01,$00
  db $08,$30,$0A,$01,$05
  db $08,$38,$0B,$01,$05
  db $10,$08,$0C,$01,$00
  db $10,$10,$0D,$01,$05
  db $10,$18,$0E,$01,$05
  db $10,$20,$0F,$01,$00
  db $10,$28,$10,$01,$05
  db $10,$30,$11,$01,$05
  db $18,$08,$12,$01,$00
  db $18,$10,$13,$01,$00
  db $18,$18,$14,$01,$00
  db $18,$20,$15,$01,$04
  db $18,$28,$16,$01,$04
  db $20,$00,$17,$01,$05
  db $20,$08,$18,$01,$04
  db $20,$10,$19,$01,$03
  db $20,$18,$1A,$01,$03
  db $20,$20,$1B,$01,$02
  db $20,$28,$1C,$01,$02
  db $28,$00,$1D,$01,$05
  db $28,$08,$1E,$01,$04
  db $28,$10,$1F,$01,$02
  db $28,$18,$21,$01,$02
  db $28,$20,$22,$01,$02
  db $28,$28,$23,$01,$02
Metasprite02A8::
  db $25
  db $00,$10,$30,$01,$00
  db $00,$18,$31,$01,$00
  db $00,$20,$32,$01,$00
  db $00,$28,$33,$01,$00
  db $08,$00,$34,$01,$00
  db $08,$08,$35,$01,$00
  db $08,$10,$36,$01,$00
  db $08,$18,$37,$01,$00
  db $08,$20,$38,$01,$00
  db $08,$28,$39,$01,$00
  db $08,$30,$3A,$01,$00
  db $10,$F8,$3B,$01,$00
  db $10,$00,$3C,$01,$00
  db $10,$08,$3D,$01,$00
  db $10,$10,$3E,$01,$00
  db $10,$18,$3F,$01,$00
  db $10,$20,$40,$01,$00
  db $10,$28,$41,$01,$00
  db $10,$30,$42,$01,$00
  db $18,$F8,$43,$01,$00
  db $18,$00,$44,$01,$01
  db $18,$08,$45,$01,$01
  db $18,$10,$46,$01,$00
  db $18,$18,$47,$01,$00
  db $18,$20,$48,$01,$02
  db $18,$28,$49,$01,$00
  db $20,$00,$4A,$01,$01
  db $20,$08,$4B,$01,$01
  db $20,$18,$4C,$01,$00
  db $20,$20,$4D,$01,$01
  db $20,$28,$4E,$01,$01
  db $28,$00,$4F,$01,$01
  db $28,$08,$50,$01,$01
  db $28,$10,$51,$01,$01
  db $28,$18,$52,$01,$01
  db $28,$20,$53,$01,$01
  db $28,$28,$54,$01,$01
Metasprite02A9::
  db $23
  db $00,$F8,$05,$01,$25
  db $00,$00,$04,$01,$25
  db $00,$10,$03,$01,$20
  db $00,$18,$02,$01,$21
  db $00,$20,$01,$01,$21
  db $00,$28,$00,$01,$21
  db $08,$F8,$0B,$01,$25
  db $08,$00,$0A,$01,$25
  db $08,$10,$09,$01,$20
  db $08,$18,$08,$01,$20
  db $08,$20,$07,$01,$20
  db $08,$28,$06,$01,$21
  db $10,$00,$11,$01,$25
  db $10,$08,$10,$01,$25
  db $10,$10,$0F,$01,$20
  db $10,$18,$0E,$01,$25
  db $10,$20,$0D,$01,$25
  db $10,$28,$0C,$01,$20
  db $18,$08,$16,$01,$24
  db $18,$10,$15,$01,$24
  db $18,$18,$14,$01,$20
  db $18,$20,$13,$01,$20
  db $18,$28,$12,$01,$20
  db $20,$08,$1C,$01,$22
  db $20,$10,$1B,$01,$22
  db $20,$18,$1A,$01,$23
  db $20,$20,$19,$01,$23
  db $20,$28,$18,$01,$24
  db $20,$30,$17,$01,$25
  db $28,$08,$23,$01,$22
  db $28,$10,$22,$01,$22
  db $28,$18,$21,$01,$22
  db $28,$20,$1F,$01,$22
  db $28,$28,$1E,$01,$24
  db $28,$30,$1D,$01,$25
Metasprite02AA::
  db $04
  db $00,$00,$00,$01,$00
  db $00,$08,$01,$01,$00
  db $08,$00,$02,$01,$00
  db $08,$08,$03,$01,$00
Metasprite02AB::
  db $04
  db $00,$00,$04,$01,$00
  db $00,$08,$05,$01,$00
  db $08,$00,$06,$01,$00
  db $08,$08,$07,$01,$00
Metasprite02AC::
  db $04
  db $00,$00,$08,$01,$00
  db $00,$08,$09,$01,$00
  db $08,$00,$0A,$01,$00
  db $08,$08,$0B,$01,$00
Metasprite02AD::
  db $04
  db $00,$00,$0C,$01,$00
  db $00,$08,$0D,$01,$00
  db $08,$00,$0E,$01,$00
  db $08,$08,$0F,$01,$00
Metasprite02AE::
  db $04
  db $00,$00,$10,$01,$00
  db $00,$08,$11,$01,$00
  db $08,$00,$12,$01,$00
  db $08,$08,$13,$01,$00
Metasprite02AF::
  db $04
  db $00,$00,$00,$01,$00
  db $00,$08,$01,$01,$00
  db $08,$00,$02,$01,$00
  db $08,$08,$03,$01,$00
Metasprite02B0::
  db $04
  db $00,$00,$04,$01,$00
  db $00,$08,$05,$01,$00
  db $08,$00,$06,$01,$00
  db $08,$08,$07,$01,$00
Metasprite02B1::
  db $04
  db $00,$F8,$08,$01,$00
  db $00,$00,$09,$01,$00
  db $08,$F8,$0A,$01,$00
  db $08,$00,$0B,$01,$00
Metasprite02B2::
  db $08
  db $00,$F0,$0C,$01,$00
  db $00,$F8,$0D,$01,$00
  db $00,$00,$0E,$01,$00
  db $00,$08,$0F,$01,$00
  db $08,$F0,$10,$01,$00
  db $08,$F8,$11,$01,$00
  db $08,$00,$12,$01,$00
  db $08,$08,$13,$01,$00
Metasprite02B3::
  db $08
  db $00,$F0,$14,$01,$00
  db $00,$F8,$15,$01,$00
  db $00,$00,$16,$01,$00
  db $00,$08,$17,$01,$00
  db $08,$F0,$18,$01,$00
  db $08,$F8,$19,$01,$00
  db $08,$00,$1A,$01,$00
  db $08,$08,$1B,$01,$00
Metasprite02B4::
  db $14
  db $00,$00,$1C,$01,$05
  db $00,$08,$1D,$01,$05
  db $00,$10,$1E,$01,$05
  db $00,$18,$1F,$01,$05
  db $08,$00,$20,$01,$05
  db $08,$08,$21,$01,$02
  db $08,$10,$22,$01,$02
  db $08,$18,$23,$01,$05
  db $10,$00,$24,$01,$05
  db $10,$08,$25,$01,$03
  db $10,$10,$26,$01,$03
  db $10,$18,$27,$01,$05
  db $18,$00,$28,$01,$05
  db $18,$08,$29,$01,$03
  db $18,$10,$2A,$01,$03
  db $18,$18,$2B,$01,$05
  db $20,$00,$2C,$01,$05
  db $20,$08,$2D,$01,$04
  db $20,$10,$2E,$01,$04
  db $20,$18,$2F,$01,$05
Metasprite02B5::
  db $14
  db $00,$00,$30,$01,$05
  db $00,$08,$31,$01,$05
  db $00,$10,$32,$01,$05
  db $00,$18,$33,$01,$05
  db $08,$00,$34,$01,$05
  db $08,$08,$35,$01,$02
  db $08,$10,$36,$01,$02
  db $08,$18,$37,$01,$05
  db $10,$00,$38,$01,$05
  db $10,$08,$39,$01,$03
  db $10,$10,$3A,$01,$03
  db $10,$18,$3B,$01,$05
  db $18,$00,$3C,$01,$05
  db $18,$08,$3D,$01,$03
  db $18,$10,$3E,$01,$03
  db $18,$18,$3F,$01,$05
  db $20,$00,$40,$01,$05
  db $20,$08,$41,$01,$04
  db $20,$10,$42,$01,$04
  db $20,$18,$43,$01,$05
Metasprite02B6::
  db $08
  db $00,$00,$50,$01,$06
  db $00,$04,$50,$01,$06
  db $04,$00,$50,$01,$06
  db $04,$04,$50,$01,$06
  db $00,$08,$50,$01,$06
  db $00,$0C,$50,$01,$06
  db $04,$08,$50,$01,$06
  db $04,$0C,$50,$01,$06
Metasprite02B7::
  db $04
  db $00,$00,$00,$01,$00
  db $00,$08,$01,$01,$00
  db $08,$00,$02,$01,$00
  db $08,$08,$03,$01,$00
Metasprite02B8::
  db $04
  db $00,$00,$0C,$01,$00
  db $00,$08,$0D,$01,$00
  db $08,$00,$0E,$01,$00
  db $08,$08,$0F,$01,$00
Metasprite02B9::
  db $04
  db $00,$00,$04,$01,$00
  db $00,$08,$05,$01,$00
  db $08,$00,$06,$01,$00
  db $08,$08,$07,$01,$00
Metasprite02BA::
  db $04
  db $00,$00,$10,$01,$00
  db $00,$08,$11,$01,$00
  db $08,$00,$12,$01,$00
  db $08,$08,$13,$01,$00
Metasprite02BB::
  db $04
  db $00,$00,$08,$01,$00
  db $00,$08,$09,$01,$00
  db $08,$00,$0A,$01,$00
  db $08,$08,$0B,$01,$00
Metasprite02BC::
  db $04
  db $00,$00,$14,$01,$00
  db $00,$08,$15,$01,$00
  db $08,$00,$16,$01,$00
  db $08,$08,$17,$01,$00
Metasprite02BD::
  db $0C
  db $00,$00,$18,$01,$04
  db $00,$08,$19,$01,$04
  db $00,$10,$1A,$01,$04
  db $08,$00,$1B,$01,$04
  db $08,$08,$1C,$01,$04
  db $08,$10,$1D,$01,$04
  db $10,$00,$1E,$01,$04
  db $10,$08,$1F,$01,$04
  db $10,$10,$20,$01,$04
  db $18,$00,$21,$01,$04
  db $18,$08,$22,$01,$04
  db $18,$10,$23,$01,$04
Metasprite02BE::
  db $0C
  db $00,$00,$24,$01,$04
  db $00,$08,$25,$01,$04
  db $00,$10,$26,$01,$04
  db $08,$00,$27,$01,$04
  db $08,$08,$28,$01,$04
  db $08,$10,$29,$01,$04
  db $10,$00,$2A,$01,$04
  db $10,$08,$2B,$01,$04
  db $10,$10,$2C,$01,$04
  db $18,$00,$2D,$01,$04
  db $18,$08,$2E,$01,$04
  db $18,$10,$2F,$01,$04
Metasprite02BF::
  db $05
  db $00,$00,$A2,$01,$18
  db $00,$08,$AF,$01,$18
  db $00,$10,$AF,$01,$18
  db $00,$18,$AC,$01,$18
  db $00,$20,$AF,$01,$18
Metasprite02C0::
  db $01
  db $00,$00,$BA,$01,$08
Metasprite02C1::
  db $0D
  db $00,$00,$A6,$01,$18
  db $00,$08,$AB,$01,$18
  db $00,$10,$AD,$01,$18
  db $00,$18,$B2,$01,$18
  db $00,$20,$B1,$01,$18
  db $08,$F4,$AD,$01,$18
  db $08,$FC,$9E,$01,$18
  db $08,$04,$B0,$01,$18
  db $08,$0C,$B0,$01,$18
  db $08,$14,$B4,$01,$18
  db $08,$1C,$AC,$01,$18
  db $08,$24,$AF,$01,$18
  db $08,$2C,$A1,$01,$18
Metasprite02C2::
  db $04
  db $00,$00,$02,$01,$40
  db $00,$08,$03,$01,$40
  db $08,$00,$00,$01,$40
  db $08,$08,$01,$01,$40
Metasprite02C3::
  db $04
  db $00,$00,$0E,$01,$40
  db $00,$08,$0F,$01,$40
  db $08,$00,$0C,$01,$40
  db $08,$08,$0D,$01,$40
Metasprite02C4::
  db $04
  db $00,$00,$06,$01,$40
  db $00,$08,$07,$01,$40
  db $08,$00,$04,$01,$40
  db $08,$08,$05,$01,$40
Metasprite02C5::
  db $04
  db $00,$00,$12,$01,$40
  db $00,$08,$13,$01,$40
  db $08,$00,$10,$01,$40
  db $08,$08,$11,$01,$40
MetaspriteTable02End::
