; Autogenerated by ./scripts/dump_metasprites.py

SECTION "Metasprite Table 00", ROMX[$4000], BANK[$2F]
MetaspriteTable00::
  dw Metasprite0000
  dw Metasprite0001
  dw Metasprite0002
  dw Metasprite0003
  dw Metasprite0004
  dw Metasprite0005
  dw Metasprite0006
  dw Metasprite0007
  dw Metasprite0008
  dw Metasprite0009
  dw Metasprite000A
  dw Metasprite000A
  dw Metasprite000A
  dw Metasprite000A
  dw Metasprite000A
  dw Metasprite000A
  dw Metasprite000A
  dw Metasprite0011
  dw Metasprite0012
  dw Metasprite0013
  dw Metasprite0014
  dw Metasprite0015
  dw Metasprite0016
  dw Metasprite0017
  dw Metasprite0018
  dw Metasprite0019
  dw Metasprite001A
  dw Metasprite001A
  dw Metasprite001A
  dw Metasprite001A
  dw Metasprite001A
  dw Metasprite001A
  dw Metasprite001A
  dw Metasprite0021
  dw Metasprite0022
  dw Metasprite0023
  dw Metasprite0024
  dw Metasprite0025
  dw Metasprite0026
  dw Metasprite0027
  dw Metasprite0028
  dw Metasprite0029
  dw Metasprite002A
  dw Metasprite002A
  dw Metasprite002A
  dw Metasprite002A
  dw Metasprite002A
  dw Metasprite002A
  dw Metasprite002A
  dw Metasprite0031
  dw Metasprite0032
  dw Metasprite0033
  dw Metasprite0034
  dw Metasprite0035
  dw Metasprite0036
  dw Metasprite0037
  dw Metasprite0038
  dw Metasprite0039
  dw Metasprite003A
  dw Metasprite003A
  dw Metasprite003A
  dw Metasprite003A
  dw Metasprite003A
  dw Metasprite003A
  dw Metasprite003A
  dw Metasprite0041
  dw Metasprite0042
  dw Metasprite0043
  dw Metasprite0044
  dw Metasprite0045
  dw Metasprite0046
  dw Metasprite0047
  dw Metasprite0048
  dw Metasprite0049
  dw Metasprite004A
  dw Metasprite004A
  dw Metasprite004A
  dw Metasprite004A
  dw Metasprite004A
  dw Metasprite004A
  dw Metasprite004A
  dw Metasprite0051
  dw Metasprite0052
  dw Metasprite0053
  dw Metasprite0054
  dw Metasprite0055
  dw Metasprite0056
  dw Metasprite0057
  dw Metasprite0058
  dw Metasprite0059
  dw Metasprite005A
  dw Metasprite005A
  dw Metasprite005A
  dw Metasprite005A
  dw Metasprite005A
  dw Metasprite005A
  dw Metasprite005A
  dw Metasprite0061
  dw Metasprite0062
  dw Metasprite0063
  dw Metasprite0064
  dw Metasprite0065
  dw Metasprite0066
  dw Metasprite0067
  dw Metasprite0068
  dw Metasprite0069
  dw Metasprite006A
  dw Metasprite006A
  dw Metasprite006A
  dw Metasprite006A
  dw Metasprite006A
  dw Metasprite006A
  dw Metasprite006A
  dw Metasprite0071
  dw Metasprite0072
  dw Metasprite0073
  dw Metasprite0074
  dw Metasprite0075
  dw Metasprite0076
  dw Metasprite0077
  dw Metasprite0078
  dw Metasprite0079
  dw Metasprite007A
  dw Metasprite007A
  dw Metasprite007A
  dw Metasprite007A
  dw Metasprite007A
  dw Metasprite007A
  dw Metasprite007A
  dw Metasprite0081
  dw Metasprite0082
  dw Metasprite0083
  dw Metasprite0084
  dw Metasprite0085
  dw Metasprite0086
  dw Metasprite0087
  dw Metasprite0088
  dw Metasprite0089
  dw Metasprite008A
  dw Metasprite008A
  dw Metasprite008A
  dw Metasprite008A
  dw Metasprite008A
  dw Metasprite008A
  dw Metasprite008A
  dw Metasprite0091
  dw Metasprite0092
  dw Metasprite0093
  dw Metasprite0094
  dw Metasprite0095
  dw Metasprite0096
  dw Metasprite0097
  dw Metasprite0098
  dw Metasprite0099
  dw Metasprite009A
  dw Metasprite009A
  dw Metasprite009A
  dw Metasprite009A
  dw Metasprite009A
  dw Metasprite009A
  dw Metasprite009A
  dw Metasprite00A1
  dw Metasprite00A2
  dw Metasprite00A3
  dw Metasprite00A4
  dw Metasprite00A5
  dw Metasprite00A6
  dw Metasprite00A7
  dw Metasprite00A8
  dw Metasprite00A9
  dw Metasprite00AA
  dw Metasprite00AB
  dw Metasprite00AC
  dw Metasprite00AD
  dw Metasprite00AE
  dw Metasprite00AF
  dw Metasprite00B0
  dw Metasprite00B1
  dw Metasprite00B2
  dw Metasprite00B3
  dw Metasprite00B4
  dw Metasprite00B5
  dw Metasprite00B6
  dw Metasprite00B7
  dw Metasprite00B8
  dw Metasprite00B9
  dw Metasprite00BA
  dw Metasprite00BB
  dw Metasprite00BC
  dw Metasprite00BD
  dw Metasprite00BE
  dw Metasprite00BF
  dw Metasprite00C0
  dw Metasprite00C1
  dw Metasprite00C2
  dw Metasprite00C3
  dw Metasprite00C4
  dw Metasprite00C5
  dw Metasprite00C6
  dw Metasprite00C7
  dw Metasprite00C8
  dw Metasprite00C9
  dw Metasprite00CA
  dw Metasprite00CB
  dw Metasprite00CC
  dw Metasprite00CD
  dw Metasprite00CE
  dw Metasprite00CF
  dw Metasprite00D0
  dw Metasprite00D1
  dw Metasprite00D2
  dw Metasprite00D3
  dw Metasprite00D4
  dw Metasprite00D5
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
  dw MetaspriteTable00End
Metasprite0000::
  db $04
  db $EC,$00,$00,$02,$10
  db $EC,$08,$01,$02,$10
  db $F4,$00,$02,$02,$10
  db $F4,$08,$03,$02,$10
Metasprite0001::
  db $04
  db $EC,$00,$04,$02,$10
  db $EC,$08,$05,$02,$10
  db $F4,$00,$06,$02,$10
  db $F4,$08,$07,$02,$10
Metasprite0002::
  db $04
  db $EC,$00,$08,$02,$10
  db $EC,$08,$09,$02,$10
  db $F4,$00,$0A,$02,$10
  db $F4,$08,$0B,$02,$10
Metasprite0003::
  db $04
  db $EC,$00,$09,$02,$30
  db $EC,$08,$08,$02,$30
  db $F4,$00,$0B,$02,$30
  db $F4,$08,$0A,$02,$30
Metasprite0004::
  db $04
  db $EC,$00,$00,$02,$18
  db $EC,$08,$01,$02,$18
  db $F4,$00,$02,$02,$18
  db $F4,$08,$03,$02,$18
Metasprite0005::
  db $04
  db $EC,$00,$01,$02,$38
  db $EC,$08,$00,$02,$38
  db $F4,$00,$03,$02,$38
  db $F4,$08,$02,$02,$38
Metasprite0006::
  db $04
  db $EC,$00,$04,$02,$18
  db $EC,$08,$05,$02,$18
  db $F4,$00,$06,$02,$18
  db $F4,$08,$07,$02,$18
Metasprite0007::
  db $04
  db $EC,$00,$05,$02,$38
  db $EC,$08,$04,$02,$38
  db $F4,$00,$07,$02,$38
  db $F4,$08,$06,$02,$38
Metasprite0008::
  db $04
  db $EC,$00,$08,$02,$18
  db $EC,$08,$09,$02,$18
  db $F4,$00,$0A,$02,$18
  db $F4,$08,$0B,$02,$18
Metasprite0009::
  db $04
  db $EC,$00,$09,$02,$38
  db $EC,$08,$08,$02,$38
  db $F4,$00,$0B,$02,$38
  db $F4,$08,$0A,$02,$38
Metasprite000A::
  db $04
  db $EC,$00,$0C,$02,$10
  db $EC,$08,$0D,$02,$10
  db $F4,$00,$0E,$02,$10
  db $F4,$08,$0F,$02,$10
Metasprite0011::
  db $04
  db $EC,$00,$10,$02,$10
  db $EC,$08,$11,$02,$10
  db $F4,$00,$12,$02,$10
  db $F4,$08,$13,$02,$10
Metasprite0012::
  db $04
  db $EC,$00,$14,$02,$10
  db $EC,$08,$15,$02,$10
  db $F4,$00,$16,$02,$10
  db $F4,$08,$17,$02,$10
Metasprite0013::
  db $04
  db $EC,$00,$15,$02,$30
  db $EC,$08,$14,$02,$30
  db $F4,$00,$17,$02,$30
  db $F4,$08,$16,$02,$30
Metasprite0014::
  db $04
  db $EC,$00,$0C,$02,$18
  db $EC,$08,$0D,$02,$18
  db $F4,$00,$0E,$02,$18
  db $F4,$08,$0F,$02,$18
Metasprite0015::
  db $04
  db $EC,$00,$0D,$02,$38
  db $EC,$08,$0C,$02,$38
  db $F4,$00,$0F,$02,$38
  db $F4,$08,$0E,$02,$38
Metasprite0016::
  db $04
  db $EC,$00,$10,$02,$18
  db $EC,$08,$11,$02,$18
  db $F4,$00,$12,$02,$18
  db $F4,$08,$13,$02,$18
Metasprite0017::
  db $04
  db $EC,$00,$11,$02,$38
  db $EC,$08,$10,$02,$38
  db $F4,$00,$13,$02,$38
  db $F4,$08,$12,$02,$38
Metasprite0018::
  db $04
  db $EC,$00,$14,$02,$18
  db $EC,$08,$15,$02,$18
  db $F4,$00,$16,$02,$18
  db $F4,$08,$17,$02,$18
Metasprite0019::
  db $04
  db $EC,$00,$15,$02,$38
  db $EC,$08,$14,$02,$38
  db $F4,$00,$17,$02,$38
  db $F4,$08,$16,$02,$38
Metasprite001A::
  db $04
  db $EC,$00,$18,$02,$10
  db $EC,$08,$19,$02,$10
  db $F4,$00,$1A,$02,$10
  db $F4,$08,$1B,$02,$10
Metasprite0021::
  db $04
  db $EC,$00,$1C,$02,$10
  db $EC,$08,$1D,$02,$10
  db $F4,$00,$1E,$02,$10
  db $F4,$08,$1F,$02,$10
Metasprite0022::
  db $04
  db $EC,$00,$20,$02,$10
  db $EC,$08,$21,$02,$10
  db $F4,$00,$22,$02,$10
  db $F4,$08,$23,$02,$10
Metasprite0023::
  db $04
  db $EC,$00,$21,$02,$30
  db $EC,$08,$20,$02,$30
  db $F4,$00,$23,$02,$30
  db $F4,$08,$22,$02,$30
Metasprite0024::
  db $04
  db $EC,$00,$18,$02,$18
  db $EC,$08,$19,$02,$18
  db $F4,$00,$1A,$02,$18
  db $F4,$08,$1B,$02,$18
Metasprite0025::
  db $04
  db $EC,$00,$19,$02,$38
  db $EC,$08,$18,$02,$38
  db $F4,$00,$1B,$02,$38
  db $F4,$08,$1A,$02,$38
Metasprite0026::
  db $04
  db $EC,$00,$1C,$02,$18
  db $EC,$08,$1D,$02,$18
  db $F4,$00,$1E,$02,$18
  db $F4,$08,$1F,$02,$18
Metasprite0027::
  db $04
  db $EC,$00,$1D,$02,$38
  db $EC,$08,$1C,$02,$38
  db $F4,$00,$1F,$02,$38
  db $F4,$08,$1E,$02,$38
Metasprite0028::
  db $04
  db $EC,$00,$20,$02,$18
  db $EC,$08,$21,$02,$18
  db $F4,$00,$22,$02,$18
  db $F4,$08,$23,$02,$18
Metasprite0029::
  db $04
  db $EC,$00,$21,$02,$38
  db $EC,$08,$20,$02,$38
  db $F4,$00,$23,$02,$38
  db $F4,$08,$22,$02,$38
Metasprite002A::
  db $04
  db $EC,$00,$24,$02,$10
  db $EC,$08,$25,$02,$10
  db $F4,$00,$26,$02,$10
  db $F4,$08,$27,$02,$10
Metasprite0031::
  db $04
  db $EC,$00,$28,$02,$10
  db $EC,$08,$29,$02,$10
  db $F4,$00,$2A,$02,$10
  db $F4,$08,$2B,$02,$10
Metasprite0032::
  db $04
  db $EC,$00,$2C,$02,$10
  db $EC,$08,$2D,$02,$10
  db $F4,$00,$2E,$02,$10
  db $F4,$08,$2F,$02,$10
Metasprite0033::
  db $04
  db $EC,$00,$2D,$02,$30
  db $EC,$08,$2C,$02,$30
  db $F4,$00,$2F,$02,$30
  db $F4,$08,$2E,$02,$30
Metasprite0034::
  db $04
  db $EC,$00,$24,$02,$18
  db $EC,$08,$25,$02,$18
  db $F4,$00,$26,$02,$18
  db $F4,$08,$27,$02,$18
Metasprite0035::
  db $04
  db $EC,$00,$25,$02,$38
  db $EC,$08,$24,$02,$38
  db $F4,$00,$27,$02,$38
  db $F4,$08,$26,$02,$38
Metasprite0036::
  db $04
  db $EC,$00,$28,$02,$18
  db $EC,$08,$29,$02,$18
  db $F4,$00,$2A,$02,$18
  db $F4,$08,$2B,$02,$18
Metasprite0037::
  db $04
  db $EC,$00,$29,$02,$38
  db $EC,$08,$28,$02,$38
  db $F4,$00,$2B,$02,$38
  db $F4,$08,$2A,$02,$38
Metasprite0038::
  db $04
  db $EC,$00,$2C,$02,$18
  db $EC,$08,$2D,$02,$18
  db $F4,$00,$2E,$02,$18
  db $F4,$08,$2F,$02,$18
Metasprite0039::
  db $04
  db $EC,$00,$2D,$02,$38
  db $EC,$08,$2C,$02,$38
  db $F4,$00,$2F,$02,$38
  db $F4,$08,$2E,$02,$38
Metasprite003A::
  db $04
  db $EC,$00,$30,$02,$10
  db $EC,$08,$31,$02,$10
  db $F4,$00,$32,$02,$10
  db $F4,$08,$33,$02,$10
Metasprite0041::
  db $04
  db $EC,$00,$34,$02,$10
  db $EC,$08,$35,$02,$10
  db $F4,$00,$36,$02,$10
  db $F4,$08,$37,$02,$10
Metasprite0042::
  db $04
  db $EC,$00,$38,$02,$10
  db $EC,$08,$39,$02,$10
  db $F4,$00,$3A,$02,$10
  db $F4,$08,$3B,$02,$10
Metasprite0043::
  db $04
  db $EC,$00,$39,$02,$30
  db $EC,$08,$38,$02,$30
  db $F4,$00,$3B,$02,$30
  db $F4,$08,$3A,$02,$30
Metasprite0044::
  db $04
  db $EC,$00,$30,$02,$18
  db $EC,$08,$31,$02,$18
  db $F4,$00,$32,$02,$18
  db $F4,$08,$33,$02,$18
Metasprite0045::
  db $04
  db $EC,$00,$31,$02,$38
  db $EC,$08,$30,$02,$38
  db $F4,$00,$33,$02,$38
  db $F4,$08,$32,$02,$38
Metasprite0046::
  db $04
  db $EC,$00,$34,$02,$18
  db $EC,$08,$35,$02,$18
  db $F4,$00,$36,$02,$18
  db $F4,$08,$37,$02,$18
Metasprite0047::
  db $04
  db $EC,$00,$35,$02,$38
  db $EC,$08,$34,$02,$38
  db $F4,$00,$37,$02,$38
  db $F4,$08,$36,$02,$38
Metasprite0048::
  db $04
  db $EC,$00,$38,$02,$18
  db $EC,$08,$39,$02,$18
  db $F4,$00,$3A,$02,$18
  db $F4,$08,$3B,$02,$18
Metasprite0049::
  db $04
  db $EC,$00,$39,$02,$38
  db $EC,$08,$38,$02,$38
  db $F4,$00,$3B,$02,$38
  db $F4,$08,$3A,$02,$38
Metasprite004A::
  db $04
  db $EC,$00,$3C,$02,$10
  db $EC,$08,$3D,$02,$10
  db $F4,$00,$3E,$02,$10
  db $F4,$08,$3F,$02,$10
Metasprite0051::
  db $04
  db $EC,$00,$40,$02,$10
  db $EC,$08,$41,$02,$10
  db $F4,$00,$42,$02,$10
  db $F4,$08,$43,$02,$10
Metasprite0052::
  db $04
  db $EC,$00,$44,$02,$10
  db $EC,$08,$45,$02,$10
  db $F4,$00,$46,$02,$10
  db $F4,$08,$47,$02,$10
Metasprite0053::
  db $04
  db $EC,$00,$45,$02,$30
  db $EC,$08,$44,$02,$30
  db $F4,$00,$47,$02,$30
  db $F4,$08,$46,$02,$30
Metasprite0054::
  db $04
  db $EC,$00,$3C,$02,$18
  db $EC,$08,$3D,$02,$18
  db $F4,$00,$3E,$02,$18
  db $F4,$08,$3F,$02,$18
Metasprite0055::
  db $04
  db $EC,$00,$3D,$02,$38
  db $EC,$08,$3C,$02,$38
  db $F4,$00,$3F,$02,$38
  db $F4,$08,$3E,$02,$38
Metasprite0056::
  db $04
  db $EC,$00,$40,$02,$18
  db $EC,$08,$41,$02,$18
  db $F4,$00,$42,$02,$18
  db $F4,$08,$43,$02,$18
Metasprite0057::
  db $04
  db $EC,$00,$41,$02,$38
  db $EC,$08,$40,$02,$38
  db $F4,$00,$43,$02,$38
  db $F4,$08,$42,$02,$38
Metasprite0058::
  db $04
  db $EC,$00,$44,$02,$18
  db $EC,$08,$45,$02,$18
  db $F4,$00,$46,$02,$18
  db $F4,$08,$47,$02,$18
Metasprite0059::
  db $04
  db $EC,$00,$45,$02,$38
  db $EC,$08,$44,$02,$38
  db $F4,$00,$47,$02,$38
  db $F4,$08,$46,$02,$38
Metasprite005A::
  db $04
  db $EC,$00,$48,$02,$10
  db $EC,$08,$49,$02,$10
  db $F4,$00,$4A,$02,$10
  db $F4,$08,$4B,$02,$10
Metasprite0061::
  db $04
  db $EC,$00,$4C,$02,$10
  db $EC,$08,$4D,$02,$10
  db $F4,$00,$4E,$02,$10
  db $F4,$08,$4F,$02,$10
Metasprite0062::
  db $04
  db $EC,$00,$50,$02,$10
  db $EC,$08,$51,$02,$10
  db $F4,$00,$52,$02,$10
  db $F4,$08,$53,$02,$10
Metasprite0063::
  db $04
  db $EC,$00,$51,$02,$30
  db $EC,$08,$50,$02,$30
  db $F4,$00,$53,$02,$30
  db $F4,$08,$52,$02,$30
Metasprite0064::
  db $04
  db $EC,$00,$48,$02,$18
  db $EC,$08,$49,$02,$18
  db $F4,$00,$4A,$02,$18
  db $F4,$08,$4B,$02,$18
Metasprite0065::
  db $04
  db $EC,$00,$49,$02,$38
  db $EC,$08,$48,$02,$38
  db $F4,$00,$4B,$02,$38
  db $F4,$08,$4A,$02,$38
Metasprite0066::
  db $04
  db $EC,$00,$4C,$02,$18
  db $EC,$08,$4D,$02,$18
  db $F4,$00,$4E,$02,$18
  db $F4,$08,$4F,$02,$18
Metasprite0067::
  db $04
  db $EC,$00,$4D,$02,$38
  db $EC,$08,$4C,$02,$38
  db $F4,$00,$4F,$02,$38
  db $F4,$08,$4E,$02,$38
Metasprite0068::
  db $04
  db $EC,$00,$50,$02,$18
  db $EC,$08,$51,$02,$18
  db $F4,$00,$52,$02,$18
  db $F4,$08,$53,$02,$18
Metasprite0069::
  db $04
  db $EC,$00,$51,$02,$38
  db $EC,$08,$50,$02,$38
  db $F4,$00,$53,$02,$38
  db $F4,$08,$52,$02,$38
Metasprite006A::
  db $04
  db $EC,$00,$54,$02,$10
  db $EC,$08,$55,$02,$10
  db $F4,$00,$56,$02,$10
  db $F4,$08,$57,$02,$10
Metasprite0071::
  db $04
  db $EC,$00,$58,$02,$10
  db $EC,$08,$59,$02,$10
  db $F4,$00,$5A,$02,$10
  db $F4,$08,$5B,$02,$10
Metasprite0072::
  db $04
  db $EC,$00,$5C,$02,$10
  db $EC,$08,$5D,$02,$10
  db $F4,$00,$5E,$02,$10
  db $F4,$08,$5F,$02,$10
Metasprite0073::
  db $04
  db $EC,$00,$5D,$02,$30
  db $EC,$08,$5C,$02,$30
  db $F4,$00,$5F,$02,$30
  db $F4,$08,$5E,$02,$30
Metasprite0074::
  db $04
  db $EC,$00,$54,$02,$18
  db $EC,$08,$55,$02,$18
  db $F4,$00,$56,$02,$18
  db $F4,$08,$57,$02,$18
Metasprite0075::
  db $04
  db $EC,$00,$55,$02,$38
  db $EC,$08,$54,$02,$38
  db $F4,$00,$57,$02,$38
  db $F4,$08,$56,$02,$38
Metasprite0076::
  db $04
  db $EC,$00,$58,$02,$18
  db $EC,$08,$59,$02,$18
  db $F4,$00,$5A,$02,$18
  db $F4,$08,$5B,$02,$18
Metasprite0077::
  db $04
  db $EC,$00,$59,$02,$38
  db $EC,$08,$58,$02,$38
  db $F4,$00,$5B,$02,$38
  db $F4,$08,$5A,$02,$38
Metasprite0078::
  db $04
  db $EC,$00,$5C,$02,$18
  db $EC,$08,$5D,$02,$18
  db $F4,$00,$5E,$02,$18
  db $F4,$08,$5F,$02,$18
Metasprite0079::
  db $04
  db $EC,$00,$5D,$02,$38
  db $EC,$08,$5C,$02,$38
  db $F4,$00,$5F,$02,$38
  db $F4,$08,$5E,$02,$38
Metasprite007A::
  db $04
  db $EC,$00,$60,$02,$10
  db $EC,$08,$61,$02,$10
  db $F4,$00,$62,$02,$10
  db $F4,$08,$63,$02,$10
Metasprite0081::
  db $04
  db $EC,$00,$64,$02,$10
  db $EC,$08,$65,$02,$10
  db $F4,$00,$66,$02,$10
  db $F4,$08,$67,$02,$10
Metasprite0082::
  db $04
  db $EC,$00,$68,$02,$10
  db $EC,$08,$69,$02,$10
  db $F4,$00,$6A,$02,$10
  db $F4,$08,$6B,$02,$10
Metasprite0083::
  db $04
  db $EC,$00,$69,$02,$30
  db $EC,$08,$68,$02,$30
  db $F4,$00,$6B,$02,$30
  db $F4,$08,$6A,$02,$30
Metasprite0084::
  db $04
  db $EC,$00,$60,$02,$18
  db $EC,$08,$61,$02,$18
  db $F4,$00,$62,$02,$18
  db $F4,$08,$63,$02,$18
Metasprite0085::
  db $04
  db $EC,$00,$61,$02,$38
  db $EC,$08,$60,$02,$38
  db $F4,$00,$63,$02,$38
  db $F4,$08,$62,$02,$38
Metasprite0086::
  db $04
  db $EC,$00,$64,$02,$18
  db $EC,$08,$65,$02,$18
  db $F4,$00,$66,$02,$18
  db $F4,$08,$67,$02,$18
Metasprite0087::
  db $04
  db $EC,$00,$65,$02,$38
  db $EC,$08,$64,$02,$38
  db $F4,$00,$67,$02,$38
  db $F4,$08,$66,$02,$38
Metasprite0088::
  db $04
  db $EC,$00,$68,$02,$18
  db $EC,$08,$69,$02,$18
  db $F4,$00,$6A,$02,$18
  db $F4,$08,$6B,$02,$18
Metasprite0089::
  db $04
  db $EC,$00,$69,$02,$38
  db $EC,$08,$68,$02,$38
  db $F4,$00,$6B,$02,$38
  db $F4,$08,$6A,$02,$38
Metasprite008A::
  db $04
  db $EC,$00,$6C,$02,$10
  db $EC,$08,$6D,$02,$10
  db $F4,$00,$6E,$02,$10
  db $F4,$08,$6F,$02,$10
Metasprite0091::
  db $04
  db $EC,$00,$70,$02,$10
  db $EC,$08,$71,$02,$10
  db $F4,$00,$72,$02,$10
  db $F4,$08,$73,$02,$10
Metasprite0092::
  db $04
  db $EC,$00,$74,$02,$10
  db $EC,$08,$75,$02,$10
  db $F4,$00,$76,$02,$10
  db $F4,$08,$77,$02,$10
Metasprite0093::
  db $04
  db $EC,$00,$75,$02,$30
  db $EC,$08,$74,$02,$30
  db $F4,$00,$77,$02,$30
  db $F4,$08,$76,$02,$30
Metasprite0094::
  db $04
  db $EC,$00,$6C,$02,$18
  db $EC,$08,$6D,$02,$18
  db $F4,$00,$6E,$02,$18
  db $F4,$08,$6F,$02,$18
Metasprite0095::
  db $04
  db $EC,$00,$6D,$02,$38
  db $EC,$08,$6C,$02,$38
  db $F4,$00,$6F,$02,$38
  db $F4,$08,$6E,$02,$38
Metasprite0096::
  db $04
  db $EC,$00,$70,$02,$18
  db $EC,$08,$71,$02,$18
  db $F4,$00,$72,$02,$18
  db $F4,$08,$73,$02,$18
Metasprite0097::
  db $04
  db $EC,$00,$71,$02,$38
  db $EC,$08,$70,$02,$38
  db $F4,$00,$73,$02,$38
  db $F4,$08,$72,$02,$38
Metasprite0098::
  db $04
  db $EC,$00,$74,$02,$18
  db $EC,$08,$75,$02,$18
  db $F4,$00,$76,$02,$18
  db $F4,$08,$77,$02,$18
Metasprite0099::
  db $04
  db $EC,$00,$75,$02,$38
  db $EC,$08,$74,$02,$38
  db $F4,$00,$77,$02,$38
  db $F4,$08,$76,$02,$38
Metasprite009A::
  db $01
  db $00,$00,$F8,$01,$1F
Metasprite00A1::
  db $01
  db $00,$00,$F8,$01,$5F
Metasprite00A2::
  db $01
  db $00,$00,$FA,$01,$3F
Metasprite00A3::
  db $01
  db $00,$00,$FA,$01,$1F
Metasprite00A4::
  db $01
  db $00,$00,$F9,$01,$1F
Metasprite00A5::
  db $01
  db $00,$00,$F9,$01,$5F
Metasprite00A6::
  db $01
  db $00,$00,$FB,$01,$3F
Metasprite00A7::
  db $01
  db $00,$00,$FB,$01,$1F
Metasprite00A8::
  db $0C
  db $00,$00,$00,$01,$10
  db $00,$08,$01,$01,$10
  db $00,$10,$02,$01,$10
  db $00,$18,$03,$01,$10
  db $00,$20,$04,$01,$10
  db $00,$28,$05,$01,$10
  db $08,$00,$06,$01,$10
  db $08,$08,$07,$01,$10
  db $08,$10,$08,$01,$10
  db $08,$18,$09,$01,$10
  db $08,$20,$0A,$01,$10
  db $08,$28,$0B,$01,$10
Metasprite00A9::
  db $0C
  db $00,$00,$0C,$01,$10
  db $00,$08,$0D,$01,$10
  db $00,$10,$0E,$01,$10
  db $00,$18,$0F,$01,$10
  db $00,$20,$10,$01,$10
  db $00,$28,$11,$01,$10
  db $08,$00,$12,$01,$10
  db $08,$08,$13,$01,$10
  db $08,$10,$14,$01,$10
  db $08,$18,$15,$01,$10
  db $08,$20,$16,$01,$10
  db $08,$28,$17,$01,$10
Metasprite00AA::
  db $0C
  db $00,$00,$18,$01,$10
  db $00,$08,$19,$01,$10
  db $00,$10,$1A,$01,$10
  db $00,$18,$1B,$01,$10
  db $00,$20,$1C,$01,$10
  db $00,$28,$1D,$01,$10
  db $08,$00,$1E,$01,$10
  db $08,$08,$1F,$01,$10
  db $08,$10,$20,$01,$10
  db $08,$18,$21,$01,$10
  db $08,$20,$22,$01,$10
  db $08,$28,$23,$01,$10
Metasprite00AB::
  db $0C
  db $00,$00,$24,$01,$11
  db $00,$08,$25,$01,$11
  db $00,$10,$26,$01,$11
  db $00,$18,$27,$01,$11
  db $00,$20,$28,$01,$11
  db $00,$28,$29,$01,$11
  db $08,$00,$2A,$01,$11
  db $08,$08,$2B,$01,$11
  db $08,$10,$2C,$01,$11
  db $08,$18,$2D,$01,$11
  db $08,$20,$2E,$01,$11
  db $08,$28,$2F,$01,$11
Metasprite00AC::
  db $0C
  db $00,$00,$30,$01,$11
  db $00,$08,$31,$01,$11
  db $00,$10,$32,$01,$11
  db $00,$18,$33,$01,$11
  db $00,$20,$34,$01,$11
  db $00,$28,$35,$01,$11
  db $08,$00,$36,$01,$11
  db $08,$08,$37,$01,$11
  db $08,$10,$38,$01,$11
  db $08,$18,$39,$01,$11
  db $08,$20,$3A,$01,$11
  db $08,$28,$3B,$01,$11
Metasprite00AD::
  db $0C
  db $00,$00,$3C,$01,$11
  db $00,$08,$3D,$01,$11
  db $00,$10,$3E,$01,$11
  db $00,$18,$3F,$01,$11
  db $00,$20,$40,$01,$11
  db $00,$28,$41,$01,$11
  db $08,$00,$42,$01,$11
  db $08,$08,$43,$01,$11
  db $08,$10,$44,$01,$11
  db $08,$18,$45,$01,$11
  db $08,$20,$46,$01,$11
  db $08,$28,$47,$01,$11
Metasprite00AE::
  db $0C
  db $00,$00,$48,$01,$12
  db $00,$08,$49,$01,$12
  db $00,$10,$4A,$01,$12
  db $00,$18,$4B,$01,$12
  db $00,$20,$4C,$01,$12
  db $00,$28,$4D,$01,$12
  db $08,$00,$4E,$01,$12
  db $08,$08,$4F,$01,$12
  db $08,$10,$50,$01,$12
  db $08,$18,$51,$01,$12
  db $08,$20,$52,$01,$12
  db $08,$28,$53,$01,$12
Metasprite00AF::
  db $0C
  db $00,$00,$54,$01,$12
  db $00,$08,$55,$01,$12
  db $00,$10,$56,$01,$12
  db $00,$18,$57,$01,$12
  db $00,$20,$58,$01,$12
  db $00,$28,$59,$01,$12
  db $08,$00,$5A,$01,$12
  db $08,$08,$5B,$01,$12
  db $08,$10,$5C,$01,$12
  db $08,$18,$5D,$01,$12
  db $08,$20,$5E,$01,$12
  db $08,$28,$5F,$01,$12
Metasprite00B0::
  db $0C
  db $00,$00,$60,$01,$12
  db $00,$08,$61,$01,$12
  db $00,$10,$62,$01,$12
  db $00,$18,$63,$01,$12
  db $00,$20,$64,$01,$12
  db $00,$28,$65,$01,$12
  db $08,$00,$66,$01,$12
  db $08,$08,$67,$01,$12
  db $08,$10,$68,$01,$12
  db $08,$18,$69,$01,$12
  db $08,$20,$6A,$01,$12
  db $08,$28,$6B,$01,$12
Metasprite00B1::
  db $04
  db $00,$00,$6C,$01,$13
  db $00,$08,$6D,$01,$13
  db $08,$00,$6E,$01,$13
  db $08,$08,$6F,$01,$13
Metasprite00B2::
  db $04
  db $00,$00,$70,$01,$13
  db $00,$08,$71,$01,$13
  db $08,$00,$72,$01,$13
  db $08,$08,$73,$01,$13
Metasprite00B3::
  db $04
  db $00,$00,$74,$01,$13
  db $00,$08,$75,$01,$13
  db $08,$00,$76,$01,$13
  db $08,$08,$77,$01,$13
Metasprite00B4::
  db $01
  db $00,$00,$00,$02,$10
Metasprite00B5::
  db $01
  db $00,$00,$01,$02,$10
Metasprite00B6::
  db $01
  db $00,$00,$02,$02,$10
Metasprite00B7::
  db $01
  db $00,$00,$03,$02,$10
Metasprite00B8::
  db $01
  db $00,$00,$04,$02,$10
Metasprite00B9::
  db $01
  db $00,$00,$05,$02,$10
Metasprite00BA::
  db $01
  db $00,$00,$06,$02,$10
Metasprite00BB::
  db $01
  db $00,$00,$07,$02,$10
Metasprite00BC::
  db $04
  db $00,$00,$08,$01,$11
  db $00,$08,$09,$01,$11
  db $08,$00,$0A,$01,$11
  db $08,$08,$0B,$01,$11
Metasprite00BD::
  db $04
  db $00,$00,$0C,$01,$11
  db $00,$08,$0D,$01,$11
  db $08,$00,$0E,$01,$11
  db $08,$08,$0F,$01,$11
Metasprite00BE::
  db $04
  db $00,$00,$10,$01,$11
  db $00,$08,$11,$01,$11
  db $08,$00,$12,$01,$11
  db $08,$08,$13,$01,$11
Metasprite00BF::
  db $04
  db $00,$00,$14,$01,$11
  db $00,$08,$15,$01,$11
  db $08,$00,$16,$01,$11
  db $08,$08,$17,$01,$11
Metasprite00C0::
  db $04
  db $00,$00,$18,$01,$11
  db $00,$08,$19,$01,$11
  db $08,$00,$1A,$01,$11
  db $08,$08,$1B,$01,$11
Metasprite00C1::
  db $04
  db $00,$00,$1C,$01,$12
  db $00,$08,$1D,$01,$12
  db $08,$00,$1E,$01,$12
  db $08,$08,$1F,$01,$12
Metasprite00C2::
  db $04
  db $00,$00,$20,$01,$12
  db $00,$08,$21,$01,$12
  db $08,$00,$22,$01,$12
  db $08,$08,$23,$01,$12
Metasprite00C3::
  db $04
  db $00,$00,$24,$01,$15
  db $00,$08,$25,$01,$15
  db $08,$00,$26,$01,$15
  db $08,$08,$27,$01,$15
Metasprite00C4::
  db $04
  db $00,$00,$28,$01,$13
  db $00,$08,$29,$01,$13
  db $08,$00,$2A,$01,$13
  db $08,$08,$2B,$01,$13
Metasprite00C5::
  db $04
  db $00,$00,$2C,$01,$16
  db $00,$08,$2D,$01,$16
  db $08,$00,$2E,$01,$16
  db $08,$08,$2F,$01,$16
Metasprite00C6::
  db $04
  db $00,$00,$30,$01,$12
  db $00,$08,$31,$01,$12
  db $08,$00,$32,$01,$12
  db $08,$08,$33,$01,$12
Metasprite00C7::
  db $01
  db $00,$00,$34,$02,$10
Metasprite00C8::
  db $04
  db $00,$00,$35,$01,$13
  db $00,$08,$35,$01,$33
  db $08,$00,$35,$01,$53
  db $08,$08,$35,$01,$73
Metasprite00C9::
  db $04
  db $01,$01,$35,$01,$13
  db $01,$07,$35,$01,$33
  db $07,$01,$35,$01,$53
  db $07,$07,$35,$01,$73
Metasprite00CA::
  db $04
  db $00,$00,$36,$01,$13
  db $00,$08,$36,$01,$33
  db $08,$00,$36,$01,$53
  db $08,$08,$36,$01,$73
Metasprite00CB::
  db $01
  db $00,$00,$37,$01,$16
Metasprite00CC::
  db $01
  db $00,$00,$37,$01,$15
Metasprite00CD::
  db $01
  db $00,$00,$2C,$01,$17
Metasprite00CE::
  db $01
  db $00,$00,$00,$02,$30
Metasprite00CF::
  db $01
  db $00,$00,$01,$02,$30
Metasprite00D0::
  db $01
  db $00,$00,$02,$02,$30
Metasprite00D1::
  db $01
  db $00,$00,$03,$02,$30
Metasprite00D2::
  db $01
  db $00,$00,$04,$02,$30
Metasprite00D3::
  db $01
  db $00,$00,$05,$02,$30
Metasprite00D4::
  db $01
  db $00,$00,$06,$02,$30
Metasprite00D5::
  db $01
  db $00,$00,$07,$02,$30
MetaspriteTable00End::
