; Autogenerated by ./scripts/dump_metasprites.py

SECTION "Metasprite Table 06", ROMX[$6606], BANK[$30]
MetaspriteTable06::
  dw Metasprite0600
  dw Metasprite0601
  dw Metasprite0602
  dw Metasprite0603
  dw Metasprite0604
  dw Metasprite0605
  dw Metasprite0606
  dw Metasprite0607
  dw Metasprite0608
  dw Metasprite0609
  dw Metasprite060A
  dw Metasprite060B
  dw Metasprite060C
  dw Metasprite060D
  dw Metasprite060E
  dw Metasprite060E
  dw Metasprite060E
  dw Metasprite0611
  dw Metasprite0611
  dw Metasprite0613
  dw Metasprite0614
  dw Metasprite0615
  dw Metasprite0616
  dw Metasprite0617
  dw Metasprite0618
  dw Metasprite0619
  dw Metasprite061A
  dw Metasprite061B
  dw Metasprite061C
  dw Metasprite061D
  dw Metasprite061E
  dw Metasprite061F
  dw Metasprite0620
  dw Metasprite0621
  dw Metasprite0622
  dw Metasprite0623
  dw Metasprite0624
  dw Metasprite0625
  dw Metasprite0626
  dw Metasprite0627
  dw Metasprite0628
  dw Metasprite0629
  dw Metasprite062A
  dw Metasprite062B
  dw Metasprite062C
  dw Metasprite062D
  dw Metasprite062E
  dw Metasprite062F
  dw Metasprite0630
  dw Metasprite0631
  dw Metasprite0632
  dw Metasprite0633
  dw Metasprite0634
  dw Metasprite0635
  dw Metasprite0636
  dw Metasprite0637
  dw Metasprite0638
  dw Metasprite0639
  dw Metasprite063A
  dw Metasprite063B
  dw Metasprite063C
  dw Metasprite063D
  dw Metasprite063E
  dw Metasprite063F
  dw Metasprite0640
  dw Metasprite0641
  dw Metasprite0642
  dw Metasprite0643
  dw Metasprite0644
  dw Metasprite0645
  dw Metasprite0646
  dw Metasprite0647
  dw Metasprite0648
  dw Metasprite0649
  dw Metasprite0649
  dw Metasprite064B
  dw Metasprite064C
  dw Metasprite064D
  dw Metasprite064E
  dw Metasprite064F
  dw Metasprite064F
  dw Metasprite0651
  dw Metasprite0652
  dw Metasprite0653
  dw Metasprite0654
  dw Metasprite0655
  dw Metasprite0655
  dw Metasprite0657
  dw Metasprite0658
  dw Metasprite0659
  dw Metasprite065A
  dw Metasprite065B
  dw Metasprite065C
  dw Metasprite065D
  dw Metasprite065E
  dw Metasprite065F
  dw Metasprite065F
  dw Metasprite0661
  dw Metasprite0662
  dw Metasprite0663
  dw Metasprite0664
  dw Metasprite0665
  dw Metasprite0666
  dw Metasprite0667
  dw Metasprite0668
  dw Metasprite0669
  dw Metasprite066A
  dw Metasprite066B
  dw Metasprite066C
  dw Metasprite066D
  dw Metasprite066E
  dw Metasprite066F
  dw Metasprite0670
  dw Metasprite0671
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0672
  dw Metasprite0681
  dw Metasprite0682
  dw Metasprite0683
  dw Metasprite0684
  dw Metasprite0685
  dw Metasprite0686
  dw Metasprite0687
  dw Metasprite0688
  dw Metasprite0689
  dw Metasprite068A
  dw Metasprite068B
  dw Metasprite068C
  dw Metasprite068D
  dw Metasprite068E
  dw Metasprite068F
  dw Metasprite0690
  dw Metasprite0691
  dw Metasprite0692
  dw Metasprite0693
  dw Metasprite0694
  dw Metasprite0695
  dw Metasprite0696
  dw Metasprite0697
  dw Metasprite0698
  dw Metasprite0699
  dw Metasprite069A
  dw Metasprite069B
  dw Metasprite069C
  dw Metasprite069D
  dw Metasprite069E
  dw Metasprite069F
  dw Metasprite06A0
  dw Metasprite06A1
  dw Metasprite06A2
  dw Metasprite06A3
  dw Metasprite06A4
  dw Metasprite06A5
  dw Metasprite06A6
  dw Metasprite06A7
  dw Metasprite06A8
  dw Metasprite06A9
  dw Metasprite06AA
  dw Metasprite06AB
  dw Metasprite06AC
  dw Metasprite06AD
  dw Metasprite06AE
  dw Metasprite06AF
  dw Metasprite06B0
  dw Metasprite06B1
  dw Metasprite06B2
  dw Metasprite06B3
  dw Metasprite06B4
  dw Metasprite06B5
  dw Metasprite06B6
  dw Metasprite06B7
  dw Metasprite06B8
  dw Metasprite06B9
  dw Metasprite06BA
  dw Metasprite06BB
  dw Metasprite06BC
  dw Metasprite06BD
  dw Metasprite06BE
  dw Metasprite06BF
  dw Metasprite06C0
  dw Metasprite06C1
  dw Metasprite06C2
  dw Metasprite06C3
  dw Metasprite06C4
  dw Metasprite06C5
  dw Metasprite06C6
  dw Metasprite06C7
  dw Metasprite06C8
  dw Metasprite06C9
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
  dw MetaspriteTable06End
Metasprite0600::
  db $04
  db $00,$00,$4B,$02,$70
  db $00,$08,$4A,$02,$70
  db $08,$00,$49,$02,$70
  db $08,$08,$48,$02,$70
Metasprite0601::
  db $04
  db $00,$00,$4A,$02,$50
  db $00,$08,$4B,$02,$50
  db $08,$00,$48,$02,$50
  db $08,$08,$49,$02,$50
Metasprite0602::
  db $04
  db $00,$00,$53,$02,$70
  db $00,$08,$52,$02,$70
  db $08,$00,$51,$02,$70
  db $08,$08,$50,$02,$70
Metasprite0603::
  db $04
  db $00,$00,$52,$02,$50
  db $00,$08,$53,$02,$50
  db $08,$00,$50,$02,$50
  db $08,$08,$51,$02,$50
Metasprite0604::
  db $04
  db $00,$00,$5B,$02,$70
  db $00,$08,$5A,$02,$70
  db $08,$00,$59,$02,$70
  db $08,$08,$58,$02,$70
Metasprite0605::
  db $04
  db $00,$00,$5A,$02,$50
  db $00,$08,$5B,$02,$50
  db $08,$00,$58,$02,$50
  db $08,$08,$59,$02,$50
Metasprite0606::
  db $04
  db $00,$00,$63,$02,$70
  db $00,$08,$62,$02,$70
  db $08,$00,$61,$02,$70
  db $08,$08,$60,$02,$70
Metasprite0607::
  db $04
  db $00,$00,$62,$02,$50
  db $00,$08,$63,$02,$50
  db $08,$00,$60,$02,$50
  db $08,$08,$61,$02,$50
Metasprite0608::
  db $04
  db $00,$00,$6B,$02,$70
  db $00,$08,$6A,$02,$70
  db $08,$00,$69,$02,$70
  db $08,$08,$68,$02,$70
Metasprite0609::
  db $04
  db $00,$00,$6A,$02,$50
  db $00,$08,$6B,$02,$50
  db $08,$00,$68,$02,$50
  db $08,$08,$69,$02,$50
Metasprite060A::
  db $04
  db $00,$00,$73,$02,$70
  db $00,$08,$72,$02,$70
  db $08,$00,$71,$02,$70
  db $08,$08,$70,$02,$70
Metasprite060B::
  db $04
  db $00,$00,$72,$02,$50
  db $00,$08,$73,$02,$50
  db $08,$00,$70,$02,$50
  db $08,$08,$71,$02,$50
Metasprite060C::
  db $04
  db $00,$00,$7B,$02,$70
  db $00,$08,$7A,$02,$70
  db $08,$00,$79,$02,$70
  db $08,$08,$78,$02,$70
Metasprite060D::
  db $04
  db $00,$00,$7A,$02,$50
  db $00,$08,$7B,$02,$50
  db $08,$00,$78,$02,$50
  db $08,$08,$79,$02,$50
Metasprite060E::
  db $09
  db $FC,$FC,$2C,$01,$1F
  db $FC,$04,$2D,$01,$1F
  db $FC,$0C,$2E,$01,$1F
  db $04,$FC,$2F,$01,$1F
  db $04,$04,$30,$01,$1F
  db $04,$0C,$31,$01,$1F
  db $0C,$FC,$32,$01,$1F
  db $0C,$04,$33,$01,$1F
  db $0C,$0C,$34,$01,$1F
Metasprite0611::
  db $04
  db $F0,$F8,$00,$01,$1A
  db $F0,$00,$01,$01,$1A
  db $F8,$F8,$02,$01,$1A
  db $F8,$00,$03,$01,$1A
Metasprite0613::
  db $08
  db $F0,$F8,$00,$01,$1A
  db $F0,$00,$01,$01,$1A
  db $F8,$F8,$02,$01,$1A
  db $F8,$00,$03,$01,$1A
  db $00,$F8,$04,$01,$1A
  db $00,$00,$05,$01,$1A
  db $08,$F8,$06,$01,$1A
  db $08,$00,$07,$01,$1A
Metasprite0614::
  db $02
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
Metasprite0615::
  db $02
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
Metasprite0616::
  db $04
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
  db $E8,$F8,$0A,$01,$19
  db $E8,$00,$0B,$01,$19
Metasprite0617::
  db $04
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
  db $E8,$F8,$0B,$01,$39
  db $E8,$00,$0A,$01,$39
Metasprite0618::
  db $06
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
  db $E8,$F8,$0A,$01,$19
  db $E8,$00,$0B,$01,$19
  db $F0,$F8,$0C,$01,$19
  db $F0,$00,$0D,$01,$19
Metasprite0619::
  db $06
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
  db $E8,$F8,$0B,$01,$39
  db $E8,$00,$0A,$01,$39
  db $F0,$F8,$0D,$01,$39
  db $F0,$00,$0C,$01,$39
Metasprite061A::
  db $08
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
  db $E8,$F8,$0A,$01,$19
  db $E8,$00,$0B,$01,$19
  db $F0,$F8,$0C,$01,$19
  db $F0,$00,$0D,$01,$19
  db $F8,$F8,$0E,$01,$19
  db $F8,$00,$0F,$01,$19
Metasprite061B::
  db $08
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
  db $E8,$F8,$0B,$01,$39
  db $E8,$00,$0A,$01,$39
  db $F0,$F8,$0D,$01,$39
  db $F0,$00,$0C,$01,$39
  db $F8,$F8,$0F,$01,$39
  db $F8,$00,$0E,$01,$39
Metasprite061C::
  db $0A
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
  db $E8,$F8,$0A,$01,$19
  db $E8,$00,$0B,$01,$19
  db $F0,$F8,$0C,$01,$19
  db $F0,$00,$0D,$01,$19
  db $F8,$F8,$0E,$01,$19
  db $F8,$00,$0F,$01,$19
  db $00,$F8,$0E,$01,$59
  db $00,$00,$0F,$01,$59
Metasprite061D::
  db $0A
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
  db $E8,$F8,$0B,$01,$39
  db $E8,$00,$0A,$01,$39
  db $F0,$F8,$0D,$01,$39
  db $F0,$00,$0C,$01,$39
  db $F8,$F8,$0F,$01,$39
  db $F8,$00,$0E,$01,$39
  db $00,$F8,$0F,$01,$79
  db $00,$00,$0E,$01,$79
Metasprite061E::
  db $0C
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
  db $E8,$F8,$0A,$01,$19
  db $E8,$00,$0B,$01,$19
  db $F0,$F8,$0C,$01,$19
  db $F0,$00,$0D,$01,$19
  db $F8,$F8,$0E,$01,$19
  db $F8,$00,$0F,$01,$19
  db $00,$F8,$0E,$01,$59
  db $00,$00,$0F,$01,$59
  db $08,$F8,$0C,$01,$59
  db $08,$00,$0D,$01,$59
Metasprite061F::
  db $0C
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
  db $E8,$F8,$0B,$01,$39
  db $E8,$00,$0A,$01,$39
  db $F0,$F8,$0D,$01,$39
  db $F0,$00,$0C,$01,$39
  db $F8,$F8,$0F,$01,$39
  db $F8,$00,$0E,$01,$39
  db $00,$F8,$0F,$01,$79
  db $00,$00,$0E,$01,$79
  db $08,$F8,$0D,$01,$79
  db $08,$00,$0C,$01,$79
Metasprite0620::
  db $0E
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
  db $E8,$F8,$0A,$01,$19
  db $E8,$00,$0B,$01,$19
  db $F0,$F8,$0C,$01,$19
  db $F0,$00,$0D,$01,$19
  db $F8,$F8,$0E,$01,$19
  db $F8,$00,$0F,$01,$19
  db $00,$F8,$0E,$01,$59
  db $00,$00,$0F,$01,$59
  db $08,$F8,$0C,$01,$59
  db $08,$00,$0D,$01,$59
  db $10,$F8,$0A,$01,$59
  db $10,$00,$0B,$01,$59
Metasprite0621::
  db $0E
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
  db $E8,$F8,$0B,$01,$39
  db $E8,$00,$0A,$01,$39
  db $F0,$F8,$0D,$01,$39
  db $F0,$00,$0C,$01,$39
  db $F8,$F8,$0F,$01,$39
  db $F8,$00,$0E,$01,$39
  db $00,$F8,$0F,$01,$79
  db $00,$00,$0E,$01,$79
  db $08,$F8,$0D,$01,$79
  db $08,$00,$0C,$01,$79
  db $10,$F8,$0B,$01,$79
  db $10,$00,$0A,$01,$79
Metasprite0622::
  db $10
  db $E0,$F8,$08,$01,$19
  db $E0,$00,$09,$01,$19
  db $E8,$F8,$0A,$01,$19
  db $E8,$00,$0B,$01,$19
  db $F0,$F8,$0C,$01,$19
  db $F0,$00,$0D,$01,$19
  db $F8,$F8,$0E,$01,$19
  db $F8,$00,$0F,$01,$19
  db $00,$F8,$0E,$01,$59
  db $00,$00,$0F,$01,$59
  db $08,$F8,$0C,$01,$59
  db $08,$00,$0D,$01,$59
  db $10,$F8,$0A,$01,$59
  db $10,$00,$0B,$01,$59
  db $18,$F8,$08,$01,$59
  db $18,$00,$09,$01,$59
Metasprite0623::
  db $10
  db $E0,$F8,$09,$01,$39
  db $E0,$00,$08,$01,$39
  db $E8,$F8,$0B,$01,$39
  db $E8,$00,$0A,$01,$39
  db $F0,$F8,$0D,$01,$39
  db $F0,$00,$0C,$01,$39
  db $F8,$F8,$0F,$01,$39
  db $F8,$00,$0E,$01,$39
  db $00,$F8,$0F,$01,$79
  db $00,$00,$0E,$01,$79
  db $08,$F8,$0D,$01,$79
  db $08,$00,$0C,$01,$79
  db $10,$F8,$0B,$01,$79
  db $10,$00,$0A,$01,$79
  db $18,$F8,$09,$01,$79
  db $18,$00,$08,$01,$79
Metasprite0624::
  db $01
  db $04,$FC,$10,$01,$18
Metasprite0625::
  db $01
  db $04,$0C,$10,$01,$38
Metasprite0626::
  db $02
  db $04,$FC,$10,$01,$18
  db $04,$04,$11,$01,$18
Metasprite0627::
  db $02
  db $04,$04,$11,$01,$38
  db $04,$0C,$10,$01,$38
Metasprite0628::
  db $03
  db $04,$FC,$10,$01,$18
  db $04,$04,$11,$01,$18
  db $04,$0C,$12,$01,$18
Metasprite0629::
  db $03
  db $04,$FC,$12,$01,$38
  db $04,$04,$11,$01,$38
  db $04,$0C,$10,$01,$38
Metasprite062A::
  db $03
  db $04,$FC,$13,$01,$18
  db $04,$04,$14,$01,$18
  db $04,$0C,$15,$01,$18
Metasprite062B::
  db $03
  db $04,$FC,$15,$01,$38
  db $04,$04,$14,$01,$38
  db $04,$0C,$13,$01,$38
Metasprite062C::
  db $04
  db $F0,$F8,$00,$01,$1E
  db $F8,$F8,$02,$01,$1E
  db $00,$F8,$04,$01,$1E
  db $08,$F8,$06,$01,$1E
Metasprite062D::
  db $04
  db $F0,$00,$01,$01,$1E
  db $F8,$00,$03,$01,$1E
  db $00,$00,$05,$01,$1E
  db $08,$00,$07,$01,$1E
Metasprite062E::
  db $08
  db $F0,$F8,$00,$01,$1E
  db $F0,$00,$01,$01,$1E
  db $F8,$F8,$02,$01,$1E
  db $F8,$00,$03,$01,$1E
  db $00,$F8,$04,$01,$1E
  db $00,$00,$05,$01,$1E
  db $08,$F8,$06,$01,$1E
  db $08,$00,$07,$01,$1E
Metasprite062F::
  db $08
  db $F0,$F8,$08,$01,$1E
  db $F0,$00,$09,$01,$1E
  db $F8,$F8,$0A,$01,$1E
  db $F8,$00,$0B,$01,$1E
  db $00,$F8,$0C,$01,$1E
  db $00,$00,$0D,$01,$1E
  db $08,$F8,$0E,$01,$1E
  db $08,$00,$0F,$01,$1E
Metasprite0630::
  db $08
  db $F0,$F8,$10,$01,$1E
  db $F0,$00,$11,$01,$1E
  db $F8,$F8,$12,$01,$1E
  db $F8,$00,$13,$01,$1E
  db $00,$F8,$14,$01,$1E
  db $00,$00,$15,$01,$1E
  db $08,$F8,$16,$01,$1E
  db $08,$00,$17,$01,$1E
Metasprite0631::
  db $08
  db $F0,$F8,$18,$01,$1E
  db $F0,$00,$19,$01,$1E
  db $F8,$F8,$1A,$01,$1E
  db $F8,$00,$1B,$01,$1E
  db $00,$F8,$1C,$01,$1E
  db $00,$00,$1D,$01,$1E
  db $08,$F8,$1E,$01,$1E
  db $08,$00,$1F,$01,$1E
Metasprite0632::
  db $08
  db $F0,$F8,$20,$01,$1E
  db $F0,$00,$21,$01,$1E
  db $F8,$F8,$22,$01,$1E
  db $F8,$00,$23,$01,$1E
  db $00,$F8,$24,$01,$1E
  db $00,$00,$25,$01,$1E
  db $08,$F8,$26,$01,$1E
  db $08,$00,$27,$01,$1E
Metasprite0633::
  db $08
  db $F0,$F8,$28,$01,$1E
  db $F0,$00,$29,$01,$1E
  db $F8,$F8,$2A,$01,$1E
  db $F8,$00,$2B,$01,$1E
  db $00,$F8,$2C,$01,$1E
  db $00,$00,$2D,$01,$1E
  db $08,$F8,$2E,$01,$1E
  db $08,$00,$2F,$01,$1E
Metasprite0634::
  db $08
  db $F0,$F8,$30,$01,$1E
  db $F0,$00,$31,$01,$1E
  db $F8,$F8,$32,$01,$1E
  db $F8,$00,$33,$01,$1E
  db $00,$F8,$34,$01,$1E
  db $00,$00,$35,$01,$1E
  db $08,$F8,$36,$01,$1E
  db $08,$00,$37,$01,$1E
Metasprite0635::
  db $03
  db $F4,$F8,$00,$01,$1F
  db $FC,$F8,$02,$01,$1F
  db $04,$F8,$04,$01,$1F
Metasprite0636::
  db $03
  db $F4,$00,$01,$01,$1F
  db $FC,$00,$03,$01,$1F
  db $04,$00,$05,$01,$1F
Metasprite0637::
  db $06
  db $F4,$F8,$00,$01,$1F
  db $F4,$00,$01,$01,$1F
  db $FC,$F8,$02,$01,$1F
  db $FC,$00,$03,$01,$1F
  db $04,$F8,$04,$01,$1F
  db $04,$00,$05,$01,$1F
Metasprite0638::
  db $06
  db $F4,$F8,$06,$01,$1F
  db $F4,$00,$07,$01,$1F
  db $FC,$F8,$08,$01,$1F
  db $FC,$00,$09,$01,$1F
  db $04,$F8,$0A,$01,$1F
  db $04,$00,$0B,$01,$1F
Metasprite0639::
  db $06
  db $F4,$F8,$0C,$01,$1F
  db $F4,$00,$0D,$01,$1F
  db $FC,$F8,$0E,$01,$1F
  db $FC,$00,$0F,$01,$1F
  db $04,$F8,$10,$01,$1F
  db $04,$00,$11,$01,$1F
Metasprite063A::
  db $06
  db $F4,$F8,$12,$01,$1F
  db $F4,$00,$13,$01,$1F
  db $FC,$F8,$14,$01,$1F
  db $FC,$00,$15,$01,$1F
  db $04,$F8,$16,$01,$1F
  db $04,$00,$17,$01,$1F
Metasprite063B::
  db $06
  db $F4,$F8,$18,$01,$1F
  db $F4,$00,$19,$01,$1F
  db $FC,$F8,$1A,$01,$1F
  db $FC,$00,$1B,$01,$1F
  db $04,$F8,$1C,$01,$1F
  db $04,$00,$1D,$01,$1F
Metasprite063C::
  db $06
  db $F4,$F8,$01,$01,$3F
  db $F4,$00,$00,$01,$3F
  db $FC,$F8,$03,$01,$3F
  db $FC,$00,$02,$01,$3F
  db $04,$F8,$05,$01,$3F
  db $04,$00,$04,$01,$3F
Metasprite063D::
  db $04
  db $00,$00,$00,$01,$1F
  db $00,$08,$01,$01,$1F
  db $08,$00,$02,$01,$1F
  db $08,$08,$03,$01,$1F
Metasprite063E::
  db $04
  db $00,$00,$04,$01,$1F
  db $00,$08,$05,$01,$1F
  db $08,$00,$06,$01,$1F
  db $08,$08,$07,$01,$1F
Metasprite063F::
  db $09
  db $F8,$FC,$08,$01,$18
  db $F8,$04,$09,$01,$18
  db $F8,$0C,$0A,$01,$18
  db $00,$FC,$0B,$01,$18
  db $00,$04,$0C,$01,$18
  db $00,$0C,$0D,$01,$18
  db $08,$FC,$0E,$01,$18
  db $08,$04,$0F,$01,$18
  db $08,$0C,$10,$01,$18
Metasprite0640::
  db $09
  db $F8,$FC,$11,$01,$18
  db $F8,$04,$12,$01,$18
  db $F8,$0C,$13,$01,$18
  db $00,$FC,$14,$01,$18
  db $00,$04,$15,$01,$18
  db $00,$0C,$16,$01,$18
  db $08,$FC,$17,$01,$18
  db $08,$04,$18,$01,$18
  db $08,$0C,$19,$01,$18
Metasprite0641::
  db $09
  db $F8,$FC,$1A,$01,$18
  db $F8,$04,$1B,$01,$18
  db $F8,$0C,$1C,$01,$18
  db $00,$FC,$1D,$01,$18
  db $00,$04,$1E,$01,$18
  db $00,$0C,$1F,$01,$18
  db $08,$FC,$20,$01,$18
  db $08,$04,$21,$01,$18
  db $08,$0C,$22,$01,$18
Metasprite0642::
  db $09
  db $F8,$FC,$23,$01,$18
  db $F8,$04,$24,$01,$18
  db $F8,$0C,$25,$01,$18
  db $00,$FC,$26,$01,$18
  db $00,$04,$27,$01,$18
  db $00,$0C,$28,$01,$18
  db $08,$FC,$29,$01,$18
  db $08,$04,$2A,$01,$18
  db $08,$0C,$2B,$01,$18
Metasprite0643::
  db $04
  db $00,$00,$3C,$01,$1F
  db $00,$08,$3D,$01,$1F
  db $08,$00,$3E,$01,$1F
  db $08,$08,$3F,$01,$1F
Metasprite0644::
  db $09
  db $E8,$F4,$00,$01,$1B
  db $E8,$FC,$01,$01,$1B
  db $E8,$04,$02,$01,$1B
  db $F0,$F4,$03,$01,$1B
  db $F0,$FC,$04,$01,$1B
  db $F0,$04,$05,$01,$1B
  db $F8,$F4,$06,$01,$1B
  db $F8,$FC,$07,$01,$1B
  db $F8,$04,$08,$01,$1B
Metasprite0645::
  db $08
  db $F0,$F0,$09,$01,$1B
  db $F0,$F8,$0A,$01,$1B
  db $F0,$00,$0B,$01,$1B
  db $F0,$08,$0C,$01,$1B
  db $F8,$F0,$0D,$01,$1B
  db $F8,$F8,$0E,$01,$1B
  db $F8,$00,$0F,$01,$1B
  db $F8,$08,$10,$01,$1B
Metasprite0646::
  db $08
  db $F0,$F0,$11,$01,$1B
  db $F0,$F8,$12,$01,$1B
  db $F0,$00,$13,$01,$1B
  db $F0,$08,$14,$01,$1B
  db $F8,$F0,$15,$01,$1B
  db $F8,$F8,$16,$01,$1B
  db $F8,$00,$17,$01,$1B
  db $F8,$08,$18,$01,$1B
Metasprite0647::
  db $04
  db $00,$00,$19,$01,$1B
  db $00,$08,$1A,$01,$1B
  db $08,$00,$1B,$01,$1B
  db $08,$08,$1C,$01,$1B
Metasprite0648::
  db $04
  db $00,$00,$1D,$01,$1B
  db $00,$08,$1E,$01,$1B
  db $08,$00,$1F,$01,$1B
  db $08,$08,$20,$01,$1B
Metasprite0649::
  db $04
  db $F8,$F8,$00,$01,$19
  db $F8,$00,$01,$01,$19
  db $00,$F8,$02,$01,$19
  db $00,$00,$03,$01,$19
Metasprite064B::
  db $09
  db $F4,$F4,$04,$01,$19
  db $F4,$FC,$05,$01,$19
  db $F4,$04,$06,$01,$19
  db $FC,$F4,$07,$01,$19
  db $FC,$FC,$08,$01,$19
  db $FC,$04,$09,$01,$19
  db $04,$F4,$0A,$01,$19
  db $04,$FC,$0B,$01,$19
  db $04,$04,$0C,$01,$19
Metasprite064C::
  db $10
  db $F0,$F0,$0D,$01,$19
  db $F0,$F8,$0E,$01,$19
  db $F0,$00,$0F,$01,$19
  db $F0,$08,$10,$01,$19
  db $F8,$F0,$11,$01,$19
  db $F8,$F8,$12,$01,$19
  db $F8,$00,$13,$01,$19
  db $F8,$08,$14,$01,$19
  db $00,$F0,$15,$01,$19
  db $00,$F8,$16,$01,$19
  db $00,$00,$17,$01,$19
  db $00,$08,$18,$01,$19
  db $08,$F0,$19,$01,$19
  db $08,$F8,$1A,$01,$19
  db $08,$00,$1B,$01,$19
  db $08,$08,$1C,$01,$19
Metasprite064D::
  db $04
  db $00,$00,$1D,$01,$19
  db $00,$08,$1E,$01,$19
  db $08,$00,$1F,$01,$19
  db $08,$08,$20,$01,$19
Metasprite064E::
  db $04
  db $00,$00,$21,$01,$19
  db $00,$08,$22,$01,$19
  db $08,$00,$23,$01,$19
  db $08,$08,$24,$01,$19
Metasprite064F::
  db $09
  db $E8,$F4,$00,$01,$18
  db $E8,$FC,$01,$01,$18
  db $E8,$04,$02,$01,$18
  db $F0,$F4,$03,$01,$18
  db $F0,$FC,$04,$01,$18
  db $F0,$04,$05,$01,$18
  db $F8,$F4,$06,$01,$18
  db $F8,$FC,$07,$01,$18
  db $F8,$04,$08,$01,$18
Metasprite0651::
  db $08
  db $F0,$F0,$09,$01,$18
  db $F0,$F8,$0A,$01,$18
  db $F0,$00,$0B,$01,$18
  db $F0,$08,$0C,$01,$18
  db $F8,$F0,$0D,$01,$18
  db $F8,$F8,$0E,$01,$18
  db $F8,$00,$0F,$01,$18
  db $F8,$08,$10,$01,$18
Metasprite0652::
  db $08
  db $F0,$F0,$11,$01,$18
  db $F0,$F8,$12,$01,$18
  db $F0,$00,$13,$01,$18
  db $F0,$08,$14,$01,$18
  db $F8,$F0,$15,$01,$18
  db $F8,$F8,$16,$01,$18
  db $F8,$00,$17,$01,$18
  db $F8,$08,$18,$01,$18
Metasprite0653::
  db $04
  db $00,$00,$19,$01,$18
  db $00,$08,$1A,$01,$18
  db $08,$00,$1B,$01,$18
  db $08,$08,$1C,$01,$18
Metasprite0654::
  db $04
  db $00,$00,$1A,$01,$38
  db $00,$08,$19,$01,$38
  db $08,$00,$1C,$01,$38
  db $08,$08,$1B,$01,$38
Metasprite0655::
  db $04
  db $F0,$F8,$00,$01,$1A
  db $F0,$00,$01,$01,$1A
  db $F8,$F8,$02,$01,$1A
  db $F8,$00,$03,$01,$1A
Metasprite0657::
  db $06
  db $F0,$F4,$04,$01,$1A
  db $F0,$FC,$05,$01,$1A
  db $F0,$04,$06,$01,$1A
  db $F8,$F4,$07,$01,$1A
  db $F8,$FC,$08,$01,$1A
  db $F8,$04,$09,$01,$1A
Metasprite0658::
  db $0C
  db $E8,$F0,$0A,$01,$1A
  db $E8,$F8,$0B,$01,$1A
  db $E8,$00,$0C,$01,$1A
  db $E8,$08,$0D,$01,$1A
  db $F0,$F0,$0E,$01,$1A
  db $F0,$F8,$0F,$01,$1A
  db $F0,$00,$10,$01,$1A
  db $F0,$08,$11,$01,$1A
  db $F8,$F0,$12,$01,$1A
  db $F8,$F8,$13,$01,$1A
  db $F8,$00,$14,$01,$1A
  db $F8,$08,$15,$01,$1A
Metasprite0659::
  db $04
  db $00,$00,$16,$01,$1A
  db $00,$08,$17,$01,$1A
  db $08,$00,$18,$01,$1A
  db $08,$08,$19,$01,$1A
Metasprite065A::
  db $04
  db $00,$00,$1A,$01,$1A
  db $00,$08,$1B,$01,$1A
  db $08,$00,$1C,$01,$1A
  db $08,$08,$1D,$01,$1A
Metasprite065B::
  db $01
  db $FC,$FC,$3F,$01,$1A
Metasprite065C::
  db $01
  db $FC,$FC,$3F,$01,$7A
Metasprite065D::
  db $01
  db $FC,$FC,$3F,$01,$5A
Metasprite065E::
  db $01
  db $FC,$FC,$3F,$01,$3A
Metasprite065F::
  db $04
  db $00,$00,$00,$01,$1E
  db $00,$08,$01,$01,$1E
  db $08,$00,$02,$01,$1E
  db $08,$08,$03,$01,$1E
Metasprite0661::
  db $04
  db $00,$00,$04,$01,$1D
  db $00,$08,$05,$01,$1D
  db $08,$00,$06,$01,$1D
  db $08,$08,$07,$01,$1D
Metasprite0662::
  db $04
  db $00,$00,$08,$01,$18
  db $00,$08,$09,$01,$18
  db $08,$00,$0A,$01,$18
  db $08,$08,$0B,$01,$18
Metasprite0663::
  db $04
  db $00,$00,$0C,$01,$1A
  db $00,$08,$0D,$01,$1A
  db $08,$00,$0E,$01,$1A
  db $08,$08,$0F,$01,$1A
Metasprite0664::
  db $04
  db $00,$00,$10,$01,$1F
  db $00,$08,$11,$01,$1F
  db $08,$00,$12,$01,$1F
  db $08,$08,$13,$01,$1F
Metasprite0665::
  db $04
  db $00,$00,$14,$01,$1A
  db $00,$08,$15,$01,$1A
  db $08,$00,$16,$01,$1A
  db $08,$08,$17,$01,$1A
Metasprite0666::
  db $04
  db $00,$00,$18,$01,$18
  db $00,$08,$19,$01,$18
  db $08,$00,$1A,$01,$18
  db $08,$08,$1B,$01,$18
Metasprite0667::
  db $04
  db $00,$00,$1C,$01,$19
  db $00,$08,$1D,$01,$19
  db $08,$00,$1E,$01,$19
  db $08,$08,$1F,$01,$19
Metasprite0668::
  db $01
  db $F8,$FC,$20,$02,$18
Metasprite0669::
  db $01
  db $F8,$FC,$20,$02,$38
Metasprite066A::
  db $04
  db $F0,$F8,$21,$02,$18
  db $F0,$00,$22,$02,$18
  db $F8,$F8,$23,$02,$18
  db $F8,$00,$24,$02,$18
Metasprite066B::
  db $04
  db $F0,$F8,$22,$02,$38
  db $F0,$00,$21,$02,$38
  db $F8,$F8,$24,$02,$38
  db $F8,$00,$23,$02,$38
Metasprite066C::
  db $09
  db $E8,$F4,$25,$02,$18
  db $E8,$FC,$26,$02,$18
  db $E8,$04,$27,$02,$18
  db $F0,$F4,$28,$02,$18
  db $F0,$FC,$29,$02,$18
  db $F0,$04,$2A,$02,$18
  db $F8,$F4,$2B,$02,$18
  db $F8,$FC,$2C,$02,$18
  db $F8,$04,$2D,$02,$18
Metasprite066D::
  db $09
  db $E8,$F4,$27,$02,$38
  db $E8,$FC,$26,$02,$38
  db $E8,$04,$25,$02,$38
  db $F0,$F4,$2A,$02,$38
  db $F0,$FC,$29,$02,$38
  db $F0,$04,$28,$02,$38
  db $F8,$F4,$2D,$02,$38
  db $F8,$FC,$2C,$02,$38
  db $F8,$04,$2B,$02,$38
Metasprite066E::
  db $04
  db $00,$00,$2E,$02,$18
  db $00,$08,$2F,$02,$18
  db $08,$00,$30,$02,$18
  db $08,$08,$31,$02,$18
Metasprite066F::
  db $04
  db $00,$00,$2F,$02,$38
  db $00,$08,$2E,$02,$38
  db $08,$00,$31,$02,$38
  db $08,$08,$30,$02,$38
Metasprite0670::
  db $04
  db $00,$00,$32,$02,$18
  db $00,$08,$33,$02,$18
  db $08,$00,$34,$02,$18
  db $08,$08,$35,$02,$18
Metasprite0671::
  db $04
  db $00,$00,$33,$02,$38
  db $00,$08,$32,$02,$38
  db $08,$00,$35,$02,$38
  db $08,$08,$34,$02,$38
Metasprite0672::
  db $04
  db $00,$00,$00,$02,$18
  db $00,$08,$01,$02,$18
  db $08,$00,$02,$02,$18
  db $08,$08,$03,$02,$18
Metasprite0681::
  db $04
  db $00,$00,$01,$02,$38
  db $00,$08,$00,$02,$38
  db $08,$00,$03,$02,$38
  db $08,$08,$02,$02,$38
Metasprite0682::
  db $04
  db $00,$00,$04,$02,$18
  db $00,$08,$05,$02,$18
  db $08,$00,$06,$02,$18
  db $08,$08,$07,$02,$18
Metasprite0683::
  db $04
  db $00,$00,$05,$02,$38
  db $00,$08,$04,$02,$38
  db $08,$00,$07,$02,$38
  db $08,$08,$06,$02,$38
Metasprite0684::
  db $04
  db $00,$00,$08,$02,$18
  db $00,$08,$09,$02,$18
  db $08,$00,$0A,$02,$18
  db $08,$08,$0B,$02,$18
Metasprite0685::
  db $04
  db $00,$00,$09,$02,$38
  db $00,$08,$08,$02,$38
  db $08,$00,$0B,$02,$38
  db $08,$08,$0A,$02,$38
Metasprite0686::
  db $04
  db $00,$00,$0C,$02,$18
  db $00,$08,$0D,$02,$18
  db $08,$00,$0E,$02,$18
  db $08,$08,$0F,$02,$18
Metasprite0687::
  db $04
  db $00,$00,$0D,$02,$38
  db $00,$08,$0C,$02,$38
  db $08,$00,$0F,$02,$38
  db $08,$08,$0E,$02,$38
Metasprite0688::
  db $04
  db $00,$00,$10,$02,$18
  db $00,$08,$11,$02,$18
  db $08,$00,$12,$02,$18
  db $08,$08,$13,$02,$18
Metasprite0689::
  db $04
  db $00,$00,$11,$02,$38
  db $00,$08,$10,$02,$38
  db $08,$00,$13,$02,$38
  db $08,$08,$12,$02,$38
Metasprite068A::
  db $04
  db $00,$00,$14,$02,$18
  db $00,$08,$15,$02,$18
  db $08,$00,$16,$02,$18
  db $08,$08,$17,$02,$18
Metasprite068B::
  db $04
  db $00,$00,$15,$02,$38
  db $00,$08,$14,$02,$38
  db $08,$00,$17,$02,$38
  db $08,$08,$16,$02,$38
Metasprite068C::
  db $04
  db $00,$00,$18,$02,$18
  db $00,$08,$19,$02,$18
  db $08,$00,$1A,$02,$18
  db $08,$08,$1B,$02,$18
Metasprite068D::
  db $04
  db $00,$00,$19,$02,$38
  db $00,$08,$18,$02,$38
  db $08,$00,$1B,$02,$38
  db $08,$08,$1A,$02,$38
Metasprite068E::
  db $04
  db $00,$00,$1C,$02,$18
  db $00,$08,$1D,$02,$18
  db $08,$00,$1E,$02,$18
  db $08,$08,$1F,$02,$18
Metasprite068F::
  db $04
  db $00,$00,$1D,$02,$38
  db $00,$08,$1C,$02,$38
  db $08,$00,$1F,$02,$38
  db $08,$08,$1E,$02,$38
Metasprite0690::
  db $04
  db $00,$00,$20,$02,$18
  db $00,$08,$21,$02,$18
  db $08,$00,$22,$02,$18
  db $08,$08,$23,$02,$18
Metasprite0691::
  db $04
  db $00,$00,$21,$02,$38
  db $00,$08,$20,$02,$38
  db $08,$00,$23,$02,$38
  db $08,$08,$22,$02,$38
Metasprite0692::
  db $04
  db $00,$00,$24,$02,$18
  db $00,$08,$25,$02,$18
  db $08,$00,$26,$02,$18
  db $08,$08,$27,$02,$18
Metasprite0693::
  db $04
  db $00,$00,$25,$02,$38
  db $00,$08,$24,$02,$38
  db $08,$00,$27,$02,$38
  db $08,$08,$26,$02,$38
Metasprite0694::
  db $04
  db $00,$00,$28,$02,$18
  db $00,$08,$29,$02,$18
  db $08,$00,$2A,$02,$18
  db $08,$08,$2B,$02,$18
Metasprite0695::
  db $04
  db $00,$00,$29,$02,$38
  db $00,$08,$28,$02,$38
  db $08,$00,$2B,$02,$38
  db $08,$08,$2A,$02,$38
Metasprite0696::
  db $04
  db $00,$00,$2C,$02,$18
  db $00,$08,$2D,$02,$18
  db $08,$00,$2E,$02,$18
  db $08,$08,$2F,$02,$18
Metasprite0697::
  db $04
  db $00,$00,$2D,$02,$38
  db $00,$08,$2C,$02,$38
  db $08,$00,$2F,$02,$38
  db $08,$08,$2E,$02,$38
Metasprite0698::
  db $04
  db $00,$00,$30,$02,$18
  db $00,$08,$31,$02,$18
  db $08,$00,$32,$02,$18
  db $08,$08,$33,$02,$18
Metasprite0699::
  db $04
  db $00,$00,$31,$02,$38
  db $00,$08,$30,$02,$38
  db $08,$00,$33,$02,$38
  db $08,$08,$32,$02,$38
Metasprite069A::
  db $04
  db $00,$00,$34,$02,$18
  db $00,$08,$35,$02,$18
  db $08,$00,$36,$02,$18
  db $08,$08,$37,$02,$18
Metasprite069B::
  db $04
  db $00,$00,$35,$02,$38
  db $00,$08,$34,$02,$38
  db $08,$00,$37,$02,$38
  db $08,$08,$36,$02,$38
Metasprite069C::
  db $04
  db $00,$00,$38,$02,$18
  db $00,$08,$39,$02,$18
  db $08,$00,$3A,$02,$18
  db $08,$08,$3B,$02,$18
Metasprite069D::
  db $04
  db $00,$00,$39,$02,$38
  db $00,$08,$38,$02,$38
  db $08,$00,$3B,$02,$38
  db $08,$08,$3A,$02,$38
Metasprite069E::
  db $04
  db $00,$00,$3C,$02,$18
  db $00,$08,$3D,$02,$18
  db $08,$00,$3E,$02,$18
  db $08,$08,$3F,$02,$18
Metasprite069F::
  db $04
  db $00,$00,$3D,$02,$38
  db $00,$08,$3C,$02,$38
  db $08,$00,$3F,$02,$38
  db $08,$08,$3E,$02,$38
Metasprite06A0::
  db $03
  db $F8,$F4,$00,$01,$1F
  db $F8,$FC,$01,$01,$1F
  db $F8,$04,$02,$01,$1F
Metasprite06A1::
  db $09
  db $E8,$F4,$03,$01,$1F
  db $E8,$FC,$04,$01,$1F
  db $E8,$04,$05,$01,$1F
  db $F0,$F4,$06,$01,$1F
  db $F0,$FC,$07,$01,$1F
  db $F0,$04,$08,$01,$1F
  db $F8,$F4,$09,$01,$1F
  db $F8,$FC,$0A,$01,$1F
  db $F8,$04,$0B,$01,$1F
Metasprite06A2::
  db $09
  db $E8,$F4,$0C,$01,$1F
  db $E8,$FC,$0D,$01,$1F
  db $E8,$04,$0E,$01,$1F
  db $F0,$F4,$0F,$01,$1F
  db $F0,$FC,$10,$01,$1F
  db $F0,$04,$11,$01,$1F
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06A3::
  db $09
  db $E8,$F4,$15,$01,$1B
  db $E8,$FC,$16,$01,$1B
  db $E8,$04,$17,$01,$1B
  db $F0,$F4,$18,$01,$1B
  db $F0,$FC,$19,$01,$1B
  db $F0,$04,$1A,$01,$1B
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06A4::
  db $09
  db $E8,$F4,$1B,$01,$1B
  db $E8,$FC,$1C,$01,$1B
  db $E8,$04,$1D,$01,$1B
  db $F0,$F4,$1E,$01,$1B
  db $F0,$FC,$1F,$01,$1B
  db $F0,$04,$20,$01,$1B
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06A5::
  db $09
  db $E8,$F4,$21,$01,$1B
  db $E8,$FC,$22,$01,$1B
  db $E8,$04,$23,$01,$1B
  db $F0,$F4,$24,$01,$1B
  db $F0,$FC,$25,$01,$1B
  db $F0,$04,$26,$01,$1B
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06A6::
  db $09
  db $E8,$F4,$27,$01,$1B
  db $E8,$FC,$28,$01,$1B
  db $E8,$04,$29,$01,$1B
  db $F0,$F4,$2A,$01,$1B
  db $F0,$FC,$2B,$01,$1B
  db $F0,$04,$2C,$01,$1B
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06A7::
  db $09
  db $E8,$F4,$2D,$01,$1B
  db $E8,$FC,$2E,$01,$1B
  db $E8,$04,$2F,$01,$1B
  db $F0,$F4,$30,$01,$1B
  db $F0,$FC,$31,$01,$1B
  db $F0,$04,$32,$01,$1B
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06A8::
  db $09
  db $E8,$F4,$33,$01,$1B
  db $E8,$FC,$34,$01,$1B
  db $E8,$04,$35,$01,$1B
  db $F0,$F4,$36,$01,$1B
  db $F0,$FC,$37,$01,$1B
  db $F0,$04,$38,$01,$1B
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06A9::
  db $09
  db $E8,$F4,$39,$01,$1B
  db $E8,$FC,$3A,$01,$1B
  db $E8,$04,$3B,$01,$1B
  db $F0,$F4,$3C,$01,$1B
  db $F0,$FC,$3D,$01,$1B
  db $F0,$04,$3E,$01,$1B
  db $F8,$F4,$12,$01,$1F
  db $F8,$FC,$13,$01,$1F
  db $F8,$04,$14,$01,$1F
Metasprite06AA::
  db $01
  db $FC,$00,$00,$01,$1E
Metasprite06AB::
  db $01
  db $FC,$F8,$00,$01,$1E
Metasprite06AC::
  db $04
  db $F8,$FE,$01,$01,$1E
  db $F8,$06,$02,$01,$1E
  db $00,$FE,$03,$01,$1E
  db $00,$06,$04,$01,$1E
Metasprite06AD::
  db $04
  db $F8,$F2,$01,$01,$1E
  db $F8,$FA,$02,$01,$1E
  db $00,$F2,$03,$01,$1E
  db $00,$FA,$04,$01,$1E
Metasprite06AE::
  db $04
  db $F8,$00,$05,$01,$1E
  db $F8,$08,$06,$01,$1E
  db $00,$00,$07,$01,$1E
  db $00,$08,$08,$01,$1E
Metasprite06AF::
  db $04
  db $F8,$F0,$05,$01,$1E
  db $F8,$F8,$06,$01,$1E
  db $00,$F0,$07,$01,$1E
  db $00,$F8,$08,$01,$1E
Metasprite06B0::
  db $09
  db $F4,$00,$09,$01,$1E
  db $F4,$08,$0A,$01,$1E
  db $F4,$10,$0B,$01,$1E
  db $FC,$00,$0C,$01,$1E
  db $FC,$08,$0D,$01,$1E
  db $FC,$10,$0E,$01,$1E
  db $04,$00,$0F,$01,$1E
  db $04,$08,$10,$01,$1E
  db $04,$10,$11,$01,$1E
Metasprite06B1::
  db $09
  db $F4,$E8,$09,$01,$1E
  db $F4,$F0,$0A,$01,$1E
  db $F4,$F8,$0B,$01,$1E
  db $FC,$E8,$0C,$01,$1E
  db $FC,$F0,$0D,$01,$1E
  db $FC,$F8,$0E,$01,$1E
  db $04,$E8,$0F,$01,$1E
  db $04,$F0,$10,$01,$1E
  db $04,$F8,$11,$01,$1E
Metasprite06B2::
  db $01
  db $FC,$FE,$2D,$01,$1A
Metasprite06B3::
  db $01
  db $FC,$FA,$2D,$01,$1A
Metasprite06B4::
  db $01
  db $FC,$FF,$2E,$01,$1A
Metasprite06B5::
  db $01
  db $FC,$F9,$2E,$01,$1A
Metasprite06B6::
  db $04
  db $F8,$FD,$2F,$01,$1A
  db $F8,$05,$30,$01,$1A
  db $00,$FD,$31,$01,$1A
  db $00,$05,$32,$01,$1A
Metasprite06B7::
  db $04
  db $F8,$F3,$2F,$01,$1A
  db $F8,$FB,$30,$01,$1A
  db $00,$F3,$31,$01,$1A
  db $00,$FB,$32,$01,$1A
Metasprite06B8::
  db $04
  db $F8,$00,$37,$01,$1A
  db $F8,$08,$38,$01,$1A
  db $00,$00,$39,$01,$1A
  db $00,$08,$3A,$01,$1A
Metasprite06B9::
  db $04
  db $F8,$F0,$37,$01,$1A
  db $F8,$F8,$38,$01,$1A
  db $00,$F0,$39,$01,$1A
  db $00,$F8,$3A,$01,$1A
Metasprite06BA::
  db $0D
  db $F4,$F4,$09,$01,$1E
  db $F4,$FC,$0A,$01,$1E
  db $F4,$04,$0B,$01,$1E
  db $FC,$F4,$0C,$01,$1E
  db $FC,$FC,$0D,$01,$1E
  db $FC,$04,$0E,$01,$1E
  db $04,$F4,$0F,$01,$1E
  db $04,$FC,$10,$01,$1E
  db $04,$04,$11,$01,$1E
  db $F8,$F8,$37,$01,$1A
  db $F8,$00,$38,$01,$1A
  db $00,$F8,$39,$01,$1A
  db $00,$00,$3A,$01,$1A
Metasprite06BB::
  db $0D
  db $F4,$F4,$12,$01,$1E
  db $F4,$FC,$13,$01,$1E
  db $F4,$04,$14,$01,$1E
  db $FC,$F4,$15,$01,$1E
  db $FC,$FC,$16,$01,$1E
  db $FC,$04,$17,$01,$1E
  db $04,$F4,$18,$01,$1E
  db $04,$FC,$19,$01,$1E
  db $04,$04,$1A,$01,$1E
  db $F8,$F8,$37,$01,$1A
  db $F8,$00,$38,$01,$1A
  db $00,$F8,$39,$01,$1A
  db $00,$00,$3A,$01,$1A
Metasprite06BC::
  db $0D
  db $F4,$F4,$1B,$01,$1E
  db $F4,$FC,$1C,$01,$1E
  db $F4,$04,$1D,$01,$1E
  db $FC,$F4,$1E,$01,$1E
  db $FC,$FC,$1F,$01,$1E
  db $FC,$04,$20,$01,$1E
  db $04,$F4,$21,$01,$1E
  db $04,$FC,$22,$01,$1E
  db $04,$04,$23,$01,$1E
  db $F8,$F8,$37,$01,$1A
  db $F8,$00,$38,$01,$1A
  db $00,$F8,$39,$01,$1A
  db $00,$00,$3A,$01,$1A
Metasprite06BD::
  db $0D
  db $F4,$F4,$24,$01,$1E
  db $F4,$FC,$25,$01,$1E
  db $F4,$04,$26,$01,$1E
  db $FC,$F4,$27,$01,$1E
  db $FC,$FC,$28,$01,$1E
  db $FC,$04,$29,$01,$1E
  db $04,$F4,$2A,$01,$1E
  db $04,$FC,$2B,$01,$1E
  db $04,$04,$2C,$01,$1E
  db $F8,$F8,$37,$01,$1A
  db $F8,$00,$38,$01,$1A
  db $00,$F8,$39,$01,$1A
  db $00,$00,$3A,$01,$1A
Metasprite06BE::
  db $04
  db $F8,$F8,$2F,$01,$1A
  db $F8,$00,$30,$01,$1A
  db $00,$F8,$31,$01,$1A
  db $00,$00,$32,$01,$1A
Metasprite06BF::
  db $04
  db $F8,$F8,$33,$01,$1A
  db $F8,$00,$34,$01,$1A
  db $00,$F8,$35,$01,$1A
  db $00,$00,$36,$01,$1A
Metasprite06C0::
  db $01
  db $FC,$FC,$2E,$01,$1A
Metasprite06C1::
  db $01
  db $FC,$FC,$2D,$01,$1A
Metasprite06C2::
  db $0F
  db $E8,$EC,$00,$01,$1C
  db $E8,$F4,$01,$01,$1C
  db $E8,$FC,$02,$01,$1C
  db $E8,$04,$03,$01,$1C
  db $E8,$0C,$04,$01,$1C
  db $F0,$EC,$05,$01,$1C
  db $F0,$F4,$06,$01,$1C
  db $F0,$FC,$07,$01,$1C
  db $F0,$04,$08,$01,$1C
  db $F0,$0C,$09,$01,$1C
  db $F8,$EC,$0A,$01,$1C
  db $F8,$F4,$0B,$01,$1C
  db $F8,$FC,$0C,$01,$1C
  db $F8,$04,$0D,$01,$1C
  db $F8,$0C,$0E,$01,$1C
Metasprite06C3::
  db $0F
  db $E8,$EC,$0F,$01,$1C
  db $E8,$F4,$10,$01,$1C
  db $E8,$FC,$11,$01,$1C
  db $E8,$04,$12,$01,$1C
  db $E8,$0C,$13,$01,$1C
  db $F0,$EC,$14,$01,$1C
  db $F0,$F4,$15,$01,$1C
  db $F0,$FC,$16,$01,$1C
  db $F0,$04,$17,$01,$1C
  db $F0,$0C,$18,$01,$1C
  db $F8,$EC,$19,$01,$1C
  db $F8,$F4,$1A,$01,$1C
  db $F8,$FC,$1B,$01,$1C
  db $F8,$04,$1C,$01,$1C
  db $F8,$0C,$1D,$01,$1C
Metasprite06C4::
  db $05
  db $00,$00,$00,$01,$18
  db $00,$08,$01,$01,$18
  db $08,$00,$02,$01,$18
  db $08,$08,$03,$01,$18
  db $F8,$00,$20,$01,$1A
Metasprite06C5::
  db $05
  db $00,$00,$01,$01,$38
  db $00,$08,$00,$01,$38
  db $08,$00,$03,$01,$38
  db $08,$08,$02,$01,$38
  db $F8,$08,$20,$01,$3A
Metasprite06C6::
  db $05
  db $00,$00,$04,$01,$18
  db $00,$08,$05,$01,$18
  db $08,$00,$06,$01,$18
  db $08,$08,$07,$01,$18
  db $F8,$00,$21,$01,$1A
Metasprite06C7::
  db $05
  db $00,$00,$05,$01,$38
  db $00,$08,$04,$01,$38
  db $08,$00,$07,$01,$38
  db $08,$08,$06,$01,$38
  db $F8,$08,$21,$01,$3A
Metasprite06C8::
  db $04
  db $00,$00,$08,$01,$1A
  db $00,$08,$09,$01,$1A
  db $08,$00,$0A,$01,$1A
  db $08,$08,$0B,$01,$1A
Metasprite06C9::
  db $04
  db $00,$00,$0C,$01,$1A
  db $00,$08,$0D,$01,$1A
  db $08,$00,$0E,$01,$1A
  db $08,$08,$0F,$01,$1A
MetaspriteTable06End::
