; Autogenerated by ./scripts/dump_metasprites.py

SECTION "Metasprite Table 04", ROMX[$4000], BANK[$30]
MetaspriteTable04::
  dw Metasprite0400
  dw Metasprite0401
  dw Metasprite0402
  dw Metasprite0403
  dw Metasprite0404
  dw Metasprite0405
  dw Metasprite0406
  dw Metasprite0407
  dw Metasprite0408
  dw Metasprite0409
  dw Metasprite040A
  dw Metasprite040B
  dw Metasprite040C
  dw Metasprite040D
  dw Metasprite040D
  dw Metasprite040D
  dw Metasprite040D
  dw Metasprite0411
  dw Metasprite0412
  dw Metasprite0413
  dw Metasprite0414
  dw Metasprite0415
  dw Metasprite0416
  dw Metasprite0417
  dw Metasprite0418
  dw Metasprite0419
  dw Metasprite041A
  dw Metasprite041B
  dw Metasprite041C
  dw Metasprite041D
  dw Metasprite041E
  dw Metasprite041F
  dw Metasprite0420
  dw Metasprite0421
  dw Metasprite0422
  dw Metasprite0423
  dw Metasprite0424
  dw Metasprite0425
  dw Metasprite0426
  dw Metasprite0427
  dw Metasprite0428
  dw Metasprite0429
  dw Metasprite042A
  dw Metasprite042B
  dw Metasprite042C
  dw Metasprite042C
  dw Metasprite042C
  dw Metasprite042C
  dw Metasprite042C
  dw Metasprite0431
  dw Metasprite0432
  dw Metasprite0433
  dw Metasprite0434
  dw Metasprite0435
  dw Metasprite0436
  dw Metasprite0437
  dw Metasprite0438
  dw Metasprite0439
  dw Metasprite043A
  dw Metasprite043B
  dw Metasprite043C
  dw Metasprite043D
  dw Metasprite043E
  dw Metasprite043F
  dw Metasprite0440
  dw Metasprite0441
  dw Metasprite0442
  dw Metasprite0443
  dw Metasprite0444
  dw Metasprite0445
  dw Metasprite0446
  dw Metasprite0447
  dw Metasprite0448
  dw Metasprite0449
  dw Metasprite044A
  dw Metasprite044B
  dw Metasprite044C
  dw Metasprite044D
  dw Metasprite044D
  dw Metasprite044D
  dw Metasprite044D
  dw Metasprite044D
  dw Metasprite044D
  dw Metasprite0453
  dw Metasprite0454
  dw Metasprite0455
  dw Metasprite0456
  dw Metasprite0457
  dw Metasprite0458
  dw Metasprite0459
  dw Metasprite045A
  dw Metasprite045B
  dw Metasprite045C
  dw Metasprite045C
  dw Metasprite045C
  dw Metasprite045C
  dw Metasprite045C
  dw Metasprite0461
  dw Metasprite0462
  dw Metasprite0463
  dw Metasprite0464
  dw Metasprite0465
  dw Metasprite0466
  dw Metasprite0467
  dw Metasprite0468
  dw Metasprite0469
  dw Metasprite046A
  dw Metasprite046B
  dw Metasprite046C
  dw Metasprite046D
  dw Metasprite046E
  dw Metasprite046F
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0470
  dw Metasprite0481
  dw Metasprite0482
  dw Metasprite0483
  dw Metasprite0484
  dw Metasprite0485
  dw Metasprite0486
  dw Metasprite0487
  dw Metasprite0488
  dw Metasprite0489
  dw Metasprite048A
  dw Metasprite048B
  dw Metasprite048C
  dw Metasprite048D
  dw Metasprite048E
  dw Metasprite048F
  dw Metasprite0490
  dw Metasprite0491
  dw Metasprite0492
  dw Metasprite0493
  dw Metasprite0494
  dw Metasprite0495
  dw Metasprite0496
  dw Metasprite0497
  dw Metasprite0498
  dw Metasprite0499
  dw Metasprite049A
  dw Metasprite049B
  dw Metasprite049C
  dw Metasprite049D
  dw Metasprite049E
  dw Metasprite049F
  dw Metasprite04A0
  dw Metasprite04A1
  dw Metasprite04A2
  dw Metasprite04A3
  dw Metasprite04A4
  dw Metasprite04A5
  dw Metasprite04A6
  dw Metasprite04A7
  dw Metasprite04A8
  dw Metasprite04A9
  dw Metasprite04AA
  dw Metasprite04AB
  dw Metasprite04AC
  dw Metasprite04AC
  dw Metasprite04AC
  dw Metasprite04AC
  dw Metasprite04AC
  dw Metasprite04B1
  dw Metasprite04B2
  dw Metasprite04B3
  dw Metasprite04B4
  dw Metasprite04B5
  dw Metasprite04B6
  dw Metasprite04B7
  dw Metasprite04B8
  dw Metasprite04B9
  dw Metasprite04BA
  dw Metasprite04BB
  dw Metasprite04BC
  dw Metasprite04BD
  dw Metasprite04BE
  dw Metasprite04BF
  dw Metasprite04C0
  dw Metasprite04C1
  dw Metasprite04C2
  dw Metasprite04C3
  dw Metasprite04C4
  dw Metasprite04C5
  dw Metasprite04C6
  dw Metasprite04C7
  dw Metasprite04C8
  dw Metasprite04C9
  dw Metasprite04CA
  dw Metasprite04CB
  dw Metasprite04CC
  dw Metasprite04CD
  dw Metasprite04CE
  dw Metasprite04CF
  dw Metasprite04D0
  dw Metasprite04D1
  dw Metasprite04D2
  dw Metasprite04D3
  dw Metasprite04D4
  dw Metasprite04D5
  dw Metasprite04D6
  dw Metasprite04D7
  dw Metasprite04D8
  dw Metasprite04D9
  dw Metasprite04DA
  dw Metasprite04DB
  dw Metasprite04DC
  dw Metasprite04DD
  dw Metasprite04DE
  dw Metasprite04DF
  dw Metasprite04DF
  dw Metasprite04E1
  dw Metasprite04E2
  dw Metasprite04E3
  dw Metasprite04E4
  dw Metasprite04E5
  dw Metasprite04E6
  dw Metasprite04E7
  dw Metasprite04E8
  dw Metasprite04E9
  dw Metasprite04EA
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
  dw MetaspriteTable04End
Metasprite0400::
  db $04
  db $00,$00,$38,$00,$10
  db $00,$08,$39,$00,$10
  db $08,$00,$3A,$00,$10
  db $08,$08,$3B,$00,$10
Metasprite0401::
  db $04
  db $00,$00,$3C,$00,$10
  db $00,$08,$3D,$00,$10
  db $08,$00,$3E,$00,$10
  db $08,$08,$3F,$00,$10
Metasprite0402::
  db $04
  db $00,$00,$40,$00,$10
  db $00,$08,$41,$00,$10
  db $08,$00,$42,$00,$10
  db $08,$08,$43,$00,$10
Metasprite0403::
  db $04
  db $00,$00,$44,$00,$10
  db $00,$08,$45,$00,$10
  db $08,$00,$46,$00,$10
  db $08,$08,$47,$00,$10
Metasprite0404::
  db $01
  db $00,$00,$FA,$01,$1E
Metasprite0405::
  db $01
  db $00,$00,$FB,$01,$1E
Metasprite0406::
  db $01
  db $00,$00,$FA,$01,$3E
Metasprite0407::
  db $01
  db $00,$00,$FB,$01,$3E
Metasprite0408::
  db $04
  db $00,$00,$30,$00,$10
  db $00,$08,$31,$00,$10
  db $08,$00,$32,$00,$10
  db $08,$08,$33,$00,$10
Metasprite0409::
  db $04
  db $00,$00,$34,$00,$10
  db $00,$08,$35,$00,$10
  db $08,$00,$36,$00,$10
  db $08,$08,$37,$00,$10
Metasprite040A::
  db $04
  db $00,$00,$00,$00,$10
  db $00,$08,$01,$00,$10
  db $08,$00,$02,$00,$10
  db $08,$08,$03,$00,$10
Metasprite040B::
  db $04
  db $00,$00,$04,$00,$10
  db $00,$08,$05,$00,$10
  db $08,$00,$06,$00,$10
  db $08,$08,$07,$00,$10
Metasprite040C::
  db $04
  db $00,$00,$08,$00,$10
  db $00,$08,$09,$00,$10
  db $08,$00,$0A,$00,$10
  db $08,$08,$0B,$00,$10
Metasprite040D::
  db $04
  db $00,$00,$48,$00,$10
  db $00,$08,$49,$00,$10
  db $08,$00,$4A,$00,$10
  db $08,$08,$4B,$00,$10
Metasprite0411::
  db $04
  db $00,$00,$4C,$00,$10
  db $00,$08,$4D,$00,$10
  db $08,$00,$4E,$00,$10
  db $08,$08,$4F,$00,$10
Metasprite0412::
  db $04
  db $00,$00,$49,$00,$30
  db $00,$08,$48,$00,$30
  db $08,$00,$4B,$00,$30
  db $08,$08,$4A,$00,$30
Metasprite0413::
  db $04
  db $00,$00,$4D,$00,$30
  db $00,$08,$4C,$00,$30
  db $08,$00,$4F,$00,$30
  db $08,$08,$4E,$00,$30
Metasprite0414::
  db $04
  db $00,$00,$50,$00,$10
  db $00,$08,$51,$00,$10
  db $08,$00,$52,$00,$10
  db $08,$08,$53,$00,$10
Metasprite0415::
  db $04
  db $00,$00,$54,$00,$10
  db $00,$08,$55,$00,$10
  db $08,$00,$56,$00,$10
  db $08,$08,$57,$00,$10
Metasprite0416::
  db $04
  db $00,$00,$51,$00,$30
  db $00,$08,$50,$00,$30
  db $08,$00,$53,$00,$30
  db $08,$08,$52,$00,$30
Metasprite0417::
  db $04
  db $00,$00,$55,$00,$30
  db $00,$08,$54,$00,$30
  db $08,$00,$57,$00,$30
  db $08,$08,$56,$00,$30
Metasprite0418::
  db $04
  db $00,$00,$58,$00,$10
  db $00,$08,$59,$00,$10
  db $08,$00,$5A,$00,$10
  db $08,$08,$5B,$00,$10
Metasprite0419::
  db $04
  db $00,$00,$5C,$00,$10
  db $00,$08,$5D,$00,$10
  db $08,$00,$5E,$00,$10
  db $08,$08,$5F,$00,$10
Metasprite041A::
  db $04
  db $00,$00,$59,$00,$30
  db $00,$08,$58,$00,$30
  db $08,$00,$5B,$00,$30
  db $08,$08,$5A,$00,$30
Metasprite041B::
  db $04
  db $00,$00,$5D,$00,$30
  db $00,$08,$5C,$00,$30
  db $08,$00,$5F,$00,$30
  db $08,$08,$5E,$00,$30
Metasprite041C::
  db $04
  db $00,$00,$60,$00,$10
  db $00,$08,$61,$00,$10
  db $08,$00,$62,$00,$10
  db $08,$08,$63,$00,$10
Metasprite041D::
  db $04
  db $00,$00,$64,$00,$10
  db $00,$08,$65,$00,$10
  db $08,$00,$66,$00,$10
  db $08,$08,$67,$00,$10
Metasprite041E::
  db $04
  db $00,$00,$61,$00,$30
  db $00,$08,$60,$00,$30
  db $08,$00,$63,$00,$30
  db $08,$08,$62,$00,$30
Metasprite041F::
  db $04
  db $00,$00,$65,$00,$30
  db $00,$08,$64,$00,$30
  db $08,$00,$67,$00,$30
  db $08,$08,$66,$00,$30
Metasprite0420::
  db $04
  db $00,$00,$68,$00,$10
  db $00,$08,$69,$00,$10
  db $08,$00,$6A,$00,$10
  db $08,$08,$6B,$00,$10
Metasprite0421::
  db $04
  db $00,$00,$6C,$00,$10
  db $00,$08,$6D,$00,$10
  db $08,$00,$6E,$00,$10
  db $08,$08,$6F,$00,$10
Metasprite0422::
  db $04
  db $00,$00,$69,$00,$30
  db $00,$08,$68,$00,$30
  db $08,$00,$6B,$00,$30
  db $08,$08,$6A,$00,$30
Metasprite0423::
  db $04
  db $00,$00,$6D,$00,$30
  db $00,$08,$6C,$00,$30
  db $08,$00,$6F,$00,$30
  db $08,$08,$6E,$00,$30
Metasprite0424::
  db $04
  db $00,$00,$70,$00,$10
  db $00,$08,$71,$00,$10
  db $08,$00,$72,$00,$10
  db $08,$08,$73,$00,$10
Metasprite0425::
  db $04
  db $00,$00,$74,$00,$10
  db $00,$08,$75,$00,$10
  db $08,$00,$76,$00,$10
  db $08,$08,$77,$00,$10
Metasprite0426::
  db $04
  db $00,$00,$71,$00,$10
  db $00,$08,$70,$00,$10
  db $08,$00,$73,$00,$10
  db $08,$08,$72,$00,$10
Metasprite0427::
  db $04
  db $00,$00,$75,$00,$10
  db $00,$08,$74,$00,$10
  db $08,$00,$77,$00,$10
  db $08,$08,$76,$00,$10
Metasprite0428::
  db $04
  db $00,$00,$78,$00,$10
  db $00,$08,$79,$00,$10
  db $08,$00,$7A,$00,$10
  db $08,$08,$7B,$00,$10
Metasprite0429::
  db $04
  db $00,$00,$7C,$00,$10
  db $00,$08,$7D,$00,$10
  db $08,$00,$7E,$00,$10
  db $08,$08,$7F,$00,$10
Metasprite042A::
  db $04
  db $00,$00,$79,$00,$30
  db $00,$08,$78,$00,$30
  db $08,$00,$7B,$00,$30
  db $08,$08,$7A,$00,$30
Metasprite042B::
  db $04
  db $00,$00,$7D,$00,$30
  db $00,$08,$7C,$00,$30
  db $08,$00,$7F,$00,$30
  db $08,$08,$7E,$00,$30
Metasprite042C::
  db $04
  db $00,$00,$10,$00,$10
  db $00,$08,$11,$00,$10
  db $08,$00,$12,$00,$10
  db $08,$08,$13,$00,$10
Metasprite0431::
  db $04
  db $00,$00,$11,$00,$10
  db $00,$08,$10,$00,$10
  db $08,$00,$13,$00,$10
  db $08,$08,$12,$00,$10
Metasprite0432::
  db $04
  db $00,$00,$14,$01,$11
  db $00,$08,$15,$01,$11
  db $08,$00,$16,$01,$11
  db $08,$08,$17,$01,$11
Metasprite0433::
  db $04
  db $00,$00,$14,$01,$15
  db $00,$08,$15,$01,$15
  db $08,$00,$16,$01,$15
  db $08,$08,$17,$01,$15
Metasprite0434::
  db $04
  db $F8,$F8,$18,$01,$14
  db $F8,$00,$19,$01,$14
  db $00,$F8,$1A,$01,$14
  db $00,$00,$1B,$01,$14
Metasprite0435::
  db $04
  db $F8,$F8,$1C,$01,$14
  db $F8,$00,$1D,$01,$14
  db $00,$F8,$1E,$01,$14
  db $00,$00,$1F,$01,$14
Metasprite0436::
  db $09
  db $F4,$F4,$20,$01,$14
  db $F4,$FC,$21,$01,$14
  db $F4,$04,$22,$01,$14
  db $FC,$F4,$23,$01,$14
  db $FC,$FC,$24,$01,$14
  db $FC,$04,$25,$01,$14
  db $04,$F4,$26,$01,$14
  db $04,$FC,$27,$01,$14
  db $04,$04,$28,$01,$14
Metasprite0437::
  db $04
  db $00,$00,$29,$01,$17
  db $00,$08,$2A,$01,$17
  db $00,$10,$2B,$01,$17
Metasprite0438::
  db $01
  db $00,$00,$2C,$02,$10
Metasprite0439::
  db $01
  db $00,$00,$2D,$02,$10
Metasprite043A::
  db $01
  db $00,$00,$2E,$02,$10
Metasprite043B::
  db $01
  db $00,$00,$2F,$02,$10
Metasprite043C::
  db $01
  db $00,$00,$30,$02,$10
Metasprite043D::
  db $01
  db $00,$00,$31,$02,$10
Metasprite043E::
  db $01
  db $00,$00,$32,$02,$10
Metasprite043F::
  db $01
  db $00,$00,$33,$02,$10
Metasprite0440::
  db $01
  db $00,$00,$34,$02,$10
Metasprite0441::
  db $01
  db $00,$00,$35,$02,$10
Metasprite0442::
  db $01
  db $00,$00,$36,$02,$10
Metasprite0443::
  db $01
  db $00,$00,$37,$02,$10
Metasprite0444::
  db $01
  db $00,$00,$00,$01,$15
Metasprite0445::
  db $01
  db $00,$00,$01,$01,$15
Metasprite0446::
  db $01
  db $00,$00,$02,$01,$15
Metasprite0447::
  db $0C
  db $00,$00,$03,$01,$15
  db $00,$08,$04,$01,$15
  db $00,$10,$05,$01,$15
  db $00,$18,$06,$01,$15
  db $00,$20,$07,$01,$15
  db $00,$28,$08,$01,$15
  db $08,$00,$09,$01,$15
  db $08,$08,$0A,$01,$15
  db $08,$10,$0B,$01,$15
  db $08,$18,$0C,$01,$15
  db $08,$20,$0D,$01,$15
  db $08,$28,$0E,$01,$15
Metasprite0448::
  db $0C
  db $00,$01,$03,$01,$15
  db $00,$09,$04,$01,$15
  db $00,$11,$05,$01,$15
  db $00,$19,$06,$01,$15
  db $00,$21,$07,$01,$15
  db $00,$29,$08,$01,$15
  db $08,$01,$09,$01,$15
  db $08,$09,$0A,$01,$15
  db $08,$11,$0B,$01,$15
  db $08,$19,$0C,$01,$15
  db $08,$21,$0D,$01,$15
  db $08,$29,$0E,$01,$15
Metasprite0449::
  db $0C
  db $00,$02,$03,$01,$15
  db $00,$0A,$04,$01,$15
  db $00,$12,$05,$01,$15
  db $00,$1A,$06,$01,$15
  db $00,$22,$07,$01,$15
  db $00,$2A,$08,$01,$15
  db $08,$02,$09,$01,$15
  db $08,$0A,$0A,$01,$15
  db $08,$12,$0B,$01,$15
  db $08,$1A,$0C,$01,$15
  db $08,$22,$0D,$01,$15
  db $08,$2A,$0E,$01,$15
Metasprite044A::
  db $01
  db $FC,$FC,$0F,$01,$12
Metasprite044B::
  db $04
  db $F8,$F8,$10,$01,$12
  db $F8,$00,$11,$01,$12
  db $00,$F8,$12,$01,$12
  db $00,$00,$13,$01,$12
Metasprite044C::
  db $09
  db $F4,$F4,$14,$01,$12
  db $F4,$FC,$15,$01,$12
  db $F4,$04,$16,$01,$12
  db $FC,$F4,$17,$01,$12
  db $FC,$FC,$18,$01,$12
  db $FC,$04,$19,$01,$12
  db $04,$F4,$1A,$01,$12
  db $04,$FC,$1B,$01,$12
  db $04,$04,$1C,$01,$12
Metasprite044D::
  db $04
  db $F8,$F8,$46,$01,$16
  db $F8,$10,$46,$01,$36
  db $10,$F8,$46,$01,$56
  db $10,$10,$46,$01,$76
Metasprite0453::
  db $04
  db $FA,$FA,$46,$01,$16
  db $FA,$0E,$46,$01,$36
  db $0E,$FA,$46,$01,$56
  db $0E,$0E,$46,$01,$76
Metasprite0454::
  db $04
  db $FC,$FC,$46,$01,$16
  db $FC,$0C,$46,$01,$36
  db $0C,$FC,$46,$01,$56
  db $0C,$0C,$46,$01,$76
Metasprite0455::
  db $04
  db $FE,$FE,$46,$01,$16
  db $FE,$0A,$46,$01,$36
  db $0A,$FE,$46,$01,$56
  db $0A,$0A,$46,$01,$76
Metasprite0456::
  db $04
  db $00,$00,$46,$01,$16
  db $00,$08,$46,$01,$36
  db $08,$00,$46,$01,$56
  db $08,$08,$46,$01,$76
Metasprite0457::
  db $01
  db $00,$00,$F6,$01,$12
Metasprite0458::
  db $01
  db $00,$00,$F7,$01,$12
Metasprite0459::
  db $01
  db $00,$00,$F7,$01,$32
Metasprite045A::
  db $02
  db $FF,$00,$F8,$01,$10
  db $FF,$08,$F9,$01,$10
Metasprite045B::
  db $01
  db $FE,$04,$FA,$01,$16
Metasprite045C::
  db $01
  db $00,$00,$3E,$01,$16
Metasprite0461::
  db $01
  db $00,$00,$3B,$01,$15
Metasprite0462::
  db $01
  db $00,$00,$3D,$01,$10
Metasprite0463::
  db $01
  db $00,$00,$3F,$01,$12
Metasprite0464::
  db $01
  db $00,$00,$40,$01,$16
Metasprite0465::
  db $01
  db $00,$00,$38,$01,$11
Metasprite0466::
  db $01
  db $00,$00,$3C,$01,$10
Metasprite0467::
  db $01
  db $00,$00,$39,$01,$11
Metasprite0468::
  db $01
  db $00,$00,$3A,$01,$10
Metasprite0469::
  db $01
  db $00,$00,$3B,$01,$13
Metasprite046A::
  db $01
  db $00,$00,$3C,$01,$11
Metasprite046B::
  db $01
  db $00,$00,$41,$01,$17
Metasprite046C::
  db $01
  db $00,$00,$42,$01,$12
Metasprite046D::
  db $01
  db $00,$00,$44,$01,$10
Metasprite046E::
  db $01
  db $00,$00,$43,$01,$11
Metasprite046F::
  db $01
  db $00,$00,$45,$01,$14
Metasprite0470::
  db $04
  db $00,$00,$00,$02,$18
  db $00,$08,$01,$02,$18
  db $08,$00,$02,$02,$18
  db $08,$08,$03,$02,$18
Metasprite0481::
  db $04
  db $00,$00,$01,$02,$38
  db $00,$08,$00,$02,$38
  db $08,$00,$03,$02,$38
  db $08,$08,$02,$02,$38
Metasprite0482::
  db $04
  db $00,$00,$04,$02,$18
  db $00,$08,$05,$02,$18
  db $08,$00,$06,$02,$18
  db $08,$08,$07,$02,$18
Metasprite0483::
  db $04
  db $00,$00,$05,$02,$38
  db $00,$08,$04,$02,$38
  db $08,$00,$07,$02,$38
  db $08,$08,$06,$02,$38
Metasprite0484::
  db $04
  db $00,$00,$08,$02,$18
  db $00,$08,$09,$02,$18
  db $08,$00,$0A,$02,$18
  db $08,$08,$0B,$02,$18
Metasprite0485::
  db $04
  db $00,$00,$09,$02,$38
  db $00,$08,$08,$02,$38
  db $08,$00,$0B,$02,$38
  db $08,$08,$0A,$02,$38
Metasprite0486::
  db $04
  db $00,$00,$0C,$02,$18
  db $00,$08,$0D,$02,$18
  db $08,$00,$0E,$02,$18
  db $08,$08,$0F,$02,$18
Metasprite0487::
  db $04
  db $00,$00,$0D,$02,$38
  db $00,$08,$0C,$02,$38
  db $08,$00,$0F,$02,$38
  db $08,$08,$0E,$02,$38
Metasprite0488::
  db $04
  db $00,$00,$10,$02,$18
  db $00,$08,$11,$02,$18
  db $08,$00,$12,$02,$18
  db $08,$08,$13,$02,$18
Metasprite0489::
  db $04
  db $00,$00,$11,$02,$38
  db $00,$08,$10,$02,$38
  db $08,$00,$13,$02,$38
  db $08,$08,$12,$02,$38
Metasprite048A::
  db $04
  db $00,$00,$14,$02,$18
  db $00,$08,$15,$02,$18
  db $08,$00,$16,$02,$18
  db $08,$08,$17,$02,$18
Metasprite048B::
  db $04
  db $00,$00,$15,$02,$38
  db $00,$08,$14,$02,$38
  db $08,$00,$17,$02,$38
  db $08,$08,$16,$02,$38
Metasprite048C::
  db $04
  db $00,$00,$18,$02,$18
  db $00,$08,$19,$02,$18
  db $08,$00,$1A,$02,$18
  db $08,$08,$1B,$02,$18
Metasprite048D::
  db $04
  db $00,$00,$19,$02,$38
  db $00,$08,$18,$02,$38
  db $08,$00,$1B,$02,$38
  db $08,$08,$1A,$02,$38
Metasprite048E::
  db $04
  db $00,$00,$1C,$02,$18
  db $00,$08,$1D,$02,$18
  db $08,$00,$1E,$02,$18
  db $08,$08,$1F,$02,$18
Metasprite048F::
  db $04
  db $00,$00,$1D,$02,$38
  db $00,$08,$1C,$02,$38
  db $08,$00,$1F,$02,$38
  db $08,$08,$1E,$02,$38
Metasprite0490::
  db $04
  db $00,$00,$20,$02,$18
  db $00,$08,$21,$02,$18
  db $08,$00,$22,$02,$18
  db $08,$08,$23,$02,$18
Metasprite0491::
  db $04
  db $00,$00,$21,$02,$38
  db $00,$08,$20,$02,$38
  db $08,$00,$23,$02,$38
  db $08,$08,$22,$02,$38
Metasprite0492::
  db $04
  db $00,$00,$24,$02,$18
  db $00,$08,$25,$02,$18
  db $08,$00,$26,$02,$18
  db $08,$08,$27,$02,$18
Metasprite0493::
  db $04
  db $00,$00,$25,$02,$38
  db $00,$08,$24,$02,$38
  db $08,$00,$27,$02,$38
  db $08,$08,$26,$02,$38
Metasprite0494::
  db $04
  db $00,$00,$28,$02,$18
  db $00,$08,$29,$02,$18
  db $08,$00,$2A,$02,$18
  db $08,$08,$2B,$02,$18
Metasprite0495::
  db $04
  db $00,$00,$29,$02,$38
  db $00,$08,$28,$02,$38
  db $08,$00,$2B,$02,$38
  db $08,$08,$2A,$02,$38
Metasprite0496::
  db $04
  db $00,$00,$2C,$02,$18
  db $00,$08,$2D,$02,$18
  db $08,$00,$2E,$02,$18
  db $08,$08,$2F,$02,$18
Metasprite0497::
  db $04
  db $00,$00,$2D,$02,$38
  db $00,$08,$2C,$02,$38
  db $08,$00,$2F,$02,$38
  db $08,$08,$2E,$02,$38
Metasprite0498::
  db $04
  db $00,$00,$30,$02,$18
  db $00,$08,$31,$02,$18
  db $08,$00,$32,$02,$18
  db $08,$08,$33,$02,$18
Metasprite0499::
  db $04
  db $00,$00,$31,$02,$38
  db $00,$08,$30,$02,$38
  db $08,$00,$33,$02,$38
  db $08,$08,$32,$02,$38
Metasprite049A::
  db $04
  db $00,$00,$34,$02,$18
  db $00,$08,$35,$02,$18
  db $08,$00,$36,$02,$18
  db $08,$08,$37,$02,$18
Metasprite049B::
  db $04
  db $00,$00,$35,$02,$38
  db $00,$08,$34,$02,$38
  db $08,$00,$37,$02,$38
  db $08,$08,$36,$02,$38
Metasprite049C::
  db $04
  db $00,$00,$38,$02,$18
  db $00,$08,$39,$02,$18
  db $08,$00,$3A,$02,$18
  db $08,$08,$3B,$02,$18
Metasprite049D::
  db $04
  db $00,$00,$39,$02,$38
  db $00,$08,$38,$02,$38
  db $08,$00,$3B,$02,$38
  db $08,$08,$3A,$02,$38
Metasprite049E::
  db $04
  db $00,$00,$3C,$02,$18
  db $00,$08,$3D,$02,$18
  db $08,$00,$3E,$02,$18
  db $08,$08,$3F,$02,$18
Metasprite049F::
  db $04
  db $00,$00,$3D,$02,$38
  db $00,$08,$3C,$02,$38
  db $08,$00,$3F,$02,$38
  db $08,$08,$3E,$02,$38
Metasprite04A0::
  db $01
  db $FC,$FC,$40,$02,$18
Metasprite04A1::
  db $01
  db $FC,$FC,$40,$02,$38
Metasprite04A2::
  db $01
  db $FC,$FC,$41,$02,$18
Metasprite04A3::
  db $01
  db $FC,$FC,$41,$02,$38
Metasprite04A4::
  db $01
  db $FC,$FC,$42,$02,$18
Metasprite04A5::
  db $01
  db $FC,$FC,$42,$02,$38
Metasprite04A6::
  db $01
  db $FC,$FC,$43,$02,$18
Metasprite04A7::
  db $01
  db $FC,$FC,$43,$02,$38
Metasprite04A8::
  db $01
  db $FC,$FC,$44,$02,$18
Metasprite04A9::
  db $01
  db $FC,$FC,$44,$02,$38
Metasprite04AA::
  db $01
  db $FC,$FC,$45,$02,$18
Metasprite04AB::
  db $01
  db $FC,$FC,$45,$02,$38
Metasprite04AC::
  db $04
  db $F8,$F8,$18,$02,$10
  db $F8,$00,$19,$02,$10
  db $00,$F8,$1A,$02,$10
  db $00,$00,$1B,$02,$10
Metasprite04B1::
  db $04
  db $F8,$F8,$1C,$02,$10
  db $F8,$00,$1D,$02,$10
  db $00,$F8,$1E,$02,$10
  db $00,$00,$1F,$02,$10
Metasprite04B2::
  db $09
  db $F4,$F4,$20,$02,$10
  db $F4,$FC,$21,$02,$10
  db $F4,$04,$22,$02,$10
  db $FC,$F4,$23,$02,$10
  db $FC,$FC,$24,$02,$10
  db $FC,$04,$25,$02,$10
  db $04,$F4,$26,$02,$10
  db $04,$FC,$27,$02,$10
  db $04,$04,$28,$02,$10
Metasprite04B3::
  db $09
  db $F4,$F4,$00,$02,$18
  db $F4,$FC,$01,$02,$18
  db $F4,$04,$02,$02,$18
  db $FC,$F4,$03,$02,$18
  db $FC,$FC,$04,$02,$18
  db $FC,$04,$05,$02,$18
  db $04,$F4,$06,$02,$18
  db $04,$FC,$07,$02,$18
  db $04,$04,$08,$02,$18
Metasprite04B4::
  db $09
  db $F4,$F4,$09,$02,$18
  db $F4,$FC,$0A,$02,$18
  db $F4,$04,$0B,$02,$18
  db $FC,$F4,$0C,$02,$18
  db $FC,$FC,$0D,$02,$18
  db $FC,$04,$0E,$02,$18
  db $04,$F4,$0F,$02,$18
  db $04,$FC,$10,$02,$18
  db $04,$04,$11,$02,$18
Metasprite04B5::
  db $10
  db $F0,$F0,$12,$02,$18
  db $F0,$F8,$13,$02,$18
  db $F0,$00,$14,$02,$18
  db $F0,$08,$15,$02,$18
  db $F8,$F0,$16,$02,$18
  db $F8,$F8,$17,$02,$18
  db $F8,$00,$18,$02,$18
  db $F8,$08,$19,$02,$18
  db $00,$F0,$1A,$02,$18
  db $00,$F8,$1B,$02,$18
  db $00,$00,$1C,$02,$18
  db $00,$08,$1D,$02,$18
  db $08,$F0,$1E,$02,$18
  db $08,$F8,$1F,$02,$18
  db $08,$00,$20,$02,$18
  db $08,$08,$21,$02,$18
Metasprite04B6::
  db $19
  db $EC,$EC,$22,$02,$18
  db $EC,$F4,$23,$02,$18
  db $EC,$FC,$24,$02,$18
  db $EC,$04,$25,$02,$18
  db $EC,$0C,$26,$02,$18
  db $F4,$EC,$27,$02,$18
  db $F4,$F4,$28,$02,$18
  db $F4,$FC,$29,$02,$18
  db $F4,$04,$2A,$02,$18
  db $F4,$0C,$2B,$02,$18
  db $FC,$EC,$2C,$02,$18
  db $FC,$F4,$2D,$02,$18
  db $FC,$FC,$2E,$02,$18
  db $FC,$04,$2F,$02,$18
  db $FC,$0C,$30,$02,$18
  db $04,$EC,$31,$02,$18
  db $04,$F4,$32,$02,$18
  db $04,$FC,$33,$02,$18
  db $04,$04,$34,$02,$18
  db $04,$0C,$35,$02,$18
  db $0C,$EC,$36,$02,$18
  db $0C,$F4,$37,$02,$18
  db $0C,$FC,$38,$02,$18
  db $0C,$04,$39,$02,$18
  db $0C,$0C,$3A,$02,$18
Metasprite04B7::
  db $10
  db $F0,$F0,$50,$02,$18
  db $F0,$F8,$51,$02,$18
  db $F0,$00,$52,$02,$18
  db $F0,$08,$53,$02,$18
  db $F8,$F0,$54,$02,$18
  db $F8,$F8,$55,$02,$18
  db $F8,$00,$56,$02,$18
  db $F8,$08,$57,$02,$18
  db $00,$F0,$58,$02,$18
  db $00,$F8,$59,$02,$18
  db $00,$00,$5A,$02,$18
  db $00,$08,$5B,$02,$18
  db $08,$F0,$5C,$02,$18
  db $08,$F8,$5D,$02,$18
  db $08,$00,$5E,$02,$18
  db $08,$08,$5F,$02,$18
Metasprite04B8::
  db $10
  db $F0,$F0,$53,$02,$38
  db $F0,$F8,$52,$02,$38
  db $F0,$00,$51,$02,$38
  db $F0,$08,$50,$02,$38
  db $F8,$F0,$57,$02,$38
  db $F8,$F8,$56,$02,$38
  db $F8,$00,$55,$02,$38
  db $F8,$08,$54,$02,$38
  db $00,$F0,$5B,$02,$38
  db $00,$F8,$5A,$02,$38
  db $00,$00,$59,$02,$38
  db $00,$08,$58,$02,$38
  db $08,$F0,$5F,$02,$38
  db $08,$F8,$5E,$02,$38
  db $08,$00,$5D,$02,$38
  db $08,$08,$5C,$02,$38
Metasprite04B9::
  db $04
  db $00,$00,$7C,$02,$18
  db $00,$08,$7D,$02,$18
  db $08,$00,$7E,$02,$18
  db $08,$08,$7F,$02,$18
Metasprite04BA::
  db $02
  db $F8,$00,$49,$01,$1F
  db $00,$00,$4A,$01,$1F
Metasprite04BB::
  db $02
  db $F8,$00,$4B,$01,$1F
  db $00,$00,$4C,$01,$1F
Metasprite04BC::
  db $02
  db $F8,$00,$4D,$01,$1F
  db $00,$00,$4E,$01,$1F
Metasprite04BD::
  db $04
  db $00,$F8,$60,$01,$18
  db $00,$00,$61,$01,$18
  db $00,$08,$63,$01,$18
  db $00,$10,$64,$01,$18
Metasprite04BE::
  db $01
  db $F8,$08,$00,$02,$1E
Metasprite04BF::
  db $02
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
Metasprite04C0::
  db $03
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
Metasprite04C1::
  db $04
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
Metasprite04C2::
  db $05
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
Metasprite04C3::
  db $06
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
  db $10,$08,$00,$02,$5E
Metasprite04C4::
  db $07
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
  db $10,$08,$00,$02,$5E
  db $10,$00,$00,$02,$7E
Metasprite04C5::
  db $08
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
  db $10,$08,$00,$02,$5E
  db $10,$00,$00,$02,$7E
  db $10,$F8,$01,$02,$7E
Metasprite04C6::
  db $09
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
  db $10,$08,$00,$02,$5E
  db $10,$00,$00,$02,$7E
  db $10,$F8,$01,$02,$7E
  db $08,$F8,$02,$02,$7E
Metasprite04C7::
  db $0A
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
  db $10,$08,$00,$02,$5E
  db $10,$00,$00,$02,$7E
  db $10,$F8,$01,$02,$7E
  db $08,$F8,$02,$02,$7E
  db $00,$F8,$02,$02,$3E
Metasprite04C8::
  db $0B
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
  db $10,$08,$00,$02,$5E
  db $10,$00,$00,$02,$7E
  db $10,$F8,$01,$02,$7E
  db $08,$F8,$02,$02,$7E
  db $00,$F8,$02,$02,$3E
  db $F8,$F8,$01,$02,$3E
Metasprite04C9::
  db $0C
  db $F8,$08,$00,$02,$1E
  db $F8,$10,$01,$02,$1E
  db $00,$10,$02,$02,$1E
  db $08,$10,$02,$02,$5E
  db $10,$10,$01,$02,$5E
  db $10,$08,$00,$02,$5E
  db $10,$00,$00,$02,$7E
  db $10,$F8,$01,$02,$7E
  db $08,$F8,$02,$02,$7E
  db $00,$F8,$02,$02,$3E
  db $F8,$F8,$01,$02,$3E
  db $F8,$00,$00,$02,$3E
Metasprite04CA::
  db $04
  db $00,$00,$03,$02,$19
  db $00,$08,$04,$02,$19
  db $08,$00,$05,$02,$19
  db $08,$08,$06,$02,$19
Metasprite04CB::
  db $05
  db $08,$00,$0D,$01,$1D
  db $00,$00,$08,$01,$1E
  db $00,$08,$09,$01,$1E
  db $08,$00,$0A,$01,$1E
  db $08,$08,$0B,$01,$1E
Metasprite04CC::
  db $05
  db $08,$00,$0C,$01,$1B
  db $00,$00,$08,$01,$1A
  db $00,$08,$09,$01,$1A
  db $08,$00,$0A,$01,$1A
  db $08,$08,$0B,$01,$1A
Metasprite04CD::
  db $01
  db $FC,$FC,$62,$02,$18
Metasprite04CE::
  db $01
  db $FC,$FC,$62,$02,$38
Metasprite04CF::
  db $01
  db $00,$08,$11,$02,$18
Metasprite04D0::
  db $02
  db $00,$08,$11,$02,$18
  db $00,$00,$10,$02,$18
Metasprite04D1::
  db $03
  db $00,$08,$11,$02,$18
  db $00,$00,$10,$02,$18
  db $08,$00,$12,$02,$18
Metasprite04D2::
  db $04
  db $00,$08,$11,$02,$18
  db $00,$00,$10,$02,$18
  db $08,$00,$12,$02,$18
  db $00,$00,$11,$02,$38
Metasprite04D3::
  db $05
  db $00,$08,$11,$02,$18
  db $00,$00,$10,$02,$18
  db $08,$00,$12,$02,$18
  db $00,$00,$11,$02,$38
  db $00,$08,$10,$02,$38
Metasprite04D4::
  db $06
  db $00,$08,$11,$02,$18
  db $00,$00,$10,$02,$18
  db $08,$00,$12,$02,$18
  db $00,$00,$11,$02,$38
  db $00,$08,$10,$02,$38
  db $08,$08,$12,$02,$38
Metasprite04D5::
  db $01
  db $FC,$FC,$46,$02,$18
Metasprite04D6::
  db $01
  db $FC,$FC,$46,$02,$38
Metasprite04D7::
  db $01
  db $FC,$FC,$47,$02,$18
Metasprite04D8::
  db $01
  db $FC,$FC,$47,$02,$38
Metasprite04D9::
  db $01
  db $FC,$FC,$48,$02,$18
Metasprite04DA::
  db $01
  db $FC,$FC,$48,$02,$38
Metasprite04DB::
  db $04
  db $00,$00,$03,$02,$78
  db $00,$08,$02,$02,$78
  db $08,$00,$01,$02,$78
  db $08,$08,$00,$02,$78
Metasprite04DC::
  db $04
  db $00,$00,$07,$02,$78
  db $00,$08,$06,$02,$78
  db $08,$00,$05,$02,$78
  db $08,$08,$04,$02,$78
Metasprite04DD::
  db $04
  db $00,$00,$02,$02,$58
  db $00,$08,$03,$02,$58
  db $08,$00,$00,$02,$58
  db $08,$08,$01,$02,$58
Metasprite04DE::
  db $04
  db $00,$00,$06,$02,$58
  db $00,$08,$07,$02,$58
  db $08,$00,$04,$02,$58
  db $08,$08,$05,$02,$58
Metasprite04DF::
  db $08
  db $00,$F8,$00,$02,$18
  db $00,$00,$01,$02,$18
  db $00,$08,$02,$02,$18
  db $00,$10,$03,$02,$18
  db $08,$F8,$04,$02,$18
  db $08,$00,$05,$02,$18
  db $08,$08,$06,$02,$18
  db $08,$10,$07,$02,$18
Metasprite04E1::
  db $08
  db $00,$F8,$08,$02,$18
  db $00,$00,$09,$02,$18
  db $00,$08,$0A,$02,$18
  db $00,$10,$0B,$02,$18
  db $08,$F8,$0C,$02,$18
  db $08,$00,$0D,$02,$18
  db $08,$08,$0E,$02,$18
  db $08,$10,$0F,$02,$18
Metasprite04E2::
  db $08
  db $00,$F8,$10,$02,$18
  db $00,$00,$11,$02,$18
  db $00,$08,$12,$02,$18
  db $00,$10,$13,$02,$18
  db $08,$F8,$14,$02,$18
  db $08,$00,$15,$02,$18
  db $08,$08,$16,$02,$18
  db $08,$10,$17,$02,$18
Metasprite04E3::
  db $04
  db $00,$00,$10,$01,$19
  db $00,$08,$11,$01,$19
  db $08,$00,$12,$01,$19
  db $08,$08,$13,$01,$19
Metasprite04E4::
  db $04
  db $00,$00,$11,$01,$39
  db $00,$08,$10,$01,$39
  db $08,$00,$13,$01,$39
  db $08,$08,$12,$01,$39
Metasprite04E5::
  db $04
  db $00,$00,$14,$01,$19
  db $00,$08,$15,$01,$19
  db $08,$00,$16,$01,$19
  db $08,$08,$17,$01,$19
Metasprite04E6::
  db $04
  db $00,$00,$15,$01,$39
  db $00,$08,$14,$01,$39
  db $08,$00,$17,$01,$39
  db $08,$08,$16,$01,$39
Metasprite04E7::
  db $04
  db $00,$00,$18,$01,$1D
  db $00,$08,$19,$01,$1D
  db $08,$00,$1A,$01,$1D
  db $08,$08,$1B,$01,$1D
Metasprite04E8::
  db $04
  db $00,$00,$19,$01,$3D
  db $00,$08,$18,$01,$3D
  db $08,$00,$1B,$01,$3D
  db $08,$08,$1A,$01,$3D
Metasprite04E9::
  db $04
  db $00,$00,$1C,$01,$1D
  db $00,$08,$1D,$01,$1D
  db $08,$00,$1E,$01,$1D
  db $08,$08,$1F,$01,$1D
Metasprite04EA::
  db $04
  db $00,$00,$1D,$01,$3D
  db $00,$08,$1C,$01,$3D
  db $08,$00,$1F,$01,$3D
  db $08,$08,$1E,$01,$3D
MetaspriteTable04End::
