; Autogenerated by ./scripts/dump_tileset_scripts.py

SECTION "Partial Tilesets Table 0", ROMX[$4000], BANK[$28]
PartialTilesets0::
  dw PartialTileset0000
  dw PartialTileset0001
  dw PartialTileset0002
  dw PartialTileset0003
  dw PartialTileset0004
  dw PartialTileset0005
  dw PartialTileset0006
  dw PartialTileset0007
  dw PartialTileset0008
  dw PartialTileset0009
  dw PartialTileset0009
  dw PartialTileset000B
  dw PartialTileset000C
  dw PartialTileset000D
  dw PartialTileset000E
  dw PartialTileset000F
  dw PartialTileset0010
  dw PartialTileset0011
  dw PartialTileset0011
  dw PartialTileset0011
  dw PartialTileset0014
  dw PartialTileset0015
  dw PartialTileset0016
  dw PartialTileset0017
  dw PartialTileset0018
  dw PartialTileset0019
  dw PartialTileset001A
  dw PartialTileset001B
  dw PartialTileset001C
  dw PartialTileset001D
  dw PartialTileset001E
  dw PartialTileset001F
  dw PartialTileset0020
  dw PartialTileset0020
  dw PartialTileset0022
  dw PartialTileset0023
  dw PartialTileset0023
  dw PartialTileset0023
  dw PartialTileset0023
  dw PartialTileset0027
  dw PartialTileset0027
  dw PartialTileset0029
  dw PartialTileset0029
  dw PartialTileset0029
  dw PartialTileset0029
  dw PartialTileset002D
  dw PartialTileset002E
  dw PartialTileset002F
  dw PartialTileset0030
  dw PartialTileset0031
  dw PartialTileset0032
  dw PartialTileset0033
  dw PartialTileset0034
  dw PartialTileset0035
  dw PartialTileset0036
  dw PartialTileset0037
  dw PartialTileset0038
  dw PartialTileset0038
  dw PartialTileset0038
  dw PartialTileset0038
  dw PartialTileset0038
  dw PartialTileset003D
  dw PartialTileset003E
  dw PartialTileset003F
  dw PartialTileset0040
  dw PartialTileset0041
  dw PartialTileset0042
  dw PartialTileset0043
  dw PartialTileset0044
  dw PartialTileset0045
  dw PartialTileset0046
  dw PartialTileset0047
  dw PartialTileset0048
  dw PartialTileset0049
  dw PartialTileset004A
  dw PartialTileset004B
  dw PartialTileset004C
  dw PartialTileset004D
  dw PartialTileset004E
  dw PartialTileset004F
  dw PartialTileset0050
  dw PartialTileset0051
  dw PartialTileset0052
  dw PartialTileset0053
  dw PartialTileset0054
  dw PartialTileset0055
  dw PartialTileset0056
  dw PartialTileset0057
  dw PartialTileset0058
  dw PartialTileset0059
  dw PartialTileset005A
  dw PartialTileset005B
  dw PartialTileset005C
  dw PartialTileset005D
  dw PartialTileset005E
  dw PartialTileset005F
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0
  dw PartialTilesetTerminator0

PartialTileset0000::
  INCBIN "./build/tilesets/PartialTileset0000.2bpp"
PartialTileset0001::
  INCBIN "./build/tilesets/PartialTileset0001.2bpp"
PartialTileset0002::
  INCBIN "./build/tilesets/PartialTileset0002.2bpp"
PartialTileset0003::
  INCBIN "./build/tilesets/PartialTileset0003.2bpp"
PartialTileset0004::
  INCBIN "./build/tilesets/PartialTileset0004.2bpp"
PartialTileset0005::
  INCBIN "./build/tilesets/PartialTileset0005.2bpp"
PartialTileset0006::
  INCBIN "./build/tilesets/PartialTileset0006.2bpp"
PartialTileset0007::
  INCBIN "./build/tilesets/PartialTileset0007.2bpp"
PartialTileset0008::
  INCBIN "./build/tilesets/PartialTileset0008.2bpp"
PartialTileset0009::
  INCBIN "./build/tilesets/PartialTileset0009.2bpp"
PartialTileset000B::
  INCBIN "./build/tilesets/PartialTileset000B.2bpp"
PartialTileset000C::
  INCBIN "./build/tilesets/PartialTileset000C.2bpp"
PartialTileset000D::
  INCBIN "./build/tilesets/PartialTileset000D.2bpp"
PartialTileset000E::
  INCBIN "./build/tilesets/PartialTileset000E.2bpp"
PartialTileset000F::
  INCBIN "./build/tilesets/PartialTileset000F.2bpp"
PartialTileset0010::
  INCBIN "./build/tilesets/PartialTileset0010.2bpp"
PartialTileset0011::
  INCBIN "./build/tilesets/PartialTileset0011.2bpp"
PartialTileset0014::
  INCBIN "./build/tilesets/PartialTileset0014.2bpp"
PartialTileset0015::
  INCBIN "./build/tilesets/PartialTileset0015.2bpp"
PartialTileset0016::
  INCBIN "./build/tilesets/PartialTileset0016.2bpp"
PartialTileset0017::
  INCBIN "./build/tilesets/PartialTileset0017.2bpp"
PartialTileset0018::
  INCBIN "./build/tilesets/PartialTileset0018.2bpp"
PartialTileset0019::
  INCBIN "./build/tilesets/PartialTileset0019.2bpp"
PartialTileset001A::
  INCBIN "./build/tilesets/PartialTileset001A.2bpp"
PartialTileset001B::
  INCBIN "./build/tilesets/PartialTileset001B.2bpp"
PartialTileset001C::
  INCBIN "./build/tilesets/PartialTileset001C.2bpp"
PartialTileset001D::
  INCBIN "./build/tilesets/PartialTileset001D.2bpp"
PartialTileset001E::
  INCBIN "./build/tilesets/PartialTileset001E.2bpp"
PartialTileset001F::
  INCBIN "./build/tilesets/PartialTileset001F.2bpp"
PartialTileset0020::
  INCBIN "./build/tilesets/PartialTileset0020.2bpp"
PartialTileset0022::
  INCBIN "./build/tilesets/PartialTileset0022.2bpp"
PartialTileset0023::
  INCBIN "./build/tilesets/PartialTileset0023.2bpp"
PartialTileset0027::
  INCBIN "./build/tilesets/PartialTileset0027.2bpp"
PartialTileset0029::
  INCBIN "./build/tilesets/PartialTileset0029.2bpp"
PartialTileset002D::
  INCBIN "./build/tilesets/PartialTileset002D.2bpp"
PartialTileset002E::
  INCBIN "./build/tilesets/PartialTileset002E.2bpp"
PartialTileset002F::
  INCBIN "./build/tilesets/PartialTileset002F.2bpp"
PartialTileset0030::
  INCBIN "./build/tilesets/PartialTileset0030.2bpp"
PartialTileset0031::
  INCBIN "./build/tilesets/PartialTileset0031.2bpp"
PartialTileset0032::
  INCBIN "./build/tilesets/PartialTileset0032.2bpp"
PartialTileset0033::
  INCBIN "./build/tilesets/PartialTileset0033.2bpp"
PartialTileset0034::
  INCBIN "./build/tilesets/PartialTileset0034.2bpp"
PartialTileset0035::
  INCBIN cPartialTileset0035_GAMEVERSION
PartialTileset0036::
  INCBIN "./build/tilesets/PartialTileset0036.2bpp"
PartialTileset0037::
  INCBIN "./build/tilesets/PartialTileset0037.2bpp"
PartialTileset0038::
  INCBIN "./build/tilesets/PartialTileset0038.2bpp"
PartialTileset003D::
  INCBIN "./build/tilesets/PartialTileset003D.2bpp"
PartialTileset003E::
  INCBIN "./build/tilesets/PartialTileset003E.2bpp"
PartialTileset003F::
  INCBIN "./build/tilesets/PartialTileset003F.2bpp"
PartialTileset0040::
  INCBIN "./build/tilesets/PartialTileset0040.2bpp"
PartialTileset0041::
  INCBIN "./build/tilesets/PartialTileset0041.2bpp"
PartialTileset0042::
  INCBIN "./build/tilesets/PartialTileset0042.2bpp"
PartialTileset0043::
  INCBIN "./build/tilesets/PartialTileset0043.2bpp"
PartialTileset0044::
  INCBIN "./build/tilesets/PartialTileset0044.2bpp"
PartialTileset0045::
  INCBIN "./build/tilesets/PartialTileset0045.2bpp"
PartialTileset0046::
  INCBIN "./build/tilesets/PartialTileset0046.2bpp"
PartialTileset0047::
  INCBIN "./build/tilesets/PartialTileset0047.2bpp"
PartialTileset0048::
  INCBIN "./build/tilesets/PartialTileset0048.2bpp"
PartialTileset0049::
  INCBIN "./build/tilesets/PartialTileset0049.2bpp"
PartialTileset004A::
  INCBIN "./build/tilesets/PartialTileset004A.2bpp"
PartialTileset004B::
  INCBIN "./build/tilesets/PartialTileset004B.2bpp"
PartialTileset004C::
  INCBIN "./build/tilesets/PartialTileset004C.2bpp"
PartialTileset004D::
  INCBIN "./build/tilesets/PartialTileset004D.2bpp"
PartialTileset004E::
  INCBIN "./build/tilesets/PartialTileset004E.2bpp"
PartialTileset004F::
  INCBIN "./build/tilesets/PartialTileset004F.2bpp"
PartialTileset0050::
  INCBIN "./build/tilesets/PartialTileset0050.2bpp"
PartialTileset0051::
  INCBIN "./build/tilesets/PartialTileset0051.2bpp"
PartialTileset0052::
  INCBIN "./build/tilesets/PartialTileset0052.2bpp"
PartialTileset0053::
  INCBIN "./build/tilesets/PartialTileset0053.2bpp"
PartialTileset0054::
  INCBIN "./build/tilesets/PartialTileset0054.2bpp"
PartialTileset0055::
  INCBIN "./build/tilesets/PartialTileset0055.2bpp"
PartialTileset0056::
  INCBIN "./build/tilesets/PartialTileset0056.2bpp"
PartialTileset0057::
  INCBIN "./build/tilesets/PartialTileset0057.2bpp"
PartialTileset0058::
  INCBIN "./build/tilesets/PartialTileset0058.2bpp"
PartialTileset0059::
  INCBIN "./build/tilesets/PartialTileset0059.2bpp"
PartialTileset005A::
  INCBIN "./build/tilesets/PartialTileset005A.2bpp"
PartialTileset005B::
  INCBIN "./build/tilesets/PartialTileset005B.2bpp"
PartialTileset005C::
  INCBIN "./build/tilesets/PartialTileset005C.2bpp"
PartialTileset005D::
  INCBIN "./build/tilesets/PartialTileset005D.2bpp"
PartialTileset005E::
  INCBIN "./build/tilesets/PartialTileset005E.2bpp"
PartialTileset005F::
  INCBIN "./build/tilesets/PartialTileset005F.2bpp"
PartialTilesetTerminator0::

SECTION "Partial Tilesets Table 1", ROMX[$4000], BANK[$2D]
PartialTilesets1::
  dw PartialTileset0100
  dw PartialTileset0101
  dw PartialTileset0102
  dw PartialTileset0103
  dw PartialTileset0104
  dw PartialTileset0105
  dw PartialTileset0106
  dw PartialTileset0107
  dw PartialTileset0108
  dw PartialTileset0109
  dw PartialTileset010A
  dw PartialTileset010B
  dw PartialTileset010C
  dw PartialTileset010D
  dw PartialTileset010E
  dw PartialTileset010F
  dw PartialTileset0110
  dw PartialTileset0111
  dw PartialTileset0112
  dw PartialTileset0113
  dw PartialTileset0114
  dw PartialTileset0115
  dw PartialTileset0116
  dw PartialTileset0117
  dw PartialTileset0118
  dw PartialTileset0119
  dw PartialTileset011A
  dw PartialTileset011B
  dw PartialTileset011C
  dw PartialTileset011D
  dw PartialTileset011E
  dw PartialTileset011E
  dw PartialTileset011E
  dw PartialTileset0121
  dw PartialTileset0122
  dw PartialTileset0123
  dw PartialTileset0124
  dw PartialTileset0125
  dw PartialTileset0126
  dw PartialTileset0127
  dw PartialTileset0128
  dw PartialTileset0129
  dw PartialTileset012A
  dw PartialTileset012B
  dw PartialTileset012C
  dw PartialTileset012D
  dw PartialTileset012E
  dw PartialTileset012F
  dw PartialTileset0130
  dw PartialTileset0131
  dw PartialTileset0132
  dw PartialTileset0133
  dw PartialTileset0134
  dw PartialTileset0135
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1
  dw PartialTilesetTerminator1

PartialTileset0100::
  INCBIN "./build/tilesets/PartialTileset0100.2bpp"
PartialTileset0101::
  INCBIN "./build/tilesets/PartialTileset0101.2bpp"
PartialTileset0102::
  INCBIN "./build/tilesets/PartialTileset0102.2bpp"
PartialTileset0103::
  INCBIN "./build/tilesets/PartialTileset0103.2bpp"
PartialTileset0104::
  INCBIN "./build/tilesets/PartialTileset0104.2bpp"
PartialTileset0105::
  INCBIN "./build/tilesets/PartialTileset0105.2bpp"
PartialTileset0106::
  INCBIN "./build/tilesets/PartialTileset0106.2bpp"
PartialTileset0107::
  INCBIN "./build/tilesets/PartialTileset0107.2bpp"
PartialTileset0108::
  INCBIN "./build/tilesets/PartialTileset0108.2bpp"
PartialTileset0109::
  INCBIN "./build/tilesets/PartialTileset0109.2bpp"
PartialTileset010A::
  INCBIN "./build/tilesets/PartialTileset010A.2bpp"
PartialTileset010B::
  INCBIN "./build/tilesets/PartialTileset010B.2bpp"
PartialTileset010C::
  INCBIN "./build/tilesets/PartialTileset010C.2bpp"
PartialTileset010D::
  INCBIN "./build/tilesets/PartialTileset010D.2bpp"
PartialTileset010E::
  INCBIN "./build/tilesets/PartialTileset010E.2bpp"
PartialTileset010F::
  INCBIN "./build/tilesets/PartialTileset010F.2bpp"
PartialTileset0110::
  INCBIN "./build/tilesets/PartialTileset0110.2bpp"
PartialTileset0111::
  INCBIN "./build/tilesets/PartialTileset0111.2bpp"
PartialTileset0112::
  INCBIN "./build/tilesets/PartialTileset0112.2bpp"
PartialTileset0113::
  INCBIN "./build/tilesets/PartialTileset0113.2bpp"
PartialTileset0114::
  INCBIN "./build/tilesets/PartialTileset0114.2bpp"
PartialTileset0115::
  INCBIN "./build/tilesets/PartialTileset0115.2bpp"
PartialTileset0116::
  INCBIN "./build/tilesets/PartialTileset0116.2bpp"
PartialTileset0117::
  INCBIN "./build/tilesets/PartialTileset0117.2bpp"
PartialTileset0118::
  INCBIN "./build/tilesets/PartialTileset0118.2bpp"
PartialTileset0119::
  INCBIN "./build/tilesets/PartialTileset0119.2bpp"
PartialTileset011A::
  INCBIN "./build/tilesets/PartialTileset011A.2bpp"
PartialTileset011B::
  INCBIN "./build/tilesets/PartialTileset011B.2bpp"
PartialTileset011C::
  INCBIN "./build/tilesets/PartialTileset011C.2bpp"
PartialTileset011D::
  INCBIN "./build/tilesets/PartialTileset011D.2bpp"
PartialTileset011E::
  INCBIN "./build/tilesets/PartialTileset011E.2bpp"
PartialTileset0121::
  INCBIN "./build/tilesets/PartialTileset0121.2bpp"
PartialTileset0122::
  INCBIN "./build/tilesets/PartialTileset0122.2bpp"
PartialTileset0123::
  INCBIN "./build/tilesets/PartialTileset0123.2bpp"
PartialTileset0124::
  INCBIN "./build/tilesets/PartialTileset0124.2bpp"
PartialTileset0125::
  INCBIN "./build/tilesets/PartialTileset0125.2bpp"
PartialTileset0126::
  INCBIN "./build/tilesets/PartialTileset0126.2bpp"
PartialTileset0127::
  INCBIN "./build/tilesets/PartialTileset0127.2bpp"
PartialTileset0128::
  INCBIN "./build/tilesets/PartialTileset0128.2bpp"
PartialTileset0129::
  INCBIN "./build/tilesets/PartialTileset0129.2bpp"
PartialTileset012A::
  INCBIN "./build/tilesets/PartialTileset012A.2bpp"
PartialTileset012B::
  INCBIN "./build/tilesets/PartialTileset012B.2bpp"
PartialTileset012C::
  INCBIN "./build/tilesets/PartialTileset012C.2bpp"
PartialTileset012D::
  INCBIN "./build/tilesets/PartialTileset012D.2bpp"
PartialTileset012E::
  INCBIN "./build/tilesets/PartialTileset012E.2bpp"
PartialTileset012F::
  INCBIN "./build/tilesets/PartialTileset012F.2bpp"
PartialTileset0130::
  INCBIN "./build/tilesets/PartialTileset0130.2bpp"
PartialTileset0131::
  INCBIN "./build/tilesets/PartialTileset0131.2bpp"
PartialTileset0132::
  INCBIN "./build/tilesets/PartialTileset0132.2bpp"
PartialTileset0133::
  INCBIN "./build/tilesets/PartialTileset0133.2bpp"
PartialTileset0134::
  INCBIN "./build/tilesets/PartialTileset0134.2bpp"
PartialTileset0135::
  INCBIN "./build/tilesets/PartialTileset0135.2bpp"
PartialTilesetTerminator1::

SECTION "Partial Tilesets Table 2", ROMX[$4000], BANK[$61]
PartialTilesets2::
  dw PartialTileset0200
  dw PartialTileset0201
  dw PartialTileset0202
  dw PartialTileset0203
  dw PartialTileset0204
  dw PartialTileset0205
  dw PartialTileset0206
  dw PartialTileset0207
  dw PartialTileset0208
  dw PartialTileset0209
  dw PartialTileset020A
  dw PartialTileset020B
  dw PartialTileset020C
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2
  dw PartialTilesetTerminator2

PartialTileset0200::
  INCBIN "./build/tilesets/PartialTileset0200.2bpp"
PartialTileset0201::
  INCBIN "./build/tilesets/PartialTileset0201.2bpp"
PartialTileset0202::
  INCBIN "./build/tilesets/PartialTileset0202.2bpp"
PartialTileset0203::
  INCBIN "./build/tilesets/PartialTileset0203.2bpp"
PartialTileset0204::
  INCBIN "./build/tilesets/PartialTileset0204.2bpp"
PartialTileset0205::
  INCBIN "./build/tilesets/PartialTileset0205.2bpp"
PartialTileset0206::
  INCBIN "./build/tilesets/PartialTileset0206.2bpp"
PartialTileset0207::
  INCBIN "./build/tilesets/PartialTileset0207.2bpp"
PartialTileset0208::
  INCBIN "./build/tilesets/PartialTileset0208.2bpp"
PartialTileset0209::
  INCBIN "./build/tilesets/PartialTileset0209.2bpp"
PartialTileset020A::
  INCBIN "./build/tilesets/PartialTileset020A.2bpp"
PartialTileset020B::
  INCBIN "./build/tilesets/PartialTileset020B.2bpp"
PartialTileset020C::
  INCBIN "./build/tilesets/PartialTileset020C.2bpp"
PartialTilesetTerminator2::

SECTION "Partial Tilesets Table 3", ROMX[$4000], BANK[$29]
PartialTilesets3::
  dw PartialTileset0300
  dw PartialTileset0301
  dw PartialTileset0302
  dw PartialTileset0303
  dw PartialTileset0304
  dw PartialTileset0305
  dw PartialTileset0306
  dw PartialTileset0307
  dw PartialTileset0308
  dw PartialTileset0309
  dw PartialTileset0309
  dw PartialTileset030B
  dw PartialTileset030C
  dw PartialTileset030D
  dw PartialTileset030E
  dw PartialTileset030F
  dw PartialTileset0310
  dw PartialTileset0311
  dw PartialTileset0311
  dw PartialTileset0311
  dw PartialTileset0314
  dw PartialTileset0315
  dw PartialTileset0316
  dw PartialTileset0317
  dw PartialTileset0318
  dw PartialTileset0319
  dw PartialTileset031A
  dw PartialTileset031B
  dw PartialTileset031C
  dw PartialTileset031D
  dw PartialTileset031E
  dw PartialTileset031F
  dw PartialTileset0320
  dw PartialTileset0320
  dw PartialTileset0322
  dw PartialTileset0323
  dw PartialTileset0323
  dw PartialTileset0323
  dw PartialTileset0323
  dw PartialTileset0327
  dw PartialTileset0327
  dw PartialTileset0329
  dw PartialTileset0329
  dw PartialTileset0329
  dw PartialTileset0329
  dw PartialTileset032D
  dw PartialTileset032E
  dw PartialTileset032F
  dw PartialTileset0330
  dw PartialTileset0331
  dw PartialTileset0332
  dw PartialTileset0333
  dw PartialTileset0334
  dw PartialTileset0335
  dw PartialTileset0336
  dw PartialTileset0337
  dw PartialTileset0338
  dw PartialTileset0338
  dw PartialTileset0338
  dw PartialTileset0338
  dw PartialTileset0338
  dw PartialTileset033D
  dw PartialTileset033E
  dw PartialTileset033F
  dw PartialTileset0340
  dw PartialTileset0341
  dw PartialTileset0342
  dw PartialTileset0343
  dw PartialTileset0344
  dw PartialTileset0345
  dw PartialTileset0346
  dw PartialTileset0347
  dw PartialTileset0348
  dw PartialTileset0349
  dw PartialTileset034A
  dw PartialTileset034B
  dw PartialTileset034C
  dw PartialTileset034D
  dw PartialTileset034E
  dw PartialTileset034F
  dw PartialTileset0350
  dw PartialTileset0351
  dw PartialTileset0352
  dw PartialTileset0353
  dw PartialTileset0354
  dw PartialTileset0355
  dw PartialTileset0356
  dw PartialTileset0357
  dw PartialTileset0358
  dw PartialTileset0359
  dw PartialTileset035A
  dw PartialTileset035B
  dw PartialTileset035C
  dw PartialTileset035D
  dw PartialTileset035E
  dw PartialTileset035F
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3
  dw PartialTilesetTerminator3

PartialTileset0300::
  INCBIN "./build/tilesets/PartialTileset0300.2bpp"
PartialTileset0301::
  INCBIN "./build/tilesets/PartialTileset0301.2bpp"
PartialTileset0302::
  INCBIN "./build/tilesets/PartialTileset0302.2bpp"
PartialTileset0303::
  INCBIN "./build/tilesets/PartialTileset0303.2bpp"
PartialTileset0304::
  INCBIN "./build/tilesets/PartialTileset0304.2bpp"
PartialTileset0305::
  INCBIN "./build/tilesets/PartialTileset0305.2bpp"
PartialTileset0306::
  INCBIN "./build/tilesets/PartialTileset0306.2bpp"
PartialTileset0307::
  INCBIN "./build/tilesets/PartialTileset0307.2bpp"
PartialTileset0308::
  INCBIN "./build/tilesets/PartialTileset0308.2bpp"
PartialTileset0309::
  INCBIN "./build/tilesets/PartialTileset0309.2bpp"
PartialTileset030B::
  INCBIN "./build/tilesets/PartialTileset030B.2bpp"
PartialTileset030C::
  INCBIN "./build/tilesets/PartialTileset030C.2bpp"
PartialTileset030D::
  INCBIN "./build/tilesets/PartialTileset030D.2bpp"
PartialTileset030E::
  INCBIN "./build/tilesets/PartialTileset030E.2bpp"
PartialTileset030F::
  INCBIN "./build/tilesets/PartialTileset030F.2bpp"
PartialTileset0310::
  INCBIN "./build/tilesets/PartialTileset0310.2bpp"
PartialTileset0311::
  INCBIN "./build/tilesets/PartialTileset0311.2bpp"
PartialTileset0314::
  INCBIN "./build/tilesets/PartialTileset0314.2bpp"
PartialTileset0315::
  INCBIN "./build/tilesets/PartialTileset0315.2bpp"
PartialTileset0316::
  INCBIN "./build/tilesets/PartialTileset0316.2bpp"
PartialTileset0317::
  INCBIN "./build/tilesets/PartialTileset0317.2bpp"
PartialTileset0318::
  INCBIN "./build/tilesets/PartialTileset0318.2bpp"
PartialTileset0319::
  INCBIN "./build/tilesets/PartialTileset0319.2bpp"
PartialTileset031A::
  INCBIN "./build/tilesets/PartialTileset031A.2bpp"
PartialTileset031B::
  INCBIN "./build/tilesets/PartialTileset031B.2bpp"
PartialTileset031C::
  INCBIN "./build/tilesets/PartialTileset031C.2bpp"
PartialTileset031D::
  INCBIN "./build/tilesets/PartialTileset031D.2bpp"
PartialTileset031E::
  INCBIN "./build/tilesets/PartialTileset031E.2bpp"
PartialTileset031F::
  INCBIN "./build/tilesets/PartialTileset031F.2bpp"
PartialTileset0320::
  INCBIN "./build/tilesets/PartialTileset0320.2bpp"
PartialTileset0322::
  INCBIN "./build/tilesets/PartialTileset0322.2bpp"
PartialTileset0323::
  INCBIN "./build/tilesets/PartialTileset0323.2bpp"
PartialTileset0327::
  INCBIN "./build/tilesets/PartialTileset0327.2bpp"
PartialTileset0329::
  INCBIN "./build/tilesets/PartialTileset0329.2bpp"
PartialTileset032D::
  INCBIN "./build/tilesets/PartialTileset032D.2bpp"
PartialTileset032E::
  INCBIN "./build/tilesets/PartialTileset032E.2bpp"
PartialTileset032F::
  INCBIN "./build/tilesets/PartialTileset032F.2bpp"
PartialTileset0330::
  INCBIN "./build/tilesets/PartialTileset0330.2bpp"
PartialTileset0331::
  INCBIN "./build/tilesets/PartialTileset0331.2bpp"
PartialTileset0332::
  INCBIN "./build/tilesets/PartialTileset0332.2bpp"
PartialTileset0333::
  INCBIN "./build/tilesets/PartialTileset0333.2bpp"
PartialTileset0334::
  INCBIN "./build/tilesets/PartialTileset0334.2bpp"
PartialTileset0335::
  INCBIN cPartialTileset0335_GAMEVERSION
PartialTileset0336::
  INCBIN "./build/tilesets/PartialTileset0336.2bpp"
PartialTileset0337::
  INCBIN "./build/tilesets/PartialTileset0337.2bpp"
PartialTileset0338::
  INCBIN "./build/tilesets/PartialTileset0338.2bpp"
PartialTileset033D::
  INCBIN "./build/tilesets/PartialTileset033D.2bpp"
PartialTileset033E::
  INCBIN "./build/tilesets/PartialTileset033E.2bpp"
PartialTileset033F::
  INCBIN "./build/tilesets/PartialTileset033F.2bpp"
PartialTileset0340::
  INCBIN "./build/tilesets/PartialTileset0340.2bpp"
PartialTileset0341::
  INCBIN "./build/tilesets/PartialTileset0341.2bpp"
PartialTileset0342::
  INCBIN "./build/tilesets/PartialTileset0342.2bpp"
PartialTileset0343::
  INCBIN "./build/tilesets/PartialTileset0343.2bpp"
PartialTileset0344::
  INCBIN "./build/tilesets/PartialTileset0344.2bpp"
PartialTileset0345::
  INCBIN "./build/tilesets/PartialTileset0345.2bpp"
PartialTileset0346::
  INCBIN "./build/tilesets/PartialTileset0346.2bpp"
PartialTileset0347::
  INCBIN "./build/tilesets/PartialTileset0347.2bpp"
PartialTileset0348::
  INCBIN "./build/tilesets/PartialTileset0348.2bpp"
PartialTileset0349::
  INCBIN "./build/tilesets/PartialTileset0349.2bpp"
PartialTileset034A::
  INCBIN "./build/tilesets/PartialTileset034A.2bpp"
PartialTileset034B::
  INCBIN "./build/tilesets/PartialTileset034B.2bpp"
PartialTileset034C::
  INCBIN "./build/tilesets/PartialTileset034C.2bpp"
PartialTileset034D::
  INCBIN "./build/tilesets/PartialTileset034D.2bpp"
PartialTileset034E::
  INCBIN "./build/tilesets/PartialTileset034E.2bpp"
PartialTileset034F::
  INCBIN "./build/tilesets/PartialTileset034F.2bpp"
PartialTileset0350::
  INCBIN "./build/tilesets/PartialTileset0350.2bpp"
PartialTileset0351::
  INCBIN "./build/tilesets/PartialTileset0351.2bpp"
PartialTileset0352::
  INCBIN "./build/tilesets/PartialTileset0352.2bpp"
PartialTileset0353::
  INCBIN "./build/tilesets/PartialTileset0353.2bpp"
PartialTileset0354::
  INCBIN "./build/tilesets/PartialTileset0354.2bpp"
PartialTileset0355::
  INCBIN "./build/tilesets/PartialTileset0355.2bpp"
PartialTileset0356::
  INCBIN "./build/tilesets/PartialTileset0356.2bpp"
PartialTileset0357::
  INCBIN "./build/tilesets/PartialTileset0357.2bpp"
PartialTileset0358::
  INCBIN "./build/tilesets/PartialTileset0358.2bpp"
PartialTileset0359::
  INCBIN "./build/tilesets/PartialTileset0359.2bpp"
PartialTileset035A::
  INCBIN "./build/tilesets/PartialTileset035A.2bpp"
PartialTileset035B::
  INCBIN "./build/tilesets/PartialTileset035B.2bpp"
PartialTileset035C::
  INCBIN "./build/tilesets/PartialTileset035C.2bpp"
PartialTileset035D::
  INCBIN "./build/tilesets/PartialTileset035D.2bpp"
PartialTileset035E::
  INCBIN "./build/tilesets/PartialTileset035E.2bpp"
PartialTileset035F::
  INCBIN "./build/tilesets/PartialTileset035F.2bpp"
PartialTilesetTerminator3::

SECTION "Partial Tilesets Table 4", ROMX[$4000], BANK[$2A]
PartialTilesets4::
  dw PartialTileset0400
  dw PartialTileset0401
  dw PartialTileset0402
  dw PartialTileset0403
  dw PartialTileset0404
  dw PartialTileset0405
  dw PartialTileset0406
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0407
  dw PartialTileset0461
  dw PartialTileset0462
  dw PartialTileset0463
  dw PartialTileset0464
  dw PartialTileset0465
  dw PartialTileset0466
  dw PartialTileset0467
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0468
  dw PartialTileset0491
  dw PartialTileset0492
  dw PartialTileset0493
  dw PartialTileset0494
  dw PartialTileset0495
  dw PartialTileset0496
  dw PartialTileset0497
  dw PartialTileset0498
  dw PartialTileset0499
  dw PartialTileset049A
  dw PartialTileset049B
  dw PartialTileset049C
  dw PartialTileset049D
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4
  dw PartialTilesetTerminator4

PartialTileset0400::
  INCBIN "./build/tilesets/PartialTileset0400.2bpp"
PartialTileset0401::
  INCBIN "./build/tilesets/PartialTileset0401.2bpp"
PartialTileset0402::
  INCBIN "./build/tilesets/PartialTileset0402.2bpp"
PartialTileset0403::
  INCBIN "./build/tilesets/PartialTileset0403.2bpp"
PartialTileset0404::
  INCBIN "./build/tilesets/PartialTileset0404.2bpp"
PartialTileset0405::
  INCBIN "./build/tilesets/PartialTileset0405.2bpp"
PartialTileset0406::
  INCBIN "./build/tilesets/PartialTileset0406.2bpp"
PartialTileset0407::
  INCBIN "./build/tilesets/PartialTileset0407.2bpp"
PartialTileset0461::
  INCBIN "./build/tilesets/PartialTileset0461.2bpp"
PartialTileset0462::
  INCBIN "./build/tilesets/PartialTileset0462.2bpp"
PartialTileset0463::
  INCBIN "./build/tilesets/PartialTileset0463.2bpp"
PartialTileset0464::
  INCBIN "./build/tilesets/PartialTileset0464.2bpp"
PartialTileset0465::
  INCBIN "./build/tilesets/PartialTileset0465.2bpp"
PartialTileset0466::
  INCBIN "./build/tilesets/PartialTileset0466.2bpp"
PartialTileset0467::
  INCBIN "./build/tilesets/PartialTileset0467.2bpp"
PartialTileset0468::
  INCBIN "./build/tilesets/PartialTileset0468.2bpp"
PartialTileset0491::
  INCBIN "./build/tilesets/PartialTileset0491.2bpp"
PartialTileset0492::
  INCBIN "./build/tilesets/PartialTileset0492.2bpp"
PartialTileset0493::
  INCBIN "./build/tilesets/PartialTileset0493.2bpp"
PartialTileset0494::
  INCBIN "./build/tilesets/PartialTileset0494.2bpp"
PartialTileset0495::
  INCBIN "./build/tilesets/PartialTileset0495.2bpp"
PartialTileset0496::
  INCBIN "./build/tilesets/PartialTileset0496.2bpp"
PartialTileset0497::
  INCBIN "./build/tilesets/PartialTileset0497.2bpp"
PartialTileset0498::
  INCBIN "./build/tilesets/PartialTileset0498.2bpp"
PartialTileset0499::
  INCBIN "./build/tilesets/PartialTileset0499.2bpp"
PartialTileset049A::
  INCBIN "./build/tilesets/PartialTileset049A.2bpp"
PartialTileset049B::
  INCBIN "./build/tilesets/PartialTileset049B.2bpp"
PartialTileset049C::
  INCBIN "./build/tilesets/PartialTileset049C.2bpp"
PartialTileset049D::
  INCBIN "./build/tilesets/PartialTileset049D.2bpp"
PartialTilesetTerminator4::

SECTION "Partial Tilesets Table 5", ROMX[$4000], BANK[$2C]
PartialTilesets5::
  dw PartialTileset0500
  dw PartialTileset0501
  dw PartialTileset0502
  dw PartialTileset0503
  dw PartialTileset0504
  dw PartialTileset0505
  dw PartialTileset0506
  dw PartialTileset0507
  dw PartialTileset0508
  dw PartialTileset0509
  dw PartialTileset050A
  dw PartialTileset050B
  dw PartialTileset050C
  dw PartialTileset050D
  dw PartialTileset050E
  dw PartialTileset050F
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5
  dw PartialTilesetTerminator5

PartialTileset0500::
  INCBIN "./build/tilesets/PartialTileset0500.2bpp"
PartialTileset0501::
  INCBIN "./build/tilesets/PartialTileset0501.2bpp"
PartialTileset0502::
  INCBIN "./build/tilesets/PartialTileset0502.2bpp"
PartialTileset0503::
  INCBIN "./build/tilesets/PartialTileset0503.2bpp"
PartialTileset0504::
  INCBIN "./build/tilesets/PartialTileset0504.2bpp"
PartialTileset0505::
  INCBIN "./build/tilesets/PartialTileset0505.2bpp"
PartialTileset0506::
  INCBIN "./build/tilesets/PartialTileset0506.2bpp"
PartialTileset0507::
  INCBIN "./build/tilesets/PartialTileset0507.2bpp"
PartialTileset0508::
  INCBIN "./build/tilesets/PartialTileset0508.2bpp"
PartialTileset0509::
  INCBIN "./build/tilesets/PartialTileset0509.2bpp"
PartialTileset050A::
  INCBIN "./build/tilesets/PartialTileset050A.2bpp"
PartialTileset050B::
  INCBIN "./build/tilesets/PartialTileset050B.2bpp"
PartialTileset050C::
  INCBIN "./build/tilesets/PartialTileset050C.2bpp"
PartialTileset050D::
  INCBIN "./build/tilesets/PartialTileset050D.2bpp"
PartialTileset050E::
  INCBIN "./build/tilesets/PartialTileset050E.2bpp"
PartialTileset050F::
  INCBIN "./build/tilesets/PartialTileset050F.2bpp"
PartialTilesetTerminator5::

