name: Spell Check

on: 
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/medabots/medarot3:tr_EN

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          path: 'medarot3'

      - name: Get latest text from source
        working-directory: 'medarot3'
        env:
          TRANSLATION_SHEET: sheet.xlsx
        run: |
          wget -q --no-check-certificate "${{ secrets.TRANSLATION_SHEET_URL_SOURCE }}" -O $TRANSLATION_SHEET
          make csv_from_xlsx
          git status --porcelain

      - name: Run spell check
        working-directory: 'medarot3'
        run: |
          make test_spellcheck > ~/spellcheck_results.txt
          cat ~/spellcheck_results.txt

      - name: Archive spell check results
        uses: actions/upload-artifact@v2
        with:
          name: spellcheck_results.txt
          path: ~/spellcheck_results.txt
          retention-days: 1